### ISSUE TITLE
Prevent toolboxes from being deleted on `podman system prune`

### ISSUE THREAD

**Issue by kuba3351** [containers/toolbox#1005]
**Is your feature request related to a problem? Please describe.**
If working with the containers it is very easy to get out of free space on the hard drive. It is very common to use `podman system prune` in this situation. It removes all stopped containers in a single command and reclaiming a lot of space, but it will also remove stopped toolboxes because there are technically a podman containers. I would like to preserve my toolboxes while using `podman system prune`.

**Describe the solution you'd like**
I think it is possible to implement a systemd service that will start all the toolboxes on system boot, so the Toolboxes will not be deleted when executing `podman system prune`

**Describe alternatives you've considered**
An alternative would be to mark toolbox containers as toolboxes in podman, and change the implementation of `podman system prune` to not delete toolboxes, but this requires changes in the podman side, so I think systemd service is simpler.

**Comment by JayDoubleu** [comment]
You can filter out toolbox label when running prune.

**Comment by juhp** [comment]
I would recommend using `podman image prune` instead - I think that might be what you want.

**Comment by debarshiray** [comment]
I am going to close this issue now.

However, thanks for stopping by and playing around with Toolbx!
