### ISSUE TITLE
Create a Fedora 37 toolbox image

### ISSUE THREAD

**Issue by travier** [containers/toolbox#1011]
**Is your feature request related to a problem? Please describe.**

Create a Fedora 37 toolbox. We need this to test toolbox in Fedora CoreOS. See https://github.com/coreos/fedora-coreos-tracker/issues/1103

**Comment by travier** [comment]
There are probably other steps that I don't know about on the infra side of things.

**Comment by HarryMichal** [comment]
There seems to be an upstream issue with building images -> https://pagure.io/releng/issue/10658

**Comment by juhp** [comment]
Actually the first step is to have an image tagged with `fedora:37` which is currently missing.

**Comment by juhp** [comment]
fedora:37 is fixed, but now the fedora-toolbox:37 build fails in OBS in the same way as fedora-toolbox:36.

**Comment by juhp** [comment]
I have built the container images now - see the releng if you want to know the details..

This ticket can be closed now
