### ISSUE TITLE
/etc/profile.d/toolbox.sh:26: bad substitution on Fedora Kinoite

### ISSUE THREAD

**Issue by FilBot3** [containers/toolbox#1017]
# Describe the bug

> A clear and concise description of *what the bug is*. If possible, re-run the command(s) with `--log-level debug` and put the output here.

When I launch a new Zsh (oh-my-zsh) session, I get this output.

```bash
/etc/profile.d/toolbox.sh:26: bad substitution
```

## Steps how to reproduce the behaviour 

1. Open Konsole, see error.

## Expected behaviour

> A clear and concise description of what you *expected to happen*.

No output when starting the session.

## Actual behaviour

> A clear and concise description of what *actually happened*.

I see.

```bash
/etc/profile.d/toolbox.sh:26: bad substitution
```

## Screenshots 

> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/3039509/156198255-3ce16860-af66-45fa-971f-c973fdac111e.png)

**Output of `toolbox --version` (v0.0.90+)**

```bash
❯ toolbox --version
toolbox version 0.0.99.3
```

**Toolbox package info (`rpm -q toolbox`)**

```bash
❯ rpm -q toolbox
toolbox-0.0.99.3-2.fc35.x86_64
```

**Output of `podman version`**

```bash
❯ podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 15:45:07 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

```bash
❯ rpm -q podman
podman-3.4.4-1.fc35.x86_64
```

**Info about your OS**

```bash
❯ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35.20220228.0 (Kinoite)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35.20220228.0 (Kinoite)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-kinoite/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Kinoite"
VARIANT_ID=kinoite
OSTREE_VERSION='35.20220228.0'
```

**Additional context**
> Add any other context about the problem here.
> When did the issue start occurring? After an update (what packages were updated)?
> If the issue is about operating with containers/images (creating, using, deleting,..), share here what image you used. If you're unsure, share here the output of `toolbox list -i` (shows all toolbox images on your system).

The issue started around the 15th of January. I just now got annoyed with it.

> If you see an error message saying: `Error: invalid entry point PID of container <name-of-container>`, add to the ticket output of command `podman start --attach <name-of-container>`.

**Comment by kmmiles** [comment]
So the problem there is:
```bash
echo "${VARIANT_ID^}"
```
Just rip the `^` off if you want it to shut up.

Basically it attempts to uppercase the first letter of `$VARIANT_ID`, but that type of parameter expansion is a bash-ism.
You can do similar in zsh, but it's of course a `zsh`ism:
```bash
echo "${VARIANT_ID:0:1:u}${VARIANT_ID:1}"
```

I suppose a nicer fix would be to simply use `VARIANT`, which is already a pretty name, or worst case use `sed` to perform the uppercasing, which will work in POSIX, bash, and zsh.

**Comment by debarshiray** [comment]
> When I launch a new Zsh (oh-my-zsh) session, I get this output.
> 
> ```shell
> /etc/profile.d/toolbox.sh:26: bad substitution
> ```

Yes, this is a fallout from https://github.com/containers/toolbox/pull/881

> The issue started around the 15th of January. I just now got annoyed with it.

That's about a month after the 0.0.99.3 release came out, where this problem was introduced.  So it adds up.

**Comment by debarshiray** [comment]
> I suppose a nicer fix would be to simply use `VARIANT`, which
> is already a pretty name, or worst case use `sed` to perform
> the uppercasing, which will work in POSIX, bash, and zsh.

I think, these days we should use `PRETTY_NAME` and let the downstream distributor decide how the host operating system should be called. PRETTY_NAME has the advantage of being effectively a mandatory field. The os-release(5) [manual](https://www.freedesktop.org/software/systemd/man/os-release.html) says:
```
If not set, a default of "PRETTY_NAME="Linux"" may be used.
```

In comparison, `VARIANT` and `VARIANT_ID` are optional fields.

Note that the [original](https://github.com/containers/toolbox/commit/79f59b667b22b647253cb047a9c04cd60d1db03a) welcome banner was from a time when on Fedora Silverblue `VARIANT` and `VARIANT_ID` were set to the same values as on Fedora Workstation. That's why it started off hard-coded as Fedora Silverblue.

Fedora Silverblue [got its own](https://pagure.io/workstation-ostree-config/c/c18ef957d11862d32f362722931dbfdf1f5beb0d) `VARIANT` and `VARIANT_ID` only as recently as Fedora 32.

**Comment by debarshiray** [comment]
Fixed by https://github.com/containers/toolbox/pull/1177
