### ISSUE TITLE
Be more explicit about security implications in project description

### ISSUE THREAD

**Issue by laolux** [containers/toolbox#1020]
**Is your feature request related to a problem? Please describe.**
Quite a few people tend to believe that toolbox is a security mechanism to run untrusted software in a container. This is not really true, as toolbox containers can access all files in the user's home directory and thus cause havoc.

**Describe the solution you'd like**
Make it more explicit in the project documentation that a toolbox can access all private files of a user and thus does not protect against malicious software. I know that it is written that toolbox provides "access to the user's home directory", but I think it would be good to explicitly spell out that this means that malicious software inside a toolbox can steal, encrypt and delete all your personal data, just like malicious software outside a toolbox.

**Describe alternatives you've considered**
One could argue that it should be obvious that toolbox does not protect against malicious software, but I think it would be better to explicitly warn about that.

**Comment by debarshiray** [comment]
Done in https://github.com/containers/toolbox/pull/1182 and https://github.com/containers/containertoolbx.org/pull/29
