### ISSUE TITLE
Functionality similar to nix-shell/direnv

### ISSUE THREAD

**Issue by jcdickinson** [containers/toolbox#1033]
**Is your feature request related to a problem? Please describe.**

If I want to keep project dependencies apart, it's annoying to have to manually (and remembering to) juggle the containers/toolboxes. I also envy developers who can set up a working development environment for an arbitrary project after entering one command.

**Describe the solution you'd like**

Something like nix-shell/direnv.

Off the top of my head, this could look something like:

1. During `toolbox create` search for a file such as `toolbx-env` in ancestor directories. If this file is found:
1.1. Read the contents of the file, a single line which is the name/tag of the image to use.
1.2. Warn the user that the container will run with unrestricted access to their system.
1.3. Assuming they answer 'y' (or pass some `--yes` flag), use the `toolbx-env` as the default container.
1.4. Give the container a label containing the basename of the toolbx-env file.
2. During `toolbox enter` search for the `toolbx-env` file in ancestor directories. If this file is found:
2.1. Search for a container containing the correct basename label.
2.2. If the container is found, use that instead.

* Would it be possible to automatically switch between containers when `pwd` changes?
* Any ideas for allowing the end-user-developer to customize the container further?

**Describe alternatives you've considered**

The `toolbx-env` file could contain an entire buildah script, something like VSCode remote containers. That smells like extreme fragility to me, though, because buildah scripts are (by nature) more freeform than a Dockerfile. This could also be replicated by having a script that builds the image (which might even end with `toolbox create`), and then simply have the end-user-developer execute it after cloning the repo.

**Additional context**

[`nix-shell` is a very good example of this.](https://nixos.org/manual/nix/unstable/command-ref/nix-shell.html) After cloning a project that has it set up, all you need to do is run `nix-shell` from the root of the clone. Nix will set up a shell for you and drop you into it.

**Comment by yurigba** [comment]
I have thought of something very similar. You can have just a toolboxfile that you are able to be read when using `toolbox enter`. Then it will set all the parameters like json or yaml. Also, configure environment variables to be set on the specific toolbox.

We could use a "safe" version of the toolboxfile that restricts usage to commands like choosing the right container.
Then if the container has to do something like change environment variables, it should be something like nix. So every change afterwards is temporary and will be persistent only inside the container. But this does not implies that there should be no warnings.

**Comment by akdev1l** [comment]
I think you can create a `Containerfile`:

```
FROM fedora-toolbox:36

RUN sudo dnf install cmake 'gcc-c++' $somelibs
```

then do `podman build -t mycoolapp:builder` and then `toolbx create --image mycoolapp:builder`

I think that should work for what you want, reinventing another format seems like a lot of work for no clear benefit imo
