### ISSUE TITLE
Only sharing enough to open GUI apps

### ISSUE THREAD

**Issue by kisccz** [containers/toolbox#1040]
**Is your feature request related to a problem? Please describe.**
'm always frustrated when I see toolbox containers and how they have access to all my home folder. I just want a podman container that shares enough resources with my system to launch GUI applications without giving it acces to my system. 

**Describe the solution you'd like**
A container that is isolated from my system with its own filesystem but can launch GUI apps. Even better if there was a permission system where the user chooses what the container has access to

**Describe alternatives you've considered**
Docker containers can open GUI apps in an isolated environment. I prefer podman though

**Additional context**
You have this functionality already, I just want the toolbox container to be more isolated from my system while sharing only the things I want it to. I just need it for GUI apps for now

**Comment by whs-dot-hk** [comment]
I like your idea, I think toolbox is missing a way to start a container with packages and personalize configures (examples would be the kickstart files or the preseed files)

**Comment by akdev1l** [comment]
I would recommend spending some time reading `podman-run(1)`

what you want is something like:

```
podman run --rm -it \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY \
   fedora:latest
```

Passes through the X socket and the `DISPLAY

**Comment by HarryMichal** [comment]
Hi @kisccz! At this time isolation of the container environment from the host environment is not among the project's [goals](https://github.com/containers/toolbox/blob/main/GOALS.md).

Toolbx is meant to be mainly a development & debugging tool which also happens to provide certain additional use cases (e.g., running GUI apps available as RPM package but not as a Flatpak on Fedora Silverblue without layering on the host system). We're not focusing on those very use cases.

As has been mentioned in https://github.com/containers/podman/issues/13830, if you're only looking to run GUI applications and require sandboxing coupled with a permission system, you should be looking at [Flatpak](https://github.com/flatpak/flatpak).
