### ISSUE TITLE
toolbox list output contains duplicate image records

### ISSUE THREAD

**Issue by mkrajnak** [containers/toolbox#1043]
**Describe the bug**
this bug was initially created downstream, I am creating it after discussion with @debarshiray as we want to extend discussion to upstream 

**Steps how to reproduce the behaviour**
```
$ podman pull <INTERNAL_URL>/toolbox-container:9.0.0-9  
Trying to pull <INTERNAL_URL>/toolbox-container:9.0.0-9  ...
Getting image source signatures
Copying blob b1641283b956 done  
Copying blob 26f1167feaf7 done  
Copying blob adffa6963146 done  
Copying config e793d00bc6 done  
Writing manifest to image destination
Storing signatures
e793d00bc6295609626f1eae4084d4a767a751f4f1d4c3c3fc5c75d1b1c6680c

[test@rhel-8 ~]$ skopeo copy <INTERNAL_URL>/toolbox-container:9.0.0-9  containers-storage:registry.access.redhat.com/ubi9/toolbox:latest
Getting image source signatures
Copying blob e6a13b8f88ad skipped: already exists  
Copying blob 352ba846236b skipped: already exists  
Copying blob 3ba8c926eef9 skipped: already exists  
Copying config e793d00bc6 done  
Writing manifest to image destination
Storing signatures
[test@fedora redhat-linux-build]$ podman images
REPOSITORY                                                       TAG         IMAGE ID      CREATED      SIZE
registry.access.redhat.com/ubi9/toolbox                          latest      c24104d7b237  13 days ago  596 MB
<INTERNAL_URL>/rh-osbs/toolbox-container  9.0.0-9     c24104d7b237  13 days ago  596 MB
[test@fedora redhat-linux-build]$ toolbox list 
IMAGE ID      IMAGE NAME                                      CREATED
c24104d7b237  registry.access.redhat.com/ubi9/toolbox:latest  13 days ago
c24104d7b237  registry.access.redhat.com/ubi9/toolbox:latest  13 days ago
```

As you can see, output of `toolbox list` show those images as the same image, however those are actually 2 images that have 2 human readable names:

$ podman images --format json":
```
Image 1:

"Id": "e9e5f02b635db0130339d8e6ba8c873030dfcc24b075f96a8c4cdb743a9b6eac",
...
 "Names": [
            " registry.access.redhat.com/ubi9/toolbox:latest ",
            " <INTERNAL_URL>/toolbox-container:9.0.0-9 "
        ],

Image 2:

"Id": "e9e5f02b635db0130339d8e6ba8c873030dfcc24b075f96a8c4cdb743a9b6eac",
...
"Names": [
            " registry.access.redhat.com/ubi9/toolbox:latest  ",
            " <INTERNAL_URL>/toolbox-container:9.0.0-9 "
        ],  
```
The field that could actually distinguish those images is a TAG but it's not a part of JSON output, to obtain the TAG you have to switch to Go Template:

```
$  podman images   --format "{{.ID}}  {{.Tag}}"
c24104d7b237  latest
c24104d7b237  9.0.0-9
```

**Expected behaviour**
I am not sure what should be the expected behaviour but I would add the tag so we can see that those are actually two images.

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.3

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.3-4.fc36.x86_64

**Output of `podman version`**
e.g.,
```
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.18
Built:        Fri Apr  1 20:08:04 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-4.0.3-1.fc37.x86_64

**Info about your OS**
Fedora release 37 (Rawhide)

**Comment by debarshiray** [comment]
I took the liberty to fix some minor typos in the URLs.  The links to `registry.access.redhat.com` are public, or soon to be public, so we don't need to hide them.  :)

**Comment by debarshiray** [comment]
`toolbox list` could behave the same way as `podman images`.  ie., list each human-readable name for a given ID.  That way it's very clear to the user that the same image can be called by different names.

Or, we can only show one of the human-readable names for an ID, but then we would be keeping some information from the user, which might confuse her.

Whatever we do, the current behaviour of repeating the same name is definitely a bug.

**Comment by debarshiray** [comment]
> The field that could actually distinguish those images is a TAG but it's not
> a part of JSON output

The tag, on it's own, isn't enough.  eg., we could have an image with two different names that both have the `latest` tag.

It's the full name, including the URL of the registry and the tag that clearly identifies an image.
