### ISSUE TITLE
Add `--forward-fd` to `toolbox run`

### ISSUE THREAD

**Issue by allisonkarlitskaya** [containers/toolbox#1066]
Basically, similar in spirit to `flatpak-spawn --forward-fd=` and `podman exec --preserve-fds=` it would be lovely to be able to do the same with Toolbox.

An alternative to this would be a "dry-run" mode for `toolbox run` that shows me which `podman` commandline would be used, allowing me to hack it for myself.

As a workaround, for the time being, I'm running `toolbox run env` to start the toolbox and get a list of the environment variables and then constructing an approximate `podman exec` invocation using the output.

**Comment by debarshiray** [comment]
Yes, I had considered adding this in the past, but I wanted to wait until one more person showed up with a real world use case.

Would you also want a `--forward-fd` for `toolbox enter`?  Or only for `run`?

Maybe you already have a patch / branch / pull request somewhere?  :)  It would be nice if we could come up with a nifty little test case for this.

**Comment by debarshiray** [comment]
I am looking forward to Boxi using this, once we get a release out.
