### ISSUE TITLE
registry.fedoraproject.org registry seems to be deprecated

### ISSUE THREAD

**Issue by alexsaezm** [containers/toolbox#1069]
[From a thread at devel@lists.fedoraproject.org](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/3UF7FQY6L4X6MIQWKUGCTXSFBGMPKQRH/#LPHOIWIMNACOVQGX73DDFNUSJDBDDNHS), looks like registry.fedoraproject.org is not updated anymore.
Apparently, the new registry is at quay.io -> https://quay.io/organization/fedora/

**Comment by debarshiray** [comment]
Yes, I am aware of https://pagure.io/fedora-infrastructure/issue/10386

As far as I know, folks are looking at moving `registry.fedoraproject.org` to `quay.io`, but nothing has happened yet.  It's too early to declare `registry.fedoraproject.org` as deprecated.  :)

**Comment by debarshiray** [comment]
I am tentatively closing this.  We can't do much unless there's some movement in https://pagure.io/fedora-infrastructure/issue/10386

Regardless, thanks for the heads-up!
