### ISSUE TITLE
`.local/bin` not on path for applications which are run with toolbox run

### ISSUE THREAD

**Issue by VarLad** [containers/toolbox#1076]
**Describe the bug**
If I open an editor as such `toolbox run hx /path/to/file.extension`, LSP doesn't work, since the language is installed in `.local/bin`. The only workaround is to do `toolbox enter` and `hx /path/to/file.extension`.
The same occurs for shells. Whether I use `SHELL=something toolbox enter` or `toolbox run shell`, I get the same, other than bash, no shell has `.local/bin` on path. I've tried it for nushell and fish

Essentially, anything opened with `toolbox run` doesn't have `.local/bin` on path

**Steps how to reproduce the behaviour**
Mentioned above

**Expected behaviour**
Everything opened with `toolbox enter` has `.local/bin` on the PATH

**Actual behaviour**
`.local/bin` is not on the path

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.3

**Toolbox package info (`rpm -q toolbox`)**
e.g., `toolbox-0.0.18-2.fc32.noarch`

**Output of `podman version`**
e.g.,
```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 15 20:01:58 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-4.1.1-1.fc36.x86_64

**Info about your OS**
Fedora Silverblue 36

**Additional context**
Being unable to use files installed on local path is an issue since a lot of applications are installed there. Thats a problem when using toolbox with editors or shells. Moreso on immutable distros where toolbox are usually used because its easier to install stuff locally

**Comment by Fowindev** [comment]
Happened to me too, but "toolbox run bash -i -c command" seems to work

**Comment by debarshiray** [comment]
Yes, you are right.  There's something odd going on.  Before going ahead and changing anything, I would like to understand exactly what Podman is doing.  See https://github.com/containers/podman/issues/16280

**Comment by debarshiray** [comment]
This should be fixed by https://github.com/containers/toolbox/pull/1148

Please feel free to re-open or leave a comment if you have reason to believe otherwise.

**Comment by debarshiray** [comment]
Thanks for your interest in Toolbx.  :)
