### ISSUE TITLE
Consider being able to create a local base image/container with common tools/packages

### ISSUE THREAD

**Issue by brunosxs** [containers/toolbox#1077]
**Is your feature request related to a problem? Please describe.**
Having to install the same set of tools on every toolbox I create seems wasteful. Everytime I create a toolbox I start from zero and have to reinstall basic tools like git, cpp/rust toolchains, etc...

**Describe the solution you'd like**
A way to create a base image or container in which we can base the new toolbx from.

Consider something like:
I want a base cpp enviroment. So I would do `toolbox create my-base-cpp-container && toolbox enter my-base-cpp-container`, and create the base container in the usual way, adding tools like git, gcc, valgrind, etc...
Later, I would start developing something for the godot engine, I'd want to use the base container as a sort of image (in docker terms) and just add specific dependencies to build godot on it.
`$ toolbx create godot-dev from my-base-cpp-container`

**Describe alternatives you've considered**
I for now am using a script that I run inside the newly created toolbx container.
**Additional context**
Docker multi-stage builds seems to be the closets analogy, which podman supports as well.

**Comment by HarryMichal** [comment]
Hi @brunosxs and thank you for opening the feature request!

Yes, Toolbx does not have any "image management" features but for that there is the whole OCI ecosystem. Every user of Toolbx has the freedom of writing their own Containerfile/Dockerfile and create their own images based on the default Toolbx images. For the time being, I'd recommend you that path to go in. It should even be possible to override the default used image in the configuration file.

**Comment by akdev1l** [comment]
You can do as you described, create the toolbox and customize it then do `podman commit` to create an image from that.

From then on you can create new toolboxes with the `-i` flag and passing your custom image

**Comment by brunosxs** [comment]
I think this must be clarified in the documentation then... 
An effort to make it better would be appreciated. Both the documentation on docs.fedora and the toolbox website are too vague.
I'll look at how I can improve that, I'd be willing to help... maybe just adding examples in the man page of toolbox would help first-timers like myself.

**Comment by akdev1l** [comment]
I'm having trouble sleeping so I'll put the steps here:

1. Create a toolbox - in this case I'm using a custom image as base
```
[akdev@canzuk ~]$ toolbox create -i docker.io/akdev1l/ubuntu-toolbox:22.04
Created container: ubuntu-toolbox-22.04
Enter with: toolbox enter ubuntu-toolbox-22.04
```
2. Enter the toolbox and do modifications 
```
[akdev@canzuk ~]$ toolbox enter ubuntu-toolbox-22.04
⬢[akdev@toolbox ~]$ sudo apt install -y neofetch
sudo: unable to resolve host toolbox: No address associated with hostname
```
3. commit the changes:

```
[akdev@canzuk ~]$ podman commit ubuntu-toolbox-22.04 my-custom-image
```
4. You can now create new custom toolboxes by doing: `toolbox create -i my-custom-image`

Example:
```
[akdev@canzuk ~]$ toolbox create -i my-custom-image
Created container: my-custom-image
Enter with: toolbox enter my-custom-image
[akdev@canzuk ~]$ toolbox enter my-custom-image
⬢[akdev@toolbox ~]$ neofetch
            .-/+oossssoo+/-.               akdev@toolbox
        `:+ssssssssssssssssss+:`           -------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.1 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: MS-7C37 1.0
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.18.16-200.fc36.x86_64
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 4 days, 2 hours, 46 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 498 (dpkg)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3840x2160
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: conmon
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: NVIDIA GeForce GTX 1060 3GB
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   GPU: NVIDIA GeForce RTX 3090
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Memory: 5455MiB / 64221MiB
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

Note how we didn't need to install `neofetch` as that was already part of the image.

**Comment by matthiasclasen** [comment]
Thanks for mentioning podman commit. That is useful to know, and that means this workflow already works. I guess we could consider adding a toolbox commit command to wrap that, so you don't have to use 'raw' podman commands for this workflow.

**Comment by matthiasclasen** [comment]
We've added a section about custom images to the website now

**Comment by QmwJlHuSg9pa** [comment]
For the next poor soul who finds this thread and finds themselves scratching their head:
1. As of December 2021, "Toolbox" [has been renamed](https://debarshiray.wordpress.com/2021/11/10/toolbox-is-now-toolbx/) to "Toolbx". As of writing, the command itself is still printed "toolbox" (and is referred to as such throughout this GitHub repo's README).
2. The aforementioned "**custom images**" section can currently be found within the [installation guide](https://containertoolbx.org/install/#custom-images) on the "Toolbx" website.

**Comment by debarshiray** [comment]
The website was revamped in February 2024, and there's a lot more documentation about _custom images_ at https://containertoolbx.org/doc/
