### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by paralin** [containers/toolbox#1088]
The last release was last year and some commits have been added since, can you tag a new release?

Thanks!

**Comment by heyakyra** [comment]
Ideally with an executable of the recommended go implementation, instead of [the deprecated one included now](https://github.com/containers/toolbox/pull/698#issuecomment-1230561306)

**Comment by debarshiray** [comment]
> The last release was last year and some commits have been added
> since, can you tag a new release?

`main` is currently not in a state to be released.  We will roll a release once it's ready.

Is there anything specific that you are interested in?

**Comment by debarshiray** [comment]
> Ideally with an executable of the recommended go implementation

This sounds like a misunderstanding.  Our upstream release tarballs won't ever have *an executable of the recommended go implementation*.

Programs written in Go need to be built (or compiled) into a architecture-specific machine readable executable.  So, we would have to provide binaries for all possible architectures, and even then, various distributors would want to build it with their own build flags.  You can either build Toolbx from the upstream release tarballs yourself, or use your distribution's binary packages for your machine's architecture.

Both the GitHub [project](https://github.com/containers/toolbox) and the [website](https://containertoolbx.org/) link to [instructions](https://containertoolbx.org/install/) for building Toolbx.

**Comment by heyakyra** [comment]
Fair enough, I'm just thinking for users of older (pre-22.04 LTS) Ubuntu releases which do not have this packaged in the official repos. 

I usually see github releases with executables for various architectures, but if it doesn't make sense to offer that here in favor of official distro packages, doesn't it at least make sense to completely remove the deprecated script to avoid the confusion in the first place?

**Comment by paralin** [comment]
I've been having some issues with the current tagged release, is the newer go version on the main branch far enough along in development to use in an experimental context? This is for https://github.com/SkiffOS/SkiffOS config apps/toolbx

**Comment by debarshiray** [comment]
> I've been having some issues with the current tagged release

I see.  Can you elaborate further?  Preferably with links to GitHub issues.

> is
> the newer go version on the main branch far enough along in
> development to use in an experimental context?

You can certainly use it in an experimental context.  It's just that the behaviour isn't quite what we want to call *supported*, so there might be some smaller changes before the release.

> This is for https://github.com/SkiffOS/SkiffOS config apps/toolbx

I see.  Very interesting.  :)

**Comment by debarshiray** [comment]
> doesn't it at least make sense to completely remove the deprecated
> script to avoid the confusion in the first place?

No.  I already [answered](https://github.com/containers/toolbox/pull/698) this.

**Comment by debarshiray** [comment]
Closing.

A new release will eventually happen once `main` is in a releasable state.  Keeping an issue open for it won't make it happen sooner.  :)

Having said that, I am still interested in knowing if there are pressing problems in the 0.0.99.3 release that's causing serious issues for people.

**Comment by debarshiray** [comment]
I suppose you have already noticed, but we do have a new release [now](https://github.com/containers/toolbox/pull/1241).
