### ISSUE TITLE
Move src/go.mod to root

### ISSUE THREAD

**Issue by paralin** [containers/toolbox#1089]
Currently working on a Buildroot package for this:

It's difficult to `go mod vendor` inside a sub-dir for us. Usually Go projects do not use a `src` subdir.

Would it be possible to move the `src/` contents to the root to make this project more canonical?

**Comment by paralin** [comment]
https://github.com/skiffos/containers-toolbox/commit/c0104586773c197a99592752a0e62a6ab902faad

To package this I've moved `src/` to `/`

... in that commit I also dropped `meson` but that is not necessary, just was convenient for packaging purposes in my case.

**Comment by debarshiray** [comment]
RHEL also uses `go mod vendor` and we handle it by creating a separate *vendored* tarball from the upstream tarball downstream.  Is that possible in your case?

Going forward, I want to release two sets of upstream tarballs.  One *vendored*, one not.  That should make things easier for everybody.

**Comment by debarshiray** [comment]
> Would it be possible to move the src/ contents to the root to make
> this project more canonical?

Umm... is it possible?  Yes.  However, I don't want to because I would like to keep the top-level directory somewhat clean.

I know that Go projects tend to have a very flat hierarchy with everything in the top-level directory.  I find that somewhat disorienting.

Secondly, and more importantly, I don't think of Toolbx as a Go project.  It uses Go as the primary programming language, but it's possible that it might use a different language for some auxiliary purposes.  Today it uses Bash for testing.  It's possible that it might start using some small C programs in the test suite to test different aspects of the Toolbx container's runtime.  That's why I don't want to everything to the Go way of doing things -- Go isn't the only thing involved.

**Comment by debarshiray** [comment]
Closing.

Thanks for working on the Buildroot package!

**Comment by paralin** [comment]
The problem is that your project is the /only/ one that doesn't have go.mod in the root. I can understand that choice as a matter of personal preference (as in your case) if it were common practice. But since you're the **only one** breaking the pattern, it makes it **very difficult** for us downstream to add your project.

**Comment by debarshiray** [comment]
Umm... I don't understand.

Isn't it possible to build Toolbx just as any other code-base that uses Meson, instead of assuming Go?  Or in the other words, how would you deal with a hybrid code-base that consists of languages other than Go?

**Comment by paralin** [comment]
The binary that is produced for toolbox is Go. So, we would use the Go package infrastructure which sets all the environment variables for cross compilation and uses the buildroot host-go toolchain.

**Comment by paralin** [comment]
@debarshiray Here's some links for reference:

 - Go package infra: https://github.com/buildroot/buildroot/blob/master/package/pkg-golang.mk#L119
 - Example of a Go package: https://github.com/buildroot/buildroot/blob/master/package/runc/runc.mk#L27

**Comment by HarryMichal** [comment]
> The binary that is produced for toolbox is Go. So, we would use the Go package infrastructure which sets all the environment variables for cross compilation and uses the buildroot host-go toolchain.

Keep in mind that Toolbx requires a bit of a special treatment to work correctly. We expect a profile shell script to be in place, inject a special runpath, create crucial symlinks under /run/host, etc. All this work is done by our build system that you completely discarded in https://github.com/skiffos/containers-toolbox/commit/c0104586773c197a99592752a0e62a6ab902faad.

**Comment by paralin** [comment]
@HarryMichal if so then the buildroot package should be updated to accomodate that. The package I committed to SkiffOS is a prototype at best. It obviously needs more improvement, especially before I submit it upstream to buildroot proper.

**Comment by paralin** [comment]
... regardless I don't see what the downside of structuring the project in a more normal way without src/ - there are no compelling arguments as to why (pros), and numerous as to why not / how that makes things more difficult (cons).
