### ISSUE TITLE
Add the Containerfile for Fedora 38

### ISSUE THREAD

**Issue by debarshiray** [containers/toolbox#1111]
Fedora [Rawhide](https://docs.fedoraproject.org/en-US/releases/rawhide/) now points to Fedora 38 because Fedora 37 has been branched from it.  So, we should update our image definitions by adding one for Fedora 38.

While doing so, it will be good to check that everything is synchronized with the files in Fedora's [dist-git](https://src.fedoraproject.org/container/fedora-toolbox)

**Comment by nievesmontero** [comment]
The directory has been created but is pending to be tested.

**Comment by nievesmontero** [comment]
The f38 image has been tested and apparently works.
