### ISSUE TITLE
Add a way to pass --cap-add=sys_admin to the "podman create" call

### ISSUE THREAD

**Issue by livingsilver94** [containers/toolbox#1126]
**Is your feature request related to a problem? Please describe.**
I want to isolate the development environment of a distro. I'm a packager, I'd use the distro tools to build packages for it.
The package builder creates temporary containers using `mount()` and other tricks I didn't study deeper. One of these `mount()`
 calls is `mount("none", "/a/temporary/path/sys", "sysfs", 0, NULL)`, which will fail with `EPERM`.

**Describe the solution you'd like**
Add a way to pass --cap-add=sys_admin to the "podman create" call so that `mount()` is successful.

**Comment by akdev1l** [comment]
There are a lot of "add way of passing $specific_flag to underlying podman".

Perhaps it would be good to just add a way of doing that generically instead of trying to address each concern separately.

```
toolbox --podman-args=--cap-add=SYS_ADMIN create
```

Perhaps it would be better off as a configuration file

**Comment by livingsilver94** [comment]
This is surely handy but potentially it could interfere with toolbx, as I imagine some flags work against the way toolbox works.

**Comment by debarshiray** [comment]
I suppose this is specifically about mounting a sysfs instance inside a rootless Toolbx?  `mount(8)` does work for a few other cases.  For example, it's possible to do bind mounts inside the container's mount namespace.

Out of curiosity, which distribution are you working on?  Maybe we can make the tools Toolbx-aware and figure out a different way of doing things.  A few years ago, @owtaylor adjusted [mock](https://github.com/rpm-software-management/mock/pull/337) to work inside Toolbx.  Also, not that this works inside a rootless Toolbx:
```
$ sudo mount --rbind /sys /tmp/sysfs
```

**Comment by livingsilver94** [comment]
Heh, after your message my issue appears like an X/Y problem actually.

> `sudo mount --rbind /sys /tmp/sysfs`

Oh interesting! But the tooling uses `mount(3)`, I don't think the syscall provides such option.

> Out of curiosity, which distribution are you working on?

It's SerpentOS,  not yet released. I will dive deeper into the SerpentOS code to figure out something.

**Comment by debarshiray** [comment]
> Heh, after your message my issue appears like an X/Y problem actually.

What do you mean by *an X/Y problem*? :)

> > `sudo mount --rbind /sys /tmp/sysfs`
> 
> Oh interesting! But the tooling uses `mount(3)`, I don't think the syscall provides such option.

I think you meant `mount(2)`.  :)

The `mount(2)` system call definitely lets you do bind mounts.  Look for the `MS_BIND` flag.  There's also `MS_REC` to make it recursive.  However, yes, implementing it with the system call will take a bit more effort than invoking the `mount(8)` command.

> > Out of curiosity, which distribution are you working on?
> 
> It's SerpentOS, not yet released. I will dive deeper into the SerpentOS code to figure out something.

I see.  Interesting.

**Comment by akdev1l** [comment]
> This is surely handy but potentially it could interfere with toolbx, as I imagine some flags work against the way toolbox works.

we could mark it as unsupported and leave it out of the man page - it is definitely an advanced use case so let there be dragons imo. 

After the community comes up with consistent patterns of usage we could standardize those via specific flags which will be documented and supported.

**Comment by debarshiray** [comment]
> > This is surely handy but potentially it could interfere with toolbx,
> > as I imagine some flags work against the way toolbox works.
> 
> we could mark it as unsupported and leave it out of the man page
> - it is definitely an advanced use case so let there be dragons imo.

Once it's in the Toolbx code, people will automatically assume some level of support.  :)

On top of that, we will always have to be careful about not mentioned it in the manuals or in the shell completions, which is easier said than done.

> After the community comes up with consistent patterns of usage
> we could standardize those via specific flags which will be documented
> and supported.

Even better, folks can experiment directly with Podman.  Toolbx's Podman invocations can found in the `toolbox --verbose ...` logs and `podman inspect --type container ...`, and if someone is truly advanced, then will need access to all the bells and whistles that Podman has.

Once people have converged upon accepted ways of doing interesting things, then we can figure out a way to offer them through Toolbx for convenience.

**Comment by debarshiray** [comment]
> > Heh, after your message my issue appears like an X/Y problem actually.
> 
> What do you mean by _an X/Y problem_? :)

Found: https://en.wikipedia.org/wiki/XY_problem

**Comment by debarshiray** [comment]
I am tentatively closing this for the time being.  If you need help adjusting the SerpentOS tools to work within a Toolbx, then feel free to reach out.

Thanks for stopping by!
