### ISSUE TITLE
Incorrect Link to Latest Release

### ISSUE THREAD

**Issue by glasko-dp** [containers/toolbox#1127]
Running Debian - downloaded what was apparently the latest release from https://github.com/containers/toolbox/releases/tag/0.0.99.3
When I run `toolbox -v`, I get the message:
```
THIS IMPLEMENTATION OF TOOLBOX IS NO LONGER MAINTAINED.
Please, use the Go implementation instead.
```

**Comment by HarryMichal** [comment]
Hi @glasko-dp, thanks for filling the issue. Next time, please, try to make use of the new issue templates. It helps us to understand your situation better right away without having to ask more questions.

How did you install Toolbx on your machine? Was it via a Debian package or did you clone the sources yourself? In any case, what you are running is the "old Toolbx" that was just a Shell script. It is left in the repository only for historical purposes. The current implementation is written in Go and requires to be compiled first. Check out the [instructions](https://containertoolbx.org/install/) for how to build Toolbx from source.
