### ISSUE TITLE
Toolbox uses host's version of Golang instead of version in toolbox

### ISSUE THREAD

**Issue by barnscott** [containers/toolbox#1132]
**Describe the bug**
`go version` in the container image of the Toolbox env reports version `1.18.6`, though the container image (Fedora 37) only includes version `1.19.1`. It appears that Go is getting redirected to another version of Go, possibly on theHost, while i need a newer version of Go.

**My Experience**
On Silverblue 36 with the default Toolbox image, Fedora 36, I tried used to Go 1.19.1 [instructions](https://go.dev/doc/install) to override Go with the newest version. However, while I can use it when I call Go binary path directly, the system continues to default to using the previous version (1.18.6) even after overriding system env vars,  go-env vars, and PATH.

Next, I decided to switch to the Fedora 37 beta container image. Using Toolbox, grabbed the 37 release. Within Fedora 37 container I see that it has Go `1.19.1` installed by default. However, when I run `go` command, it is still reporting `1.18.6`. Since I can not locate where `1.18.6` is installed, I assume it is somehow redirecting to Go which is installed on the host (not sure).

On the Fedora 37 image, even though dnf installed `golang 1.19.1`, `dnf info` reports `1.18.6`
![image](https://user-images.githubusercontent.com/48160387/193474328-81ff08b4-7be8-4b87-9ca9-92cfb2064750.png)
![image](https://user-images.githubusercontent.com/48160387/193474271-41b23f1e-5bf6-4b14-9166-f66e3dcd0fd9.png)

In the screenshot below, you will see im using Fedora 37 container image via Toolbox. The container is set to the default path for golang, which is where `1.19.1` is located. However, calling golang in the normal mannor reports a different version of golang.
![image](https://user-images.githubusercontent.com/48160387/193473164-ec43c110-cba8-419d-9e68-5f76db9fb0ab.png)

Is my assessment accurate that toolbox redirects to the Go binary on the host? If not, any suggestions on what I should do to address my problem? And how can I use Golang 1.19.1 within Toolbox while my host if Fedora 36.

**Steps how to reproduce the behaviour**
1. Run `go version`
2. Observe it is using `1.18.6` which is not the version present in Fedora 37

**Expected behaviour**
Using Golang in Toolbox should use the version of Golang within the container image of Toolbox env.

**Actual behaviour**
I see my Fedora 37 container image in the Toolbox env is using 1.18.6 instead of 1.19.1 (the version in the Fedora 37 image).

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.3

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.3-6.fc36.x86_64

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 14:58:19 2022
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-4.2.1-2.fc36.x86_64

**Info about your OS**
Fedora Silverblue 36

**Comment by barnscott** [comment]
Just realized that Silverblue doesn't have Golang installed (on the host). And then quickly found some alias' that I configured a long time ago and forgot. So.. yup.

**Comment by debarshiray** [comment]
> Just realized that Silverblue doesn't have Golang installed (on the host). And then quickly found some alias' that I configured a long time ago and forgot. So.. yup.

Happens to the best of us.  :)

Thanks for stopping by.
