### ISSUE TITLE
Comment says that this implementation is no longer maintained

### ISSUE THREAD

**Issue by danielhoherd** [containers/toolbox#1178]
https://github.com/containers/toolbox/blob/main/toolbox#L18 says that this is no longer maintained. Should we be using something else, or is the comment wrong?

**Comment by debarshiray** [comment]
> Should we be using something else,

Yes.

> or is the comment wrong?

No.

**Comment by danielhoherd** [comment]
If it's non longer maintained, shouldn't the repo make that more obvious instead of burying that crucial piece of information in a code comment? Last week a co-worker was suggesting that we use this, and I just happened to stumble onto that comment about this being not maintained anymore.
