### ISSUE TITLE
RFE: Disable Travis CI on this repo

### ISSUE THREAD

**Issue by cevich** [containers/toolbox#1230]
**Is your feature request related to a problem? Please describe.**
It doesn't appear Travis-CI is in use on this repo, yet it's explicitly enabled for this repo.

**Describe the solution you'd like**
I'd like to disable Travis-CI to reduce the overall number of containers-org. enabled apps, thereby reducing the maintenance burden.

**Describe alternatives you've considered**
Leave Travis-CI enabled

**Additional context**
Travis-CI has issued multiple security bulletins over the past years.

**Comment by debarshiray** [comment]
Yes, we can certainly disable Travis for `containers/toolbox`.

It's been [more than 3 years](https://github.com/containers/toolbox/commit/c86a715d3cf2b8225e43083abbf7b31c9f104ecc) since we last used Travis.

**Comment by cevich** [comment]
Will do, thanks!
