### ISSUE TITLE
Unable to build toolbox 0.0.99.4 on Kubuntu 20.04

### ISSUE THREAD

**Issue by antonc42** [containers/toolbox#1247]
**Describe the bug**
Unable to build toolbox 0.0.99.4 on Kubuntu 20.04

**Steps how to reproduce the behaviour**
1. Install dependencies listed here: https://containertoolbx.org/install/
```
gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```
```
apt list golang
golang/focal,now 2:1.13~1ubuntu2 amd64 [installed]
```
```
apt list go-md2man
go-md2man/focal,now 1.0.10+ds-1 amd64 [installed]
```
```
venv/bin/meson --version
1.0.1
```
```
apt list ninja-build
ninja-build/focal,now 1.10.0-1build1 amd64 [installed]
```
```
apt list systemd
systemd/focal-updates,now 245.4-4ubuntu3.19 amd64 [installed]
```
```
apt list bash-completion
bash-completion/focal,now 1:2.10-1ubuntu1 all [installed]
```
3. Download `toolbox-0.0.99.4.tar.xz` from Github releases page.
4. Extract into new directory. ```tar xvf toolbox-0.0.99.4.tar.xz```
5. Enter extracted directory. ```cd toolbox-0.0.99.4/```
6. Create a Python virtual environment. ```python3.11 -m venv venv```
7. Activate the virtual environment. ```. venv/bin/activate```
8. Update basic modules. ```python3 -m pip install --upgrade pip setuptools wheel```
9. Install meson. ```python3 -m pip install meson```
10. Run meson setup. ```meson setup -Dprofile_dir=/etc/profile.d builddir```
11. Error
```
The Meson build system
Version: 1.0.1
Source dir: /home/user/Downloads/toolbox-temp/toolbox-0.0.99.4
Build dir: /home/user/Downloads/toolbox-temp/toolbox-0.0.99.4/builddir
Build type: native build
Project name: toolbox
Project version: 0.0.99.4
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -print-file-name=libc.so: YES 

meson.build:17:0: ERROR: C header 'shadow/subid.h' not found

A full log can be found at /home/user/Downloads/toolbox-temp/toolbox-0.0.99.4/builddir/meson-logs/meson-log.txt
```

**Expected behaviour**
Able to build and install Toolbox 0.0.99.4 on Kubuntu 20.04

**Actual behaviour**
Unable to build. Appears to be a missing header file.

**Output of `toolbox --version` (v0.0.90+)**
Currently have toolbox 0.0.99.3 installed and working.
```
toolbox --version
toolbox version 0.0.99.3
```

**Output of `podman version`**
e.g.,
```
podman version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.6
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
```
apt list podman
podman/now 100:3.4.2-1 amd64 [installed,local]
```

**Info about your OS**
Kubuntu 20.04
Updated 2023-02-27

**Additional context**
Unable to find a package that provides the header file:
```
sudo apt-file update
sudo apt-file find subid.h
```

It appears that on Ubuntu, the package that would provide this is `libsubid-dev`, which appears to only be available in 22.10 or later according to this: https://packages.ubuntu.com/search?searchon=sourcenames&keywords=shadow

Unless I'm incorrect, that would mean that Toolbox can no longer be installed on Ubuntu LTS versions without compiling [shadow utils](https://github.com/shadow-maint/shadow) from source. I'm not sure replacing core system components with source-built ones is a good idea. Any ideas on how to proceed?

**Comment by debarshiray** [comment]
> Unless I'm incorrect, that would mean that Toolbox can no
> longer be installed on Ubuntu LTS versions without
> compiling [shadow utils](https://github.com/shadow-maint/shadow)
> from source.

You can't install the latest Toolbx 0.0.99.4 release without either updating [Shadow](https://github.com/shadow-maint/shadow) to 4.9 or reverting commit [ca8007c192b3bb77](https://github.com/containers/toolbox/commit/ca8007c192b3bb77911f5466827252f5b714811b) downstream.  Barring that, you can still use older versions of Toolbx.

I wonder if the Toolbx [package](https://launchpad.net/ubuntu/jammy/+package/podman-toolbox) in Ubuntu 22.04 can be updated to at least 0.0.99.3.  It seems to be stuck at 0.0.99.2 at the moment.

> I'm not sure replacing core system components with
> source-built ones is a good idea. Any ideas on how to proceed?

At the end of the day, Toolbx is meant to be part of the operating system.  Note how it's part of the Fedora CoreOS and Silverblue images.  For RHEL we backported the relevant parts of Shadow to get everything to work together.

**Comment by debarshiray** [comment]
Closing, because I don't think we can do something upstream.

**Comment by Jmennius** [comment]
> > Unless I'm incorrect, that would mean that Toolbox can no
> > longer be installed on Ubuntu LTS versions without
> > compiling [shadow utils](https://github.com/shadow-maint/shadow)
> > from source.
> 
> You can't install the latest Toolbx 0.0.99.4 release without either updating [Shadow](https://github.com/shadow-maint/shadow) to 4.9 or reverting commit [ca8007c192b3bb77](https://github.com/containers/toolbox/commit/ca8007c192b3bb77911f5466827252f5b714811b) downstream. Barring that, you can still use older versions of Toolbx.
> 
> I wonder if the Toolbx [package](https://launchpad.net/ubuntu/jammy/+package/podman-toolbox) in Ubuntu 22.04 can be updated to at least 0.0.99.3. It seems to be stuck at 0.0.99.2 at the moment.
> 
> > I'm not sure replacing core system components with
> > source-built ones is a good idea. Any ideas on how to proceed?
> 
> At the end of the day, Toolbx is meant to be part of the operating system. Note how it's part of the Fedora CoreOS and Silverblue images. For RHEL we backported the relevant parts of Shadow to get everything to work together.

I agree with this assessment.
Because of the Debian package maintenance policy (which Ubuntu inherits) it is often cumbersome to build the newest source.
The expected solution in this case is to patch the project (i.e. revert that commit) or to just build an older version of the project (how it would actually be like if the package was part of the release).

**Comment by ernstki** [comment]
On Ubuntu 22.04, at least, it's possible to build Toolbx and shadow-utils from source. You will still need to be able to perform the installations as root, since some config files need to go in `/etc` and `/usr/lib`, and most of the [shadow-utils](https://github.com/shadow-maint/shadow) binaries need to be owned by root and setuid.

I feel vaguely uneasy about building and installing from the latest `master` of a repository that's going to replace my `su`,  and `passwd`, among other things. I'm not recommending this to anyone, seriously, just documenting for myself, and in case it helps out some other adventurous soul who was nearly to the goal and just needed a nudge.

In actuality, I used [Environment Modules](https://modules.sf.net) to segregate Toolbx and shadow-utils from other things I had installed in `/usr/local`, but that's beyond the scope here so I don't go into it.

```bash
cd ~/place/where/you/store/code
git clone --depth=1 https://github.com/containers/toolbox.git
git clone --depth=1 https://github.com/shadow-maint/shadow.git

# dependencies for shadow
sudo apt install libbsd-dev libsemanage-dev itstool
# entirely optional dependencies for shadow
#sudo apt install bats shellcheck codespell skopeo

cd shadow
./autogen.sh --prefix=/usr/local
make -j8 && sudo make install

# toolbox assumes a Fedora / Red Hat filesystem layout, I guess…
pushd /usr/share
sudo ln -s ../../etc/profile.d
popd

# toolbox requires `go` somewhere in your $PATH
sudo apt install golang-1.23
# there is a better, permanent solution, but such as this will suffice
export PATH=$PATH:/usr/lib/go-1.23/bin

cd ../toolbox
meson build --prefix=/usr/local  # to be explicit
cd build

# not sure why this should be necessary, as /usr/local/lib is already in the
# linker search path on a typical system, but it was for me, otherwise I'd get
# the `Missing subgid and/or subuid ranges for user` error mentioned in #1658
export CGO_LDFLAGS=-Wl,-rpath=/usr/local/lib
ninja

# this bit will ask for elevated privileges regardless, to install
# to /usr/share/profile.d and /usr/lib/tmpfiles.d
ninja install
```

You can test to make sure the LDFLAGS took effect with

```console
$ objdump -x src/toolbox | grep RUNPATH
  RUNPATH              /usr/local/lib:/run/host/usr/lib/x86_64-linux-gnu
```

and the command

```bash
strace -ef status=failed toolbox list
```

can be useful for general troubleshooting. That's how I figured out that `toolbox` wasn't finding `libsubid.so.5.0.0` and that the `-Wl,-rpath` linker flag was needed.
