### ISSUE TITLE
enter fresh toolbox giving "Error: no space left on device"

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#1329]
**Describe the bug**
Recently I am not able to enter new toolbox containers.

**Steps how to reproduce the behaviour**
1. `toolbox create fedora-test-toolbox`
2. `toolbox enter fedora-test-toolbox`
3. `podman start -a fedora-test-toolbox`

**Expected behaviour**
Toolbox to setup normally

**Actual behaviour**
For me on Fedora Silverblue 38:

2. fails with `Error: failed to initialize container fedora-test-toolbox`

4. ends with:
```
level=debug msg="Setting up watches for file system events"
Error: no space left on device
```
for all new toolboxes apparently. See full output below.

**Output of `toolbox --version`**
toolbox version 0.0.99.4

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.4-1.fc38

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Sat May 27 01:58:48 2023
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-4.5.1-1.fc38.x86_64

**other package info**
conmon-2.1.7-2.fc38
containers-common-1-89.fc38
crun-1.8.5-1.fc38

**Info about your OS**
Fedora Silverblue 38 (38.20230619.0)

**Additional context**
When did the issue start occurring?   Not sure exactly (haven't tried creating in a while)

If you see an error message saying: `Error: invalid entry point PID of container <name-of-container>`, add to the ticket output of command `podman start --attach <name-of-container>`.

```
$ podman start -a fedora-test-toolbox 
level=debug msg="Running as real user ID 0"
level=debug msg="Resolved absolute path to the executable as /usr/bin/toolbox"
level=debug msg="TOOLBOX_PATH is /usr/bin/toolbox"
level=debug msg="Migrating to newer Podman"
level=debug msg="Setting up configuration"
level=debug msg="Setting up configuration: file /etc/containers/toolbox.conf not found"
level=debug msg="Setting up configuration: file /root/.config/containers/toolbox.conf not found"
level=debug msg="Resolving container and image names"
level=debug msg="Container: ''"
level=debug msg="Distribution (CLI): ''"
level=debug msg="Image (CLI): ''"
level=debug msg="Release (CLI): ''"
level=debug msg="Resolved container and image names"
level=debug msg="Container: 'fedora-toolbox-38'"
level=debug msg="Image: 'fedora-toolbox:38'"
level=debug msg="Release: '38'"
level=debug msg="Creating /run/.toolboxenv"
level=debug msg="Monitoring host"
level=debug msg="Path /run/host/etc exists"
level=debug msg="Resolved /etc/localtime to /run/host/usr/share/zoneinfo/Asia/Singapore"
level=debug msg="Creating regular file /etc/machine-id"
level=debug msg="Binding /etc/machine-id to /run/host/etc/machine-id"
level=debug msg="Creating directory /run/libvirt"
level=debug msg="Binding /run/libvirt to /run/host/run/libvirt"
level=debug msg="Creating directory /run/systemd/journal"
level=debug msg="Binding /run/systemd/journal to /run/host/run/systemd/journal"
level=debug msg="Creating directory /run/systemd/resolve"
level=debug msg="Binding /run/systemd/resolve to /run/host/run/systemd/resolve"
level=debug msg="Creating directory /run/systemd/sessions"
level=debug msg="Binding /run/systemd/sessions to /run/host/run/systemd/sessions"
level=debug msg="Creating directory /run/systemd/system"
level=debug msg="Binding /run/systemd/system to /run/host/run/systemd/system"
level=debug msg="Creating directory /run/systemd/users"
level=debug msg="Binding /run/systemd/users to /run/host/run/systemd/users"
level=debug msg="Creating directory /run/udev/data"
level=debug msg="Binding /run/udev/data to /run/host/run/udev/data"
level=debug msg="Creating directory /run/udev/tags"
level=debug msg="Binding /run/udev/tags to /run/host/run/udev/tags"
level=debug msg="Creating directory /tmp"
level=debug msg="Binding /tmp to /run/host/tmp"
level=debug msg="Creating directory /var/lib/flatpak"
level=debug msg="Binding /var/lib/flatpak to /run/host/var/lib/flatpak"
level=debug msg="Creating directory /var/lib/libvirt"
level=debug msg="Binding /var/lib/libvirt to /run/host/var/lib/libvirt"
level=debug msg="Creating directory /var/lib/systemd/coredump"
level=debug msg="Binding /var/lib/systemd/coredump to /run/host/var/lib/systemd/coredump"
level=debug msg="Creating directory /var/log/journal"
level=debug msg="Binding /var/log/journal to /run/host/var/log/journal"
level=debug msg="Creating directory /var/mnt"
level=debug msg="Binding /var/mnt to /run/host/var/mnt"
level=debug msg="Creating directory /sys/fs/selinux"
level=debug msg="Binding /sys/fs/selinux to /usr/share/empty"
level=debug msg="Preparing to redirect /home to /var/home"
level=debug msg="/var/home isn't a symbolic link"
level=debug msg="Redirecting /home to /var/home"
level=debug msg="Looking up group for sudo"
level=debug msg="Group for sudo is wheel"
level=debug msg="Modifying user petersen with UID 1000:"
level=debug msg=usermod
level=debug msg=--append
level=debug msg=--groups
level=debug msg=wheel
level=debug msg=--home
level=debug msg=/var/home/petersen
level=debug msg=--shell
level=debug msg=/bin/bash
level=debug msg=--uid
level=debug msg=1000
level=debug msg=petersen
level=debug msg="Removing password for user petersen"
level=debug msg="Removing password for user root"
level=debug msg="Configuring RPM to ignore bind mounts"
level=debug msg="Setting up daily ticker"
level=debug msg="Setting up watches for file system events"
Error: no space left on device
```

**Comment by debarshiray** [comment]
This is odd.  :/

Are you using Btrfs on your host?  I am on Ext4.

What if you mount the container's root filesystem and poke around?
```
$ podman unshare
# podman mount fedora-toolbox-38
/home/rishi/.local/share/containers/storage/overlay/032eb001352a177c.../merged
# cd /home/rishi/.local/share/containers/storage/overlay/032eb001352a177c.../merged
# df -h .
...
```

The corresponding Toolbx code is in `initContainer()` in [src/cmd/initContainer.go](https://github.com/containers/toolbox/blob/main/src/cmd/initContainer.go).  A working container is supposed to have these log mesages:
```
...
...
level=debug msg="Setting up daily ticker"
level=debug msg="Setting up watches for file system events"
level=debug msg="Finished initializing container"
level=debug msg="Listening to file system and ticker events"
```

As far as I can make out, it could be these [fsnotify](https://pkg.go.dev/github.com/fsnotify/fsnotify) calls: `fsnotify.NewWatcher` and `watcherForHost.Add`.  Could you throw in a `fmt.Errorf` in your local `toolbox(1)` build and try again?  Something like:
```
-               return err
+              return fmt.Errorf("fsnotify.NewWatcher(): %w", err)
```

**Comment by juhp** [comment]
Thanks - sorry missed your comment

> Are you using Btrfs on your host? I am on Ext4.

Yes I am

> What if you mount the container's root filesystem and poke around?
> ```
> $ podman unshare
> # podman mount fedora-toolbox-38
> /home/rishi/.local/share/containers/storage/overlay/032eb001352a177c.../merged
> # cd /home/rishi/.local/share/containers/storage/overlay/032eb001352a177c.../merged
> # df -h .
> ...
> ```

Aha that gives me:
```
Filesystem                                             Size  Used Avail Use% Mounted on
/dev/mapper/luks-2936970d-43b9-4024-85ce-ac4470386343  476G  357G  113G  76% /var/home
```

> The corresponding Toolbx code is in `initContainer()` in [src/cmd/initContainer.go](https://github.com/containers/toolbox/blob/main/src/cmd/initContainer.go). A working container is supposed to have these log mesages:
> 
> ```
> ...
> level=debug msg="Setting up daily ticker"
> level=debug msg="Setting up watches for file system events"
> level=debug msg="Finished initializing container"
> level=debug msg="Listening to file system and ticker events"
> ```
> 
> As far as I can make out, it could be these [fsnotify](https://pkg.go.dev/github.com/fsnotify/fsnotify) calls: `fsnotify.NewWatcher` and `watcherForHost.Add`. Could you throw in a `fmt.Errorf` in your local `toolbox(1)` build and try again? Something like:
> 
> ```
> -               return err
> +              return fmt.Errorf("fsnotify.NewWatcher(): %w", err)
> ```

I tried that:
```
$ ~/fedora/rpms/toolbox/BUILD/toolbox-0.0.99.4/redhat-linux-build/src/toolbox enter fedora-toolbox-38
```
but no dice - same output. Perhaps it crashes before returning??  Or do I need to use the new toolbox inside too?

**Comment by juhp** [comment]
(Also happening for me today btw: I am unable to create a fresh 38 toolbox on SB 39)

**Comment by debarshiray** [comment]
> (Also happening for me today btw: I am unable to create a
> fresh 38 toolbox on SB 39)

Is that throwing the same `no space left on device` ?

**Comment by debarshiray** [comment]
I think that you are hitting the maximum limit on the number of `inotify(7)` instances or watches (they are different things) that can be created by a user.  You can check these limits with:
```ShellSession
$ cat /proc/sys/fs/inotify/max_user_instances
128
$ cat /proc/sys/fs/inotify/max_user_watches 
249158
```

Are you able to reproduce this predictably?  Or does it happen once in a while?

I suspect that there's something on your machine that's using `inotify(7)` a lot, or possibly leaking the descriptors for the instances or watches.  The error message from [fsnotify](https://pkg.go.dev/github.com/fsnotify/fsnotify) is misleading, but I think this is what's happening.

**Comment by debarshiray** [comment]
I think you are specifically running out of `inotify(7)` watches, not instances, here.

To reproduce, you can use a program like this:
```Go
// # dnf install golang-github-fsnotify-devel golang-x-sys-devel
// $ GO111MODULE=off GOPATH=/usr/share/gocode go run fsnotify.go

package main

import (
	"errors"
	"fmt"
	"github.com/fsnotify/fsnotify"
	"golang.org/x/sys/unix"
)

func main() {
	var shownAddError bool
	var shownNewWatcherError bool
	var watchers []*fsnotify.Watcher

	for {
		watcher, err := fsnotify.NewWatcher()
		if err != nil {
			if shownNewWatcherError {
				continue
			}

			var errErrno unix.Errno

			if errors.As(err, &errErrno) {
				if errors.Is(err, unix.EMFILE) {
					fmt.Printf("NewWatcher: unix.Errno: unix.EMFILE: %T, %s\n", err, err)
				} else {
					fmt.Printf("NewWatcher: unix.Errno: %T, %s\n", err, err)
				}
			} else {
				fmt.Printf("NewWatcher: %T, %s\n", err, err)
			}

			shownNewWatcherError = true
			continue
		}

		watchers = append(watchers, watcher)

		if err := watcher.Add("/etc"); err != nil {
			if shownAddError {
				continue
			}

			var errErrno unix.Errno

			if errors.As(err, &errErrno) {
				if errors.Is(err, unix.ENOSPC) {
					fmt.Printf("Add: unix.Errno: unix.ENOSPC: %T, %s\n", err, err)
				} else {
					fmt.Printf("Add: unix.Errno: %T, %s\n", err, err)
				}
			} else {
				fmt.Printf("Add: %T, %s\n", err, err)
			}

			shownAddError = true
		}
	}
}
```

Then, you can alter the limits to relatively lower values, to avoid triggering unrelated breakage from the operating system.  I recommend limiting the instances to a higher value than the watches, so that you can see both errors.  Normally, it's the other way round.

For example:
```ShellSession
# echo 128 >/proc/sys/fs/inotify/max_user_instances
# echo 64 >/proc/sys/fs/inotify/max_user_watches
```

This will lead to:
```ShellSession
$ GO111MODULE=off GOPATH=/usr/share/gocode go run fsnotify.go
Add: unix.Errno: unix.ENOSPC: syscall.Errno, no space left on device
NewWatcher: unix.Errno: unix.EMFILE: syscall.Errno, too many open files
```

**Comment by debarshiray** [comment]
Attempted workaround in https://github.com/containers/toolbox/pull/1422

**Comment by juhp** [comment]
I wanted to test this (and even did a local build) but I now realized I can't currently reproduced locally or in my VMs, which strange/weird/happy thing I suppose.  So either it got also fixed somehow or the problem is currently hidden for me anyway.

**Comment by debarshiray** [comment]
> I wanted to test this (and even did a local build) but I now realized I can't currently reproduced locally or in my VMs, which is strange/weird/happy thing I suppose. So either it got also fixed somehow or the problem is currently hidden for me anyway.
> 
> (I did experience it for quite a while, some months even I think, but had worked around it locally with distrobox... if I see it again I can try testing or maybe your fix will reach me first)

I suppose there was something on your host OS (some D-Bus daemon, perhaps) that was leaking `inotify(7)` watches for a while.  It either got fixed or it's not getting triggered anymore.
