### ISSUE TITLE
Feature: the first `toolbox enter` assumes `toolbox create` beforehand

### ISSUE THREAD

**Issue by osalbahr** [containers/toolbox#1335]
**Is your feature request related to a problem? Please describe.**

I ran `toolbox enter` to enter my first toolbox and got the following:
```console
$ toolbox enter
Error: container fedora-toolbox-38 not found
Use the '--container' option to select a toolbox.
Run 'toolbox --help' for usage.
```

**Describe the solution you'd like**

I'd like it to functionally be equivalent to `toolbox create && toolbox enter`.

**Describe alternatives you've considered**

Running `toolbox create && toolbox enter`.

**Additional context**

This behavior would be consistent with `distrobox enter`.

**Comment by kth8** [comment]
I'm using toolbox version 0.0.99.4 on Fedora Silverblue 38 and this is already the default behavior.
```
[owner@fedora ~]$ toolbox rmi --all --force
[owner@fedora ~]$ toolbox enter 
No toolbox containers found. Create now? [y/N] y
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:38 (500MB)? [y/N]: y
⬢[owner@toolbox ~]$
```

**Comment by osalbahr** [comment]
@kth8 thx!
