### ISSUE TITLE
Using toolbox can destroy months or years of bash history

### ISSUE THREAD

**Issue by AdamWill** [containers/toolbox#1359]
**Describe the bug**
I use a [profile.d snippet](https://www.happyassassin.net/posts/2015/01/16/bash-history-with-multiple-sessions/) based on [one from bkuhn](https://lists.gnu.org/archive/html/bug-bash/2011-06/msg00040.html) to keep a very long and constantly updated bash history. It's surprisingly valuable to me (I say "surprisingly" because I didn't realize how valuable it was till this bug happened and I found myself swearing constantly about all the commands I've lost from my history...)

It seems that when you use a toolbox container, it shares your user's history file from your home directory, but does *not* source any configuration of the history environment variables you do in `/etc/profile.d`. So...inside the toolbox container, the `HISTSIZE` and `HISTFILESIZE` values are the defaults, and when you enter the container, it truncates your massive history to a...very short one.

**Steps how to reproduce the behaviour**
1. Set up a host system (I hit the bug using Fedora 38 and Fedora 39, and carefully reproduced it in an F38 VM for this bug report) to have large `HISTSIZE` and `HISTFILESIZE` configured via `/etc/profile.d` (I suspect the bug won't happen if you do this in `~/.bash_profile` or `~/.bashrc`, as the container probably gets those), and a history of more than 1000 entries (I copied my `profile.d` snippet and current history file into a VM)
2. Before entering the container, check the size of the history file and how many items you see when you run `history`
3. Run `toolbox enter`
4. Check the history file size within and outside the container: it will now be much smaller. Note that `HISTSIZE` and `HISTFILESIZE` are both 1000 inside the container and running `history` in the container shows 1000 items, plus however many commands you've run in the container
5. Exit the container. Run `history` from outside the container and see you now have only ~1000 entries in it

**Expected behaviour**
The container should not eat thousands of entries and years of accumulated knowledge from my history file.

**Actual behaviour**
It did.

**Screenshots**

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.4`

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.99.4-3.fc39.x86_64

**Output of `podman version`**
```
Client:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.21rc3
Built:        Mon Jul 24 05:44:03 2023
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-4.6.0-3.fc39.x86_64`

**Info about your OS**
Fedora Workstation 39. Also reproduced in a Fedora 38 VM.

**Comment by AdamWill** [comment]
I can see that this might be tricky to fix, though. Perhaps, for safety, the container should not use the same history file as the host system, but just copy it on container creation, or something?

**Comment by juhp** [comment]
Would it not be better to have the HISTORY config in your user bash config?
That would be shared with toolbox sessions. Of course if you need it for multiple users...
Maybe there should be a package for this? Reliable bash history would be very valuable.

My personal hack (not great but helps) is to append the toolbox name to the history filename.
That prevents a little clobbering at least.

Just for reference (not advocating), in `~/.bashrc`:
```
if [ -n "$container" ]; then
export HISTFILE="${HOME}/.bash_history.tb.${ID}${VERSION_ID}.${TERM}"
fi
```

**Comment by juhp** [comment]
But I would second defaulting to a different history file for toolbox containers.

**Comment by AdamWill** [comment]
Well, my position is that when "expected behaviour" results in eating thousands of lines of valuable user data, the expectations should be adjusted...

I don't remember why I do this as a systemwide snippet, honestly. Well, except that this way it applies to root as well as my regular user without needing to duplicate it (it is equally useful to have a long history as root, and I don't customarily use sudo except for doing `sudo su`). But the thing is, I do it, and I put it in my blog, so somebody else might do it. And who knows what other reasons people might have for doing it this way in systemwide config?

**Comment by juhp** [comment]
(True, though well I guess if it were packaged and default, it could even be included in fedora-toolbox images.)

Maybe it is also time to bump the default value of `HISTFILESIZE`?

**Comment by debarshiray** [comment]
So, the problem is that Toolbx containers generally have a separate `/etc` than the host, barring exceptions like `/etc/resolv.conf`, and because of that the `/etc/profile.d` snippet on the host about the Bash history goes missing in the container, and you end up getting surprised by things missing from the history.  Right?

We can't really make the containers share `/etc` with the host because they have different versions of binaries in `/usr` that may not work with the same `/etc`.

In this case, the snippet is also not a well known filename like `/etc/resolv.conf`.  So, we can't try to set it up by default.

One thing to note is that the host's `/etc/profile.d` is available inside the container at `/run/host/etc/profile.d`.  This could be used to solve the non-root case, by adding something like this to the start-up scripts in your `$HOME`:
```
if [ -f /run/.containerenv ]  && [ -f /run/.toolboxenv ]; then
    source /run/host/etc/profile.d/...
fi
```

The other option could be to extend our configuration file to specify such custom symbolic links that the user might want to have in their containers.  Some people also want to have custom mounts.

If the containers use a separate file to keep the Bash history, won't it be surprising that the history will be different across the host and different containers?  Or is there an easy way to chain Bash history files?

I also like @juhp 's idea of bumping the default value of `HISTFILESIZE`.  :)

**Comment by AdamWill** [comment]
> If the containers use a separate file to keep the Bash history, won't it be surprising that the history will be different across the host and different containers? Or is there an easy way to chain Bash history files?

I mean, it's kinda...debatable, I guess? It would be surprising to folks who have already become used to the current behaviour, though. But is it *inherently* surprising? Do we really have a strong expectation that containers share shell history with their hosts? The first time I ran toolbx, I wouldn't say I had an expectation about this. If it turned out that each toolbx container had its own history, I probably wouldn't have questioned that.

> I also like @juhp 's idea of bumping the default value of HISTFILESIZE. :)

Yes, this is clearly the lowest-hanging fruit, here.

**Comment by debarshiray** [comment]
Here's another idea.

Ultimately, if we could at least retain the environment variables like `HISTSIZE` and `HISTFILESIZE`, then it would reduce the impact of the problem a bit, right?  Toolbx currently has a list of environment variables that it tries to retain across the host and container boundary.  We can add these to that list:
```
$ git diff
diff --git a/src/pkg/utils/utils.go b/src/pkg/utils/utils.go
index 4992c36f71ba..5efbd9364035 100644
--- a/src/pkg/utils/utils.go
+++ b/src/pkg/utils/utils.go
@@ -84,6 +84,8 @@ var (
                "DBUS_SYSTEM_BUS_ADDRESS",
                "DESKTOP_SESSION",
                "DISPLAY",
+               "HISTFILESIZE",
+               "HISTSIZE",
                "LANG",
                "SHELL",
                "SSH_AUTH_SOCK",
```

The problem is that at least on Fedora `/etc/profile` overwrites `HISTSIZE` to 1000, but not `HISTFILESIZE`.  So, once the shell starts, the value propagated from the host gets lost.

Maybe we should update Fedora's shell start-up scripts to not touch `HISTSIZE` if it's already set?  I [see](https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html) that the default value for `HISTSIZE` is 500.  So, just leave it alone if it's anything other than 500.

**Comment by AdamWill** [comment]
at a guess, Fedora was probably at some point in history trying to be helpful by doubling the default history size. I suppose we could do that as a patch in the bash package instead, maybe? Leaving the default 500 alone seems like it might be poorly received by people who are used to 1000.

Really, the defaults for these should just be 100x bigger everywhere, heh.

**Comment by debarshiray** [comment]
By the way, these days Bash supports defining `PROMPT_COMMAND` as an array to let `/etc/profile.d/vte.sh` will append to the array if it's defined as such.  So, maybe it's time to update your [history snippet](https://www.happyassassin.net/posts/2015/01/16/bash-history-with-multiple-sessions/)?  :)

Note that Fedora's PROMPT_COMMAND is still not defined as an array, so we need to change that for `/etc/profile.d/vte.sh` to treat it as an array.

It was a long-standing feature request against Bash from VTE, and I am happy that it finally got done.

**Comment by debarshiray** [comment]
> Leaving the default 500 alone seems like it might be poorly received by people who are used to 1000.

I meant that if at shell start-up `HISTSIZE` is already set to, say, for example, 20000, then just leave it alone and don't set it to 1000.  Otherwise continue to set it to 1000 as before.

**Comment by AdamWill** [comment]
oh, I see, right. I misread.

**Comment by debarshiray** [comment]
> oh, I see, right. I misread.

:)

Does that make sense as a way forward?  If so, I can submit some pull requests tomorrow.

**Comment by debarshiray** [comment]
> Ultimately, if we could at least retain the environment variables like
> HISTSIZE and HISTFILESIZE, then it would reduce the impact of the
> problem a bit, right?

Since this is shell, I suppose one could cram that function directly into `PROMPT_COMMAND` and have it propagated across the host and container boundary?  It would be terribly unreadable, but it would work.

**Comment by debarshiray** [comment]
> Note that Fedora's `PROMPT_COMMAND` is still not defined as an array, so we need to change that for `/etc/profile.d/vte.sh` to treat it as an array.

Oops, I forgot that @adelton already made the changes:
* https://bugzilla.redhat.com/show_bug.cgi?id=2097525
* https://pagure.io/setup/pull-request/47
* https://pagure.io/setup/c/fd019bf4e0cdba9436c207b067ce8c0a9fdb5ef8

Now we need to wait for them to get shipped in Fedora.

**Comment by debarshiray** [comment]
> Here's another idea.
> 
> Ultimately, if we could at least retain the environment variables like `HISTSIZE` and `HISTFILESIZE`, then it would reduce the impact of the problem a bit, right? Toolbx currently has a list of environment variables that it tries to retain across the host and container boundary. We can add these to that list:
> 
> ```
> $ git diff
> diff --git a/src/pkg/utils/utils.go b/src/pkg/utils/utils.go
> index 4992c36f71ba..5efbd9364035 100644
> --- a/src/pkg/utils/utils.go
> +++ b/src/pkg/utils/utils.go
> @@ -84,6 +84,8 @@ var (
>                 "DBUS_SYSTEM_BUS_ADDRESS",
>                 "DESKTOP_SESSION",
>                 "DISPLAY",
> +               "HISTFILESIZE",
> +               "HISTSIZE",
>                 "LANG",
>                 "SHELL",
>                 "SSH_AUTH_SOCK",
> ```
> 
> The problem is that at least on Fedora `/etc/profile` overwrites `HISTSIZE` to 1000, but not `HISTFILESIZE`. So, once the shell starts, the value propagated from the host gets lost.
> 
> Maybe we should update Fedora's shell start-up scripts to not touch `HISTSIZE` if it's already set? I [see](https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html) that the default value for `HISTSIZE` is 500. So, just leave it alone if it's anything other than 500.

Here's a pull request to make Fedora's `/etc/profile` not overwrite the `HISTSIZE` environment variable:
https://pagure.io/setup/pull-request/48

**Comment by debarshiray** [comment]
Here's one for the Toolbx changes:
https://github.com/containers/toolbox/pull/1380

**Comment by debarshiray** [comment]
> Here's one for the Toolbx changes: #1380

I have been trying to write some tests for this one, and it looks like Bash start-up scripts on Arch Linux and Ubuntu don't have the problem with overwriting `HISTSIZE` that Fedora has.  This is a very pleasant surprise.  Otherwise we would have had to push through fixes for those as well.

**Comment by debarshiray** [comment]
I hope this improves things, @AdamWill 

Thanks for stopping by!  :)

**Comment by AdamWill** [comment]
So I just got a new laptop and decided to give running Silverblue as my main another shot, started a toolbx, and...hit this again! This is with toolbox-0.1.1-1.fc42.x86_64. HISTSIZE inside any toolbox container shows as 500, and my history gets truncated at 500 items.

is this because of Fedora's 500 override, or what?
