### ISSUE TITLE
Unable to run a sudo command in container -> "User is not in the sudoers file"

### ISSUE THREAD

**Issue by dabrain34** [containers/toolbox#1361]
**Describe the bug**
Using toolbox 0.99.2 0.99.3 or 0.99.4, i'm getting "user is not in the sudoers file" when i'm running sudo dnf update in a freshly created
toolbox container.

**Steps how to reproduce the behaviour**

**Expected behaviour**
I'm expected to run `sudo dnf update`

**Actual behaviour**

"user is not in the sudoers file"

**Screenshots**

**Output of `toolbox --version` (v0.0.90+)**
0.99.4

**Toolbox package info (`rpm -q toolbox`)**

**Output of `podman version`**
e.g.,
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.18.1
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

```

**Podman package info (`rpm -q podman`)**
e.g., `podman-1.9.2-1.fc32.x86_64`

**Info about your OS**
Ubuntu 22.04

**Additional context**
Seems that it was working few weeks ago...

If you see an error message saying: `Error: invalid entry point PID of container <name-of-container>`, add to the ticket output of command `podman start --attach <name-of-container>`.

**Comment by debarshiray** [comment]
Which image are you using?  On what host?

**Comment by dabrain34** [comment]
The host is a x86 machine with Ubuntu 22.04 and any image is having this issue either fedora or ubuntu.

`user is not in the sudoers file.`

**Comment by RoguedBear** [comment]
i can confirm i am facing this too.
host: ubuntu 22.04
container: ubuntu 22.04



currently looking into adding my user to sudoers manually

**Comment by debarshiray** [comment]
I am about to wrap up for the year, so I will have to revisit this in 2024.  Maybe @Jmennius (our Ubuntu maintainer) has some insight?

**Comment by Jmennius** [comment]
> I am about to wrap up for the year, so I will have to revisit this in 2024.  Maybe @Jmennius (our Ubuntu maintainer) has some insight?

I'll check this out on the weekend!

**Comment by p3732** [comment]
I too am currently facing this problem and will be available to provide feedback if needed.

**Comment by Jmennius** [comment]
Below are condensed  logs of `init-container` from Ubuntu 22.04 host (podman, toolbox from repositories), creating a F39 container:
```
"Looking up group for sudo"
"Group for sudo is wheel"
"Modifying user ievgenp with UID 1000:" usermod --append --groups wheel --home /home/ievgenp --shell /bin/bash --uid 1000 ievgenp
"Removing password for user ievgenp"
"Removing password for user root"
```
So it identifies the 'sudo' group correctly.

At the same time, inside the container (after enter):
```
ievgenp@toolbox:~$ id
uid=1000(ievgenp) gid=1000(ievgenp) groups=1000(ievgenp),0(root)
```
The user does not seem to actually be part of `wheel` group. But is it part of `root` group which I am not sure about the origin of.

While it is does seem to be fine in the groups file:
```
ievgenp@toolbox:~$ grep ievgenp /etc/group
wheel:x:10:ievgenp
ievgenp:x:1000:ievgenp
```

---

Issuing `newgrp wheel` does work as a workaround for the issue (for Fedora container, for Ubuntu that would be `newgrp sudo`).


I was able to mitigate the issue by using newer build `crun` from Lunar (`1.8-1`).

**Comment by rpolyano** [comment]
> Issuing `newgrp wheel` does work as a workaround for the issue (for Fedora container, for Ubuntu that would be `newgrp sudo`).

where did you issue this workaround command? Inside the container?  I have an Ubuntu container and issuing the command just asks for password and anything I enter (including nothing) just says Invalid password.

**Comment by Jmennius** [comment]
>  
> > Issuing `newgrp wheel` does work as a workaround for the issue (for Fedora container, for Ubuntu that would be `newgrp sudo`).
> 
> where did you issue this workaround command? Inside the container?  I have an Ubuntu container and issuing the command just asks for password and anything I enter (including nothing) just says Invalid password. 

Yes, inside the container.
It's weird that it asks for a password, that would indicate that something is wrong with `/etc/groups`, `/etc/gshadow`.. can you show their contents?
I'll try with Ubuntu (I think I've only tried Fedora on Ubuntu) myself.

Did you try updating `crun`?

**Comment by Jmennius** [comment]
I've just verified ubuntu on ubuntu (both 22.04) with updated `crun` (`1.8-1`) - works fine.
With old `crun` I indeed can't run `newgrp sudo` in any form I've tried.
Either way that does not seem to be a toolbox issue.

The best thing you can do is to backport  `crun`:
just go to the package page for lunar (https://packages.ubuntu.com/lunar/crun), click on architecture name (most likely `amd64`) and then download the package from any link you like. Once you have the package run `sudo apt install ~/Downloads/crun_1.8-1_amd64.deb`

It is also possible to add the repository, but it is then trickier to maintain if you ever dist-upgrade.

**Comment by cmarqu** [comment]
FWIW, with a Ubuntu 22.04 (jammy) host, I needed to also download and install https://packages.ubuntu.com/lunar/libyajl2, but then it worked fine.
