### ISSUE TITLE
Unknown command "‐‐log‐level" for "toolbox"

### ISSUE THREAD

**Issue by alcir** [containers/toolbox#1362]
The man page (or `toolbox --help`) states
```text
SYNOPSIS
       toolbox [‐‐assumeyes | ‐y]
               [‐‐help | ‐h]
               [‐‐log‐level LEVEL]
               [‐‐log‐podman]
               [‐‐verbose | ‐v]
               COMMAND [ARGS...]
```

But actually using `‐‐log‐level` doesn't work.

```text
toolbox ‐‐log‐level DEBUG enter
Error: unknown command "‐‐log‐level" for "toolbox"
```

**Comment by debarshiray** [comment]
See further below in the manual.  It lists the valid log levels that can be passed to `--log-level`:
```
      --log-level=level

       Log messages above specified level: debug, info, warn, error, fatal or panic (default: error)
```

**Comment by debarshiray** [comment]
In other words, try `--log-level debug`, not `--log-level DEBUG`.

**Comment by debarshiray** [comment]
Anyway, thanks for stopping by!

**Comment by alcir** [comment]
Sorry. My bad.
It was some "hidden" characters coming from cut&paste.
DEBUG or debug work anyway.

toolbox ‐‐log-level debug enter
toolbox --log-level debug enter

**Comment by debarshiray** [comment]
> toolbox ‐‐log-level debug enter

Yeah, something wrong with the second dash before `log-level`.

I am glad you managed to figure it out.
