### ISSUE TITLE
error in fedora-toolbox-39



### ISSUE THREAD

**Issue by dmitpv** [containers/toolbox#1406]
error in fedora-toolbox-39, but works fine in fedora-toolbox-38
![-1700066569](https://github.com/containers/toolbox/assets/24778434/4ddf6583-00be-4430-87e2-f469557f5ecd)
toolbox version 0.0.99.4
OS : ArchLinux

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/1410
