### ISSUE TITLE
Better instructions for other Linux distros

### ISSUE THREAD

**Issue by tiagofassoni** [containers/toolbox#1451]
The current installation docs say:
>Toolbx is installed by default on [Fedora Silverblue](https://fedoraproject.org/silverblue/) and [Workstation](https://fedoraproject.org/workstation/). On other operating systems it’s just a matter of installing the toolbox package.

However, no package called "container" exists for Ubuntu 22.04. It also does not exist for Ubuntu 23.10: https://packages.ubuntu.com/search?keywords=toolbox&searchon=names&suite=mantic&section=all

If I download the .tar.xz in the Releases section, I get what appears to be a project to be compiled using Meson, but no instructions whatsoever.

This looks like nitpicking, but the reason I'm asking this is that I want to use this project in a course with new students, and I need the installation to be easy for them.

I am also willing to write and improve the documentation myself, but I need some pointers first.

**Comment by notfirefox** [comment]
The [installation](https://containertoolbx.org/install/) page provides instructions on how to build the project from source.
> ### Dependencies and Building 
>
> Toolbx requires at least Podman 1.6.4, and optionally at least Skopeo 1.10.0, to work.
>
> It uses the Meson build system and the following dependencies are required to build it:
> - clang or gcc
> - go >= 1.13
> - go-md2man
> - meson >= 0.58.0
> - ninja
> - shadow >= 4.9
> - systemd
>
> If the following dependencies are available when building, then various optional features are enabled:
>
> - bash-completion
> - fish
>
> It can be built and installed as any other typical Meson-based project:
> ```sh
> [user@hostname toolbox]$ meson setup -Dprofile_dir=/etc/profile.d builddir
> [user@hostname toolbox]$ meson compile -C builddir
> [user@hostname toolbox]$ sudo meson install -C builddir
> ```

However if you use Ubuntu, it should be sufficient to install the package `podman-toolbox`.

**Comment by notfirefox** [comment]
Maybe we could add an Ubuntu badge to the read me file?
![image](https://github.com/containers/toolbox/assets/138280734/f96a5f7a-26be-44c1-b60e-014a748146ec)

**Comment by debarshiray** [comment]
> The current installation docs say:
> 
> > Toolbx is installed by default on [Fedora Silverblue](https://fedoraproject.org/silverblue/) and [Workstation](https://fedoraproject.org/workstation/). On other operating systems it’s just a matter of installing the toolbox package.
> 
> However, no package called "container" exists for Ubuntu 22.04. It also does not exist for Ubuntu 23.10: https://packages.ubuntu.com/search?keywords=toolbox&searchon=names&suite=mantic&section=all

Good point.  As @notfirefox pointed out, the package is `podman-toolbox` in the Debian family and I have now added it to the [installation](https://containertoolbx.org/install/) page.

We have also significantly updated the content on the Toolbx [website](https://containertoolbx.org/).  Other than [installation](https://containertoolbx.org/install/), you might be interested in these:
  * https://containertoolbx.org/doc/
  * https://containertoolbx.org/use/
 
> If I download the .tar.xz in the Releases section, I get what appears to be a project to be compiled using Meson, but no instructions whatsoever.

It's supposed to be a 'typical' Meson project.  The assumption is that Meson is common enough these days that those who want to build Toolbx from source will be either familiar with Meson or be able to learn it independently.

However, as @notfirefox pointed out, there are some basic instructions on the [installation](https://containertoolbx.org/install/) page.

> This looks like nitpicking, but the reason I'm asking this is that I want to use this project in a course with new students, and I need the installation to be easy for them.

Oh, that's wonderful.  :)

> I am also willing to write and improve the documentation myself, but I need some pointers first.

Let us know if you need something else.

**Comment by debarshiray** [comment]
> Maybe we could add an Ubuntu badge to the read me file?

Done in https://github.com/containers/toolbox/pull/1467

**Comment by debarshiray** [comment]
I am closing this issue.  Feel free to open ones if you need anything else.

Thanks for your interest in Toolbx, @tiagofassoni !

**Comment by tiagofassoni** [comment]
Thanks so much for the kind help, the information and the updated docs! I
had some health issues and couldn't answer before.

Em qua., 6 de mar. de 2024 às 13:50, Debarshi Ray ***@***.***>
escreveu:
