### ISSUE TITLE
actions/ubuntu-tests makes use of Node 16 which is end of life (EOL)

### ISSUE THREAD

**Issue by notfirefox** [containers/toolbox#1459]
**Is your feature request related to a problem? Please describe.**
Node 16 is being deprecated, here is a quick excerpt from [GitHub](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/):
> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. [...] Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

Currently when running `ubuntu-jammy-tests`, we get the following warning:

> [ubuntu-jammy-tests](https://github.com/containers/toolbox/actions/runs/8058965982/job/22012602972)
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Describe the solution you'd like**
Update `ubuntu-tests` so that it uses `checkout@v4` instead of `checkout@v3`.

**Describe alternatives you've considered**
None

**Additional context**
According to this [changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md#v400), it should be sufficient to bump the version of `actions/checkout` to 4.

**Comment by debarshiray** [comment]
Thanks for the heads-up, @notfirefox !  Would you have time to submit a pull request?

**Comment by notfirefox** [comment]
> Thanks for the heads-up, @notfirefox ! Would you have time to submit a pull request?

See https://github.com/containers/toolbox/pull/1466

**Comment by debarshiray** [comment]
[This](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) blog post says:
> Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

However, I can't spot any warnings from the `ubuntu-tests` workflow.  I am merely curious, because that way I will know how to look out for similar problems in the future.

**Comment by notfirefox** [comment]
@debarshiray https://github.com/containers/toolbox/actions/runs/8218105705

![image](https://github.com/containers/toolbox/assets/138280734/6362f029-e6d5-4c39-b7c5-b20cfc8832e8)

**Comment by debarshiray** [comment]
Aha, I see.  I had to click the *Summary* on the left.  Today I learnt.  :)
