### ISSUE TITLE
Update the welcome texts and prompts for toolbox creation

### ISSUE THREAD

**Issue by debarshiray** [containers/toolbox#146]
See these mockups from @allanday:

![mockups](https://user-images.githubusercontent.com/3208107/56972683-b55db200-6b6b-11e9-9856-99db906d54e9.png)

**Comment by allanday** [comment]
It would be good to avoid showing messages like "no toolbox found" during the first run experience: it could easily sound like something is broken and it's not a positive, led experience. If we can show specific messages in that situation, it would be good.

Here's some updated guidance for what the first run experience could look like:

![image](https://user-images.githubusercontent.com/213068/56983495-aed73680-6b7b-11e9-87af-96527b1478d1.png)

**Comment by matthiasclasen** [comment]
Looks great to me

**Comment by allanday** [comment]
These mockups were based on the idea of having a special terminal app that defaulted to using toolboxes. It's unclear whether we are actually going to do that, so it's probably best to close this.
