### ISSUE TITLE
Add distribution: Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by marknsikora** [containers/toolbox#1481]
**Is your feature request related to a problem? Please describe.**
Newest ubuntu release has dropped, not yet available as a toolbox image. 

**Describe the solution you'd like**
Create a new container image

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Jmennius** [comment]
I expect to tackle this on the weekend, expect a PR relatively soon.

**Comment by znmeb** [comment]
Thanks! I've been working with the Docker Hub image `docker.io/library/ubuntu:24.04` and "out of the box", the `unminimize`script doesn't work.I took a look at the shell script and found a work-around, but is it normal for `unminimze` to just exit without actually doing anything?
