### ISSUE TITLE
Gstreamer unable to find plugins in toolbox

### ISSUE THREAD

**Issue by monreal** [containers/toolbox#1515]
**Describe the bug**
Trying to convert some audio files using gst-launch from a toolbox, I noticed that non-core plugins are not detected.

**Steps how to reproduce the behaviour**
1.  dnf -y install gstreamer1 gstreamer1-plugins-base gstreamer1-plugins-good
2.  gst-launch-1.0 audiotestsrc num-buffers=100 ! taginject tags="title=testsrc,artist=gstreamer" ! vorbisenc ! oggmux ! filesink location=test.ogg
3. gst-inspect-1.0 taginject
No such element or plugin 'taginject'
4. gst-inspect-1.0 debug
No such element or plugin 'debug'

**Expected behaviour**
Installed plugins should be loaded and used by gst-launch-1.0 and gst-inspect-1.0

**Actual behaviour**
Only base pugins seem to be loaded for whatever reason

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.99.5

**Toolbx package info (`rpm -q toolbox`)**
toolbox-0.0.99.5-8.fc40.x86_64

**Output of `podman version`**
Client:       Podman Engine
Version:      5.0.3
API Version:  5.0.3
Go Version:   go1.22.2
Built:        Fri May 10 02:00:00 2024
OS/Arch:      linux/amd64

**Podman package info (`rpm -q podman`)**
podman-5.0.3-1.fc40.x86_64

**Info about your OS**
Fedora Silverblue 40

**Additional context**
This used to work with previous versions of Toolbox + Fedora (before 40)
Made a new container for this
Works outside the toolbox with gstreamer packages installed on the main system

**Comment by debarshiray** [comment]
> **Steps how to reproduce the behaviour**
> 
>     1. dnf -y install gstreamer1 gstreamer1-plugins-base gstreamer1-plugins-good
> 
>     2. gst-launch-1.0 audiotestsrc num-buffers=100 ! taginject tags="title=testsrc,artist=gstreamer" ! vorbisenc ! oggmux ! filesink location=test.ogg
> 
>     3. gst-inspect-1.0 taginject
>        No such element or plugin 'taginject'
> 
>     4. gst-inspect-1.0 debug
>        No such element or plugin 'debug'

This works for me with Toolbx 0.0.99.6.  I see that you are on an older version, but I can't think of a reason why it wouldn't work with it either.

Are you sure you don't have any environment variables set that might be interfering with this?

**Comment by debarshiray** [comment]
Glad to hear that, and thanks for confirming!
