### ISSUE TITLE
The version of podman-toolbox in apt is out of date

### ISSUE THREAD

**Issue by tom-reinders** [containers/toolbox#1569]
**Describe the bug**
The toolbox package for Ubuntu is out of date.

```
➜  ~ sudo apt-cache show podman-toolbox 
Package: podman-toolbox
Architecture: amd64
Version: 0.0.99.3+git20230118+446d7bfdef6a-2

...Made smaller for readability...

➜ 
```

**Steps how to reproduce the behaviour**
1. Run `sudo apt install podman-toolbox`

**Expected behaviour**
Get latest version (at time of writing this is `0.0.99.6`) of toolbox.

**Actual behaviour**
Got version `0.0.99.3` of toolbox.

**Additional context**
https://github.com/containers/toolbox/issues/1566#issuecomment-2422401047
> I'm only now noticing that i'm running `0.0.99.3` and the latest release is `0.0.99.6`.
> 
> I installed my package by running `sudo apt install podman-toolbox` because I thought "[On other operating systems it’s a matter of installing the `toolbox` or `podman-toolbox` package](https://containertoolbx.org/install/#:~:text=On%20other%20operating%20systems%20it%E2%80%99s%20a%20matter%20of%20installing%20the%20toolbox%20or%20podman%2Dtoolbox%20package)" meant that.
> 
> Is this incorrect? If so please update the install instructions to say so and show me instructions how to install it on Ubuntu, and maybe also remove the out of date package from apt. If not than the package needs to be updated in apt.

**Comment by debarshiray** [comment]
In https://github.com/containers/toolbox/issues/1566 @Jmennius meant that you need to report this downstream against the Ubuntu [package](https://packages.ubuntu.com/noble/podman-toolbox).  Someone already reported a similar [bug](https://bugs.launchpad.net/ubuntu/+source/golang-github-containers-toolbox/+bug/2069145).  Maybe you can follow that?

**Comment by debarshiray** [comment]
Closing, because updating the Ubuntu package can't be done upstream.

Sorry for the confusion.
