### ISSUE TITLE
screen inside of toolbox

### ISSUE THREAD

**Issue by fansari** [containers/toolbox#184]
If I start "screen" inside of toolbox the output is gargabe.

This happens also when my ~/.screenrc is empty.

TERM=linux

Wtih TERM=ansi it is the same issue.

Here some output of "ls -l".

```
ansari fansari   30 Dec  7 21:20  usr                                                                                 
                                     drwxrwxr-x.   2 fansari fansari   48 Jul 14  2018  vagrant                       
                                                                                               -rw-rw-r--.   1 fansari
 fansari 3269 Jul 15  2018  Vagrantfile                                                                               
                                       drwx------.  55 fansari fansari 4096 Apr  8  2018  vanessa                     
                                                                                                 drwxr-xr-x.   4 fansa
ri fansari   32 May  6 18:30  Videos                                                                                  
                                    drwxrwxr-x.   3 fansari fansari   87 Oct 31  2015  vmware                         
                                                                                             drwxrwxr-x.   4 fansari f
ansari   39 Apr 23  2018  WebstormProjects                                                                            
                                          drwxrwxr-x.   7 fansari fansari   89 Dec 31  2017  workspace                
                                                                                                      drwxrwxr-x.   2 
fansari fansari  259 Dec 23 15:13  X-Air                                                                              
                                        drwxrwxr-x.   4 fansari fansari   36 Jul  3  2018  zabbix                     
                                                                                                 ⬢[fansari@toolbox ~]$
```

**Comment by debarshiray** [comment]
Which terminal emulator were you using?

I haven't seen glitches this bad with VTE and `TERM=xterm-256color`.

**Comment by fansari** [comment]
As I said - I tried to set TERM to linux and ansi. Now I have also tried xterm-256color and it behaves the same way.

```
vanessa
       drwxr-xr-x.   4 fansari fansari   32 May  6 18:30  Videos
                                                                drwxrwxr-x.   3 fansari fansari   87 Oct 31  2015  vmware
                                                                                                                         drwxrwxr-x.   4 fansari fansari   39 Apr 23  2018  WebstormProjects
                                                                                                                                                                                            drwxrwxr-x.   7 fansari fansari   89 Dec 31  2017  workspace
          drwxrwxr-x.   2 fansari fansari  259 Dec 23 15:13  X-Air
                                                                  drwxrwxr-x.   4 fansari fansari   36 Jul  3  2018  zabbix
                                                                                                                           ⬢[fansari@toolbox ~]$ echo $TERM
                                                                                                                                                           screen.xterm-256color
                                                                                                                                                                                ⬢[fansari@toolbox ~]$ 


```

**Comment by debarshiray** [comment]
I see, ok. :(

I wonder, if like #14, this is also https://github.com/containers/libpod/issues/3179

**Comment by debarshiray** [comment]
Could you please try this again with Podman 1.5.0 and Toolbox from Git master?

**Comment by debarshiray** [comment]
@fansari ping ?

Somehow I just cannot reproduce using VTE and GNOME Terminal on Fedora.

**Comment by fansari** [comment]
Today I have updated my Fedora 30 and now I have podman 1.5.1.

When I run screen in toolbox I only get an error message:

Utmp slot not found -> not removed

Then screen is terminating. I have tested TERM linux and ansi but both give this error.

**Comment by debarshiray** [comment]
So, let me ask again. What terminal emulator are you using? I am not asking about the `TERM` variable, but what's the software inside which you are running the shell. Is the Linux console (ie., ctrl+alt+f3 and such) or is it GNOME Terminal or something else?

I am asking because I am not able to reproduce it at all and I haven't seen others bring this up. So I am not sure what's going on.

**Comment by fansari** [comment]
I always use the default GNOME terminal.

**Comment by debarshiray** [comment]
> I always use the default GNOME terminal.

Ok. I think that you shouldn't have to change the `TERM` variable because it's tied to the software that's providing the terminal emulation. eg., for GNOME Terminal `TERM` should be set to `xterm-256color`.

Since the last few years, GNOME Terminal doesn't update `utmp` and `wtmp` records anymore. I wonder if this `Utmp slot not found -> not removed` error is somehow related. Could you `strace` the screen process and see if that reveals something?

**Comment by debarshiray** [comment]
What's the ownership and permissions of `/run/utmp` on your system? I have:
```
$ ls -ld /run/utmp
-rw-rw-r--. 1 root utmp 1536 Sep 30 12:39 /run/utmp
```

One workaround is to put `deflogin off` in your Screen configuration. However, I have `deflogin on` in my `/etc/screenrc` and I don't see the error that you have been experiencing on my Fedoras, so I think something else is off.

**Comment by fansari** [comment]
-rw-rw-r--. 1 root utmp 9216 Sep 30 18:36 /run/utmp

**Comment by fansari** [comment]
⬢[fansari@toolbox fansari]$ sudo dnf install screen

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Fedora Modular 30 - x86_64                      2.4 MB/s | 2.7 MB     00:01    
Fedora Modular 30 - x86_64 - Updates            3.2 MB/s | 4.0 MB     00:01    
Fedora 30 - x86_64 - Updates                     11 MB/s |  21 MB     00:01    
Fedora 30 - x86_64                               16 MB/s |  70 MB     00:04    
Dependencies resolved.
================================================================================
 Package         Architecture    Version                  Repository       Size
================================================================================
Installing:
 screen          x86_64          4.6.2-8.fc30             fedora          557 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 557 k
Installed size: 1.0 M
Is this ok [y/N]: y
Downloading Packages:
screen-4.6.2-8.fc30.x86_64.rpm                  3.2 MB/s | 557 kB     00:00    
--------------------------------------------------------------------------------
Total                                           688 kB/s | 557 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: screen-4.6.2-8.fc30.x86_64                             1/1 
  Installing       : screen-4.6.2-8.fc30.x86_64                             1/1 
Error unpacking rpm package screen-4.6.2-8.fc30.x86_64
  Verifying        : screen-4.6.2-8.fc30.x86_64                             1/1 

Failed:
  screen-4.6.2-8.fc30.x86_64                                                    

Error: Transaction failed

**Comment by fansari** [comment]
After this screen is installed despite of the error message.

The toolbox is not usable anymore after I ran "dnf upgrade". Or is this not allowed/recommended inside the box?

Now I can open screen but it uses only half of the terminal (vertically).

I can fix this when I comment this line of my .screenrc like this:

```
# termcapinfo xterm* ti@:te@
```

**Comment by fansari** [comment]
After "dnf upgrade":

```
[fansari@bat ~]$ toolbox enter
toolbox: failed to create /run/.toolboxenv in container fedora-toolbox-30
```
After this I have to stop and remove the toolbox and recreate it.

**Comment by debarshiray** [comment]
The `Error: Transaction failed` from DNF makes me think that there's something wrong with `fuse-overlayfs`. What does `rpm -q fuse-overlayfs` say?

**Comment by fansari** [comment]
On the host it gives fuse-overlayfs-0.6.2-2.git67a4afe.fc30.x86_64.
Inside of the toolbox it is not installed.

**Comment by debarshiray** [comment]
Ok. I see various bug-fixes between `fuse-overlayfs-0.6.2` and `fuse-overlayfs-0.6.3`.

Could you please try `fuse-overlayfs-0.6.3-2.0.dev.git46c0f8e.fc30`:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1390375

(yes, `fuse-overlayfs` is only meant to be on the host)

Are the DNF failures more or less reproducable? If so it might be practical to concentrate on those first. Such strange filesystem errors are usually caused by `fuse-overlayfs`.

Thanks for sticking with this issue for so long. I wish we could have nailed it sooner.

**Comment by debarshiray** [comment]
Are you still seeing this? Or did it somehow get fixed along the way?

**Comment by fansari** [comment]
With Fedora 31 Sliverblue screen behaves normal within toolbox. So this issue is solved.

**Comment by debarshiray** [comment]
Ok, thanks for the confirmation @fansari
