### ISSUE TITLE
Avahi resolver does not work inside the toolbox

### ISSUE THREAD

**Issue by mildred** [containers/toolbox#209]
After installing `nss-mdns` inside the toolbox, I have the following in `/etc/nsswitch.conf`:

```
hosts:      files mdns4_minimal [NOTFOUND=return] dns myhostname
```

However, `ssh elyas.local` works outside the toolbox but not inside:

```
mildred@toolbox$ ssh elyas.local
ssh: Could not resolve hostname elyas.local: Name or service not known
```

This is a problem to run ansible on local hosts...

**Comment by debarshiray** [comment]
Yes, I can reproduce with `avahi-resolve --name kolache.local`.

**Comment by debarshiray** [comment]
After playing with `gdbus(1)` and d-feet inside a Flatpak container and a Toolbox container, I see that D-Bus clients inside the latter have problems accessing services on the system D-Bus instance.

This works:
 ```
host$ flatpak run --devel --command=bash org.gnome.dfeet
flatpak$ gdbus introspect --system --dest org.freedesktop.Avahi --object-path /
...
```

This doesn't:
 ```
host$ toolbox enter
flatpak$ gdbus introspect --system --dest org.freedesktop.Avahi --object-path /
Error: Timeout was reached
```

I don't know why this is the case, though.

**Comment by mildred** [comment]
This is also an issue on Silverblue, when using software inside the toolbox that must access network devices (example: simple-scan, not available as a Flatpak, cannot detect network scanners)

**Comment by Jmennius** [comment]
In my case, the dbus introspection does work, but avahi client still doesn't work.

Apparently that's because of SELinux policies:
```log
Nov 08 15:20:07 hostname audit[789]: USER_AVC pid=789 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for  scontext=system_u:system_r:avahi_t:s0 tcontext=unconfined_u:system_r:container_runtime_t:s0 tclass=dbus permissive=0
                                        exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?'
```

I'll see if I can fix that.
