### ISSUE TITLE
Duplicates in toolbox list

### ISSUE THREAD

**Issue by Dorian-DS** [containers/toolbox#226]
Duplication in list if you use a period in the name.

Container ID's match and both will disappear if you run toolbox rm on it.

```
[dorian@silverblue ~]$ toolbox list
Images created by toolbox
IMAGE ID      IMAGE NAME                                        CREATED
e9beb8775c6c  localhost/fedora-toolbox-dorian:29                27 hours ago
3e43cfbe60b7  registry.fedoraproject.org/f29/fedora-toolbox:29  6 days ago
Containers created by toolbox
CONTAINER ID  CONTAINER NAME            CREATED       STATUS   IMAGE NAME
7f9b4c82621d  fedora-toolbox-dorian-29  27 hours ago  Created  localhost/fedora-toolbox-dorian:29

[dorian@silverblue ~]$ toolbox create --container fed29 --release 29
Created container: fed29
Enter with: toolbox enter --container fed29

[dorian@silverblue ~]$ toolbox list
Images created by toolbox
IMAGE ID      IMAGE NAME                                        CREATED
e9beb8775c6c  localhost/fedora-toolbox-dorian:29                27 hours ago
3e43cfbe60b7  registry.fedoraproject.org/f29/fedora-toolbox:29  6 days ago
Containers created by toolbox
CONTAINER ID  CONTAINER NAME            CREATED        STATUS   IMAGE NAME
bc9838c56733  fed29                     8 seconds ago  Created  registry.fedoraproject.org/f29/fedora-toolbox:29
7f9b4c82621d  fedora-toolbox-dorian-29  27 hours ago   Created  localhost/fedora-toolbox-dorian:29

[dorian@silverblue ~]$ toolbox create --container fed29.1 --release 29
Created container: fed29.1
Enter with: toolbox enter --container fed29.1

[dorian@silverblue ~]$ toolbox list
Images created by toolbox
IMAGE ID      IMAGE NAME                                        CREATED
e9beb8775c6c  localhost/fedora-toolbox-dorian:29                27 hours ago
3e43cfbe60b7  registry.fedoraproject.org/f29/fedora-toolbox:29  6 days ago
Containers created by toolbox
CONTAINER ID  CONTAINER NAME            CREATED         STATUS   IMAGE NAME
48257c617c1b  fed29.1                   4 seconds ago   Created  registry.fedoraproject.org/f29/fedora-toolbox:29
bc9838c56733  fed29                     24 seconds ago  Created  registry.fedoraproject.org/f29/fedora-toolbox:29
48257c617c1b  fed29.1                   4 seconds ago   Created  registry.fedoraproject.org/f29/fedora-toolbox:29
7f9b4c82621d  fedora-toolbox-dorian-29  27 hours ago    Created  localhost/fedora-toolbox-dorian:29
[dorian@silverblue ~]$ 
```

**Comment by HarryPhoon** [comment]
Hi @Dorian-DS, I was able to reproduce this bug. I'll take a look at what's causing it.

**Comment by HarryPhoon** [comment]
Finally found the culprit. Podman doesn't support regular expressions in filter. It is already tracked https://github.com/containers/libpod/issues/3394 and a pull request that adds support for it has already been merged (https://github.com/containers/libpod/pull/3599). This issue should be fixed in the future releases of Podman.

**Comment by debarshiray** [comment]
> Finally found the culprit. Podman doesn't support regular expressions in
> filter. It is already tracked [containers/libpod#3394](https://github.com/containers/libpod/issues/3394)
> and a pull request that adds support for it has already been merged
> ([containers/libpod#3599](https://github.com/containers/libpod/pull/3599)). This
> issue should be fixed in the future releases of Podman.

Yes, exactly! @HarryPhoon is right.

(I meant to comment on this earlier, but forgot.)

**Comment by HarryPhoon** [comment]
Still we need to add a flag that'll check the support of regex and based on that change the filter.

**Comment by debarshiray** [comment]
> Still we need to add a flag that'll check the support of regex and based on that change the filter.

So far we've relied upon the presence of some flag in Podman's `--help` output for feature detection. Another option is to look at `podman version --format '{{.Version}}'`.

These are problems that wouldn't go away if we rewrite Toolbox as a Go program directly using the libpod API. :P

**Comment by Dorian-DS** [comment]
So wait for Podman's fix and this should be resolved?

**Comment by debarshiray** [comment]
Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal , and this issue is no longer present in the Go version.
