### ISSUE TITLE
Bash completion breaks if any global option other than --verbose is used

### ISSUE THREAD

**Issue by debarshiray** [containers/toolbox#296]
This works:
```
[rishi@kolache ~]$ toolbox --verbose <tab><tab>
create          help            list            rmi
enter           init-container  rm              run
```

But this doesn't:
```
$ toolbox --assumeyes <tab><tab>
```

I think that this is because of this snippet written when `--verbose` was the only global option:
```
  local command
  if [ "${COMP_WORDS[1]}" = --verbose ]; then
    command=${COMP_WORDS[2]}
  else
    command=${COMP_WORDS[1]}
  fi
```

/cc @fmuellner @HarryMichal

**Comment by HarryMichal** [comment]
Mentioned PRs were never really merged but the rewritten version of Toolbox has an [updated bash-completion script](https://github.com/containers/toolbox/pull/318/commits/df8a7811c2f16c2879ba5154576279d244d847e0) that should fix this issue.

**Comment by allanday** [comment]
In case it's not clear - let's use this ticket to track bash completion in general. It'd be great to have that working in all the places you might need it.
