### ISSUE TITLE
Allow additional bind mounts to be specified to toolbox-create

### ISSUE THREAD

**Issue by pwithnall** [containers/toolbox#307]
It would be useful to be able to specify additional bind mounts when creating a container. In my particular use case, I would like to expose `/opt` on my host to my container, since I have source code on the host and would like to build it inside the container.

Something like the following would be good:
```
toolbox create --bind /opt:/opt --bind /another-path:/somewhere-else
```

These would just be passed straight through as `--volume` arguments to `podman create`.

(Sorry for not putting together a PR myself, but editing a 2100 line bash script really doesn’t excite me.)

**Comment by cgwalters** [comment]
This is exactly https://github.com/debarshiray/toolbox/pull/100 which started [a reimplementation](https://github.com/cgwalters/coretoolbox) - we're going to merge things.

**Comment by pwithnall** [comment]
Let’s close this as a duplicate of #100 then, thanks!
