### ISSUE TITLE
Toolbox refuses to accept keyboard input in certain situations

### ISSUE THREAD

**Issue by Honza0297** [containers/toolbox#310]
How to reproduce: 
* Type "toolbox enter" or open new temrinal tab when inside toolbox container
* Before `[user@toolbox user]$` appears, there is a blank shell for a while. Start typing now (no matter what). 
* After `[user@toolbox user]$` appears, no more keyboard input is accepted, including "CTRL+C" etc.

**Comment by maxwell-k** [comment]
I can reproduce this behaviour using toolbox 0.0.15

**Comment by HarryMichal** [comment]
Just tried with pure Podman and this also happens. What I did:
```
$ podman pull alpine
$ podman create alpine sleep 100000
$ podman start --latest
$ podman exec -itl --latest /bin/sh (after executing this, type anything on the keyboard, before entering the container)
```

**Comment by HarryMichal** [comment]
I opened an issue in https://github.com/containers/libpod/issues/4397

**Comment by HarryMichal** [comment]
The ticket has been closed and the issue should be hopefully fixed in the future versions of Podman. Closing.
