### ISSUE TITLE
Allow loading toolbox.sh from custom location

### ISSUE THREAD

**Issue by Seirdy** [containers/toolbox#313]
It is currently impossible to install toolbox without root privileges because `toolbox` searches for `toolbox.sh` in a path hardcoded to `/etc/profile.d`.

While `toolbox.sh` can be installed to a custom location, there doesn't seem to be a clear way to load it from a custom location.

**Comment by Seirdy** [comment]
I'm up for making a PR to fix this issue. Would setting the location via environment variable or command-line flag be preferred?

**Comment by HarryMichal** [comment]
I would personally prefer this to be set by an environment variable. But I would wait for @debarshiray to say what he prefers.

**Comment by Seirdy** [comment]
Went ahead and made the PR anyway.

**Comment by debarshiray** [comment]
I don't want to go too far in this direction.

@HarryMichal has already started working on our long-standing plan to rewrite Toolbox in Go. It's safe to say that the current code is mostly in maintenance mode. We might still add a new feature here and there, but they will either be things that are important for a smooth switch to the Go version or really pressing short-term needs.

Therefore, I don't want to add new configuration knobs that won't be used by a big chunk of our users to the shell version of Toolbox.

With a statically compiled programming language things like installation prefixes are easy to bake into the final binary, which will make this problem go away. Any changes to the shell script in this direction will soon be made redundant by the Go code.
