### ISSUE TITLE
Rebuild registry.fedoraproject.org/f31/fedora-toolbox from release fedora:31

### ISSUE THREAD

**Issue by evelineraine** [containers/toolbox#321]
The latest release of toolbox image - `registry.fedoraproject.org/f31/fedora-toolbox:f31-7` is built on top of still-beta `fedora:31` image. When DNF-installing new packages some of the post-installation scripts fail, due to some ABI incompatibilities.

Since Fedora 31 is out of Beta already, it would be nice to have a `f31-8` image on top of the stable, release image.

---

An example of errors that are probably due to version incompatibility
```
toolbox$ dnf upgrade -y
...
  Cleanup          : libgcc-9.1.1-2.fc31.1.x86_64                       199/199
  Running scriptlet: libgcc-9.1.1-2.fc31.1.x86_64                       199/199 
  Running scriptlet: crypto-policies-20191002-1.gitc93dc99.fc31.noarc   199/199 
/var/tmp/rpm-tmp.KF4Fk7: line 1:   265 Segmentation fault      (core dumped) /usr/bin/update-crypto-policies --no-check > /dev/null 2> /dev/null

  Running scriptlet: libgcc-9.1.1-2.fc31.1.x86_64                       199/199 
/sbin/ldconfig: /lib64/ is not a symbolic link

gdk-pixbuf-query-loaders-64: error while loading shared libraries: shm_directory: cannot open shared object file: No such file or directory
warning: %triggerpostun(gdk-pixbuf2-2.40.0-1.fc31.x86_64) scriptlet failed, exit status 127


Error in <unknown> scriptlet in rpm package libgcc
  Running scriptlet: glibc-common-2.30-5.fc31.x86_64                    199/199 
/sbin/ldconfig: /lib64/ is not a symbolic link

  Running scriptlet: glib2-2.62.2-1.fc31.x86_64                         199/199 
  Running scriptlet: gdk-pixbuf2-2.40.0-1.fc31.x86_64                   199/199 
gdk-pixbuf-query-loaders-64: error while loading shared libraries: shm_directory: cannot open shared object file: No such file or directory
warning: %triggerin(gdk-pixbuf2-2.40.0-1.fc31.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package gdk-pixbuf2
  Running scriptlet: systemd-243-4.gitef67743.fc31.x86_64               199/199
```

Without `dnf upgrade` first, installing additional packages has multiple errors, and **SEGFAULT**s. After the upgrade everything goes smoothly.

**Comment by juhp** [comment]
Thanks, I kicked off https://koji.fedoraproject.org/koji/taskinfo?taskID=38800419

**Comment by HarryMichal** [comment]
I will close this when the image hits stable.

**Comment by juhp** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-CONTAINER-2019-35ff6e72f3
should be in the Fedora testing registry now

**Comment by evelineraine** [comment]
Tested with the new `31-8` image and everything is working without prior `dnf upgrade`. 

The only exception being this strange VIM error:
```shell
/var/tmp/rpm-tmp.XMzJeY: line 1:   284 Segmentation fault      (core dumped) /usr/bin/vim -c ":helptags /usr/share/vim/vimfiles/doc" -c :q &> /dev/null
```
But I don't think it's critical or at all relevant to toolbox.

Thank you! ❤️

**Comment by juhp** [comment]
@evelineraine Is that vim crash still reproducible and specific to toolbox?
