### ISSUE TITLE
Can't add myself to mock group in toolbox "usermod: group 'mock' does not exist"

### ISSUE THREAD

**Issue by Zlopez** [containers/toolbox#325]
I'm trying to get `flatpak-module local-build` running in F31 toolbox and I have mock installed:
```
$ rpm -qa | grep mock                                                                                                                                                                         
mock-1.4.21-1.fc31.noarch
mock-scm-1.4.21-1.fc31.noarch
```

But because my user isn't in the `mock` group I can't build any flatpak. So I tried to add my user to `mock` group and this is the output:
```
$ sudo usermod -a -G mock zlopez                                                                                                                                                         
usermod: group 'mock' does not exist
```

**Comment by kronenpj** [comment]
@Zlopez  Does your `/etc/group` file have a mock entry? Mine shows:
`mock:x:135:` after just installing the `mock` package and dependencies. I was able to `sudo usermod -a -G mock kronenpj` without issue.

**Comment by Zlopez** [comment]
@kronenpj I looked in `/etc/group` and there is no `mock` entry.

**Comment by debarshiray** [comment]
Interesting. I haven't looked into this too closely, but could this be about passing `--old-chroot` to `mock` because `systemd-nspawn` not working inside Toolbox containers: https://github.com/rpm-software-management/mock/pull/337 ?

**Comment by HarryMichal** [comment]
Hi @Zlopez! I just tried to reproduce your issue and could not. I pulled the latest fedora-toolbox:31 image, create a container, installed mock, added myself to the group successfully and then reentered the container.

Is the issue still present on your machine?

**Comment by Zlopez** [comment]
The issue is gone, probably fixed in newer toolbox container.
