### ISSUE TITLE
toolbox reset removes ALL containers and images!

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#326]
I don't really like this and the behavior surprised me...
I didn't expect `toolbox reset` would also remove all non-toolbox images (and containers).
I don't feel the warning

    All existing podman (and toolbox) containers and images will be removed.

is quite strong enough, or I didn't believe it anyway. ;-)

**Comment by debarshiray** [comment]
Maybe we should put the message in red?

**Comment by evelineraine** [comment]
This also surprises me that there is such *ordinary* command, like `reset` that does such a global change. I wouldn't have believed the message either 😅 
Seeing it right beside the `create` and `enter` commands, my first assumption was that it would recreate your `fedora-toolbox-31` or at least remove toolbox-created containers.

I think it's dangerous to have it named like this - it could mess up your local-only containers so easily. Perhaps, a different name / location could be a better fit, like:
* `toolbox debug wipe` or `toolbox develop wipe`, the way [OSTree](https://www.mankier.com/1/ostree-admin-unlock) does it with it's dangerous `unlock` command
* `/usr/libexec/toolbox-wipe`, the way [BTRFS](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs#COMMANDS) and Systemd put their *more-advanced* commands

Choosing either (or some other one) would make it clear that this is a *special* command, and it shouldn't be assumed to behave in any safe way (especially if named `wipe`) and could also create a framework for new development/dangerous commands to be added.

Thanks!

**Comment by markstos** [comment]
The `darcs` project used an `obliterate` subcommand for a particularly dangerous operation. That's another option.

**Comment by debarshiray** [comment]
`podman system reset` is now a thing in Podman 1.7.0. See https://github.com/containers/libpod/issues/4240

So, we can retire `toolbox reset` and we can redirect our wishes and complaints to Podman instead! :D

**Comment by debarshiray** [comment]
Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal The Go version deprecates the `reset` command in favour of `podman system migrate` and is now merely a wrapper around it.
