### ISSUE TITLE
Passthrough some directory under /home

### ISSUE THREAD

**Issue by Fatmice** [containers/toolbox#331]
I would like to passthrough a directory under /home to the container.  How do I go about doing this? Is there some config files that I can edit for each container?

**Comment by maxwell-k** [comment]
Did you check in `/var/run/host/var/home`?  On Fedora Silverblue this contains the home directory.

**Comment by Fatmice** [comment]
I'm on Fedora 31, the path /var/run/host/var/home is not found.  There are various things under /var/run/host/var not not the home directory. I have intel compiler installed under /home/intel and to use it normally one must source the file psxevars.sh when lauching a shell, which is located under /home/intel/parallel_studio_xe_*_*/

**Comment by maxwell-k** [comment]
Sorry I am a version behind, all I can suggest is having a look around in `/var/run/host`. From [the docs](https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/) I still think `/home` should be a symlink to `/var/home`; but I can't test at the moment. Good luck.

**Comment by debarshiray** [comment]
The definition of `/var` depends on whether you are on Silverblue or not. On Silverblue `/home` is a symbolic link to `/var`.

Containers created with recent versions of Toolbox make the host's `/var` available at `/run/host/var` inside the container. So, if you use `/var/parallel_studio_xe__` on the host, instead of `/home/parallel_studio_xe__`, then what @maxwell-k suggested should work.

**Comment by markstos** [comment]
This relates to #183, which is a feature request not mount `/home` by default and instead support mounting just specific directories in the container.

**Comment by debarshiray** [comment]
I am tentatively closing this based on the idea of using `/var/intel` instead of `/home/intel`.

**Comment by Fatmice** [comment]
Sorry, but I disagree with that notion. /var should not be a dumping place for programs and tool-chains...

**Comment by markstos** [comment]
@Fatmice One of Red Hat's own developers suggested that there be an option to add additional mount points under / on Silverblue over a year ago, but the idea was never acted on:

https://github.com/coreos/rpm-ostree/issues/1711

I gave up and moved on to Arch Linux. Silverblue is too inflexible and a key issue like this is seeing little progress. Maybe in another couple years I'll check back in and see what progress there's been.

Maybe there's merit to having just one r/w partition and have that be named "/var", but there are multiple decades of software built on the assumption that "/home" physically exists.

For Silverblue to gain traction faster it seems prudent to support some kind of transition or compatibility solution where other mount points can be supported, as one their own team members suggested.

**Comment by Fatmice** [comment]
@markstos I personally do not mind if there is only one r/w partition and it must be /var but at least allow mounting something else read-only, like /home/intel...

**Comment by debarshiray** [comment]
> Containers created with recent versions of Toolbox make the host's
> /var available at /run/host/var inside the container.

Even more recent versions of Toolbx (newer than 0.0.99.3, to be precise) make the entire `/` from the host available at `/run/host`.  So, containers created with Toolbx >= 0.0.99.3 will have `/run/host/home` regardless of whether it's Fedora Silverblue or Workstation.

**Comment by Fatmice** [comment]
This is very good to hear

**Comment by markstos** [comment]
> Even more recent versions of Toolbx (newer than 0.0.99.3, to be precise) make the entire / from the host available at /run/host. 

Where is this document? I don't see it in the main README or in the docs for the `create` command:

https://github.com/containers/toolbox/blob/main/doc/toolbox-create.1.md
