### ISSUE TITLE
toolbox stop command?

### ISSUE THREAD

**Issue by valankar** [containers/toolbox#334]
I may be misunderstanding the usage workflow of toolbox, but how should I stop the created toolbox? I see how to exit it, but 'toolbox list' and 'podman ps' shows it still running. I don't want to 'toolbox rm', since I would lose all changes to the toolbox right? Should I use 'podman stop'?

It might make sense to clarify the workflow in the docs.

**Comment by debarshiray** [comment]
Yes, `podman stop` should work. Ideally, I'd have liked to make it *reference counted*, where the container is automatically stopped when the last `toolbox enter` or toolbox run` session goes away, but that's not the case right now.

I am curious, though. Why do you want to stop them? A running toolbox container amounts to `sleep +Inf` which shouldn't be that expensive.

**Comment by valankar** [comment]
Thanks, I didn't realize they take very little resources.

**Comment by hadess** [comment]
FWIW, I want a `stop` command because I can't remove running containers:
https://github.com/containers/toolbox/issues/645

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/114

**Comment by JensTimmerman** [comment]
I was having the same issue, 
I wanted to stop them because `toolbox rm container` responds with: `Error: container testing-f34 is running`
So I had to run podman stop first

**Comment by daniejstriata** [comment]
I wanted to stop all the running containers as I was not using them all at the same time. Are you saying that although they are running I'm not losing the memory needed to run the containers?
