### ISSUE TITLE
Feature request: exec

### ISSUE THREAD

**Issue by BobyMCbobs** [containers/toolbox#338]
# Feature
A very useful feature in `podman` is the ability to run `podman exec -it ContainerIDorName Command` which runs a single command inside of an existing container.

## Motivation
There may be some commands which should be run by desktop files or shell scripts which need to interface from the host to a toolbox container.

## Implementation
`iitoolbox exec ContainerIDorName Command` maps to `podman exec -it ContainerIDorName Command`

---

What are your thoughts?

**Comment by HarryMichal** [comment]
Hi  @BobyMCbobs, there already is a command `run` that allows you to run a command in a container without entering it. Is that not what you're looking for??

**Comment by BobyMCbobs** [comment]
> Hi @BobyMCbobs, there already is a command `run` that allows you to run a command in a container without entering it. Is that not what you're looking for??

Oh! You're right. The documentation seems to have slipped past me.
Isn't `run` a bit of an odd mapping for it though? Wouldn't `exec` make more sense? -- in terms of how `podman` and `docker` both map it?

**Comment by HarryMichal** [comment]
I don't really see a difference between those two. You can say `Toolbox, run a command` as well as `Toolbox, execute a command`. I also think, that `run` is a bit more common word than `exec`/`execute`, but that is just my personal opinion.

**Comment by debarshiray** [comment]
Yes, as @HarryMichal said. Also, `toolbox run` is a bit like `flatpak run`.
