### ISSUE TITLE
Fedora 31: /run/host/etc/resolv.conf does not exist

### ISSUE THREAD

**Issue by fansari** [containers/toolbox#339]
After creating a new fedora-toolbox-31 I noticed that /run/host/etc/resolv.conf does not exist. /etc/resolv.conf is a link to this file.

I can remove the link and replace it with content - but this is not a permanent solution since this works only until the next start of the box.

Maybe this is related to the fact that I changed from NetworkManager to systemd-networkd on my host system.

What is the correct way to fix this?

**Comment by TingPing** [comment]
Duplicate of #187
