### ISSUE TITLE
Typing during toolbox initialization renders terminal unresponsive

### ISSUE THREAD

**Issue by cjao** [containers/toolbox#342]
Running toolbox 0.0.16-1.fc31.

To reproduce:
1. Run `toolbox enter`, and type something before the toolbox terminal prompt appears.
2. Observe that subsequent keystrokes have no effect.

**Comment by maxwell-k** [comment]
@cjao do you think this could be the same problem as https://github.com/containers/toolbox/issues/310 ?

Your description sounds very similar.

**Comment by cjao** [comment]
Yes, that looks right. Closing this as duplicate of #310

**Comment by debarshiray** [comment]
@maxwell-k thanks for triaging this!
