### ISSUE TITLE
toolbox: failed to create /run/.toolboxenv in container fedora-toolbox-31

### ISSUE THREAD

**Issue by tmstaedt** [containers/toolbox#359]
https://discussion.fedoraproject.org/t/toolbox-not-working-again/12744?u=tmstaedt

Got that error after doing a rpm-ostree upgrade. Did a rollback and toolbox would work again!!

[tom@linux2 ~]$ rpm-ostree db diff
ostree diff commit from: rollback deployment (2b1b1e95795a90c85dd27c5b89fd0e2c54c01f93b57f53d15a55ef601cc8eb87)
ostree diff commit to:   booted deployment (638125aee2de57bb643a9a1c40e0f1eee2c3e3b015a8a4783982e26443294c8a)
Downgraded:
  libinput 1.15.0-1.fc31 -> 1.14.3-2.fc31
  libtirpc 1.2.5-0.fc31 -> 1.1.4-2.rc3.fc31
  python-pip-wheel 19.1.1-7.fc31 -> 19.1.1-6.fc31
  python3-pip 19.1.1-7.fc31 -> 19.1.1-6.fc31

------------------------------------------------------------------
rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/31/x86_64/silverblue
Version: 31.20200107.0 (2020-01-07T01:34:27Z)
BaseCommit: 3ea3a112a5a5e89559435fecb9377549edbbe93eb44a3888deadaf2c4f995d37
GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
LayeredPackages: fedora-workstation-repositories filelight google-chrome mupdf virt-manager

ostree://fedora:fedora/31/x86_64/silverblue
Version: 31.20200108.0 (2020-01-08T11:26:07Z)
BaseCommit: 13625cd496d7cccc8729af79df460d8e1ca75a446ce0da0537c86ec4cc67302c
GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
LayeredPackages: fedora-workstation-repositories filelight google-chrome mupdf virt-manager

**Comment by HarryMichal** [comment]
Hi @tmstaedt, could you also, please, put here the output of `toolbox --verbose enter`??

**Comment by tmstaedt** [comment]
> Hi @tmstaedt, could you also, please, put here the output of `toolbox --verbose enter`??

tom@linux2 ~]$ toolbox enter --container fedora-toolbox-31
toolbox: failed to create /run/.toolboxenv in container fedora-toolbox-31
[tom@linux2 ~]$ toolbox --verbose enter --container fedora-toolbox-31
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user tom
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: running on a cgroups v2 host
toolbox: current Podman version is 1.6.2
toolbox: migration not needed: Podman version 1.6.2 is unchanged
toolbox: Fedora generational core is f31
toolbox: base image is fedora-toolbox:31
toolbox: container is fedora-toolbox-31
toolbox: checking if container fedora-toolbox-31 exists
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: starting container fedora-toolbox-31
toolbox: /etc/profile.d/toolbox.sh already mounted in container fedora-toolbox-31
toolbox: inspecting entry point of container fedora-toolbox-31
toolbox: entry point of container fedora-toolbox-31 is toolbox
toolbox: waiting for container fedora-toolbox-31 to finish initializing
Error: unable to find user root: no matching entries in passwd file
toolbox: failed to create /run/.toolboxenv in container fedora-toolbox-31

**Comment by tmstaedt** [comment]
All right. Works again with today's upgrade:

[tom@linux2 ~]$ rpm-ostree db diff
ostree diff commit from: rollback deployment (638125aee2de57bb643a9a1c40e0f1eee2c3e3b015a8a4783982e26443294c8a)
ostree diff commit to:   booted deployment (83d8c4b2c9db4fd4be63e4220feb8d6b3308547a5c28da01adeaa7df90bc0902)
Upgraded:
  firefox 71.0-15.fc31 -> 72.0.1-1.fc31
  kf5-kxmlgui 5.64.0-1.fc31 -> 5.64.0-2.fc31
  libinput 1.14.3-2.fc31 -> 1.15.0-1.fc31
  libtirpc 1.1.4-2.rc3.fc31 -> 1.2.5-0.fc31
  python-pip-wheel 19.1.1-6.fc31 -> 19.1.1-7.fc31
  python3-pip 19.1.1-6.fc31 -> 19.1.1-7.fc31
  qgnomeplatform 0.6.0-1.fc31 -> 0.6.0-2.fc31
  qt5-qtbase 5.12.5-2.fc31 -> 5.13.2-1.fc31
  qt5-qtbase-common 5.12.5-2.fc31 -> 5.13.2-1.fc31
  qt5-qtbase-gui 5.12.5-2.fc31 -> 5.13.2-1.fc31
  qt5-qtdeclarative 5.12.5-4.fc31 -> 5.13.2-1.fc31
  qt5-qtspeech 5.12.5-1.fc31 -> 5.13.2-1.fc31
  qt5-qtspeech-speechd 5.12.5-1.fc31 -> 5.13.2-1.fc31
  qt5-qtsvg 5.12.5-1.fc31 -> 5.13.2-1.fc31
  qt5-qtwayland 5.12.5-2.fc31 -> 5.13.2-2.fc31
  qt5-qtx11extras 5.12.5-1.fc31 -> 5.13.2-1.fc31
  qt5-qtxmlpatterns 5.12.5-1.fc31 -> 5.13.2-1.fc31
[tom@linux2 ~]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/31/x86_64/silverblue
                   Version: 31.20200109.0 (2020-01-09T00:43:29Z)
                BaseCommit: b0790118b35fba1a35bd2c2cfa7db4ab235fa6561ad9fda1a4cda0111a8e1914
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: fedora-workstation-repositories filelight google-chrome mupdf virt-manager

  ostree://fedora:fedora/31/x86_64/silverblue
                   Version: 31.20200107.0 (2020-01-07T01:34:27Z)
                BaseCommit: 3ea3a112a5a5e89559435fecb9377549edbbe93eb44a3888deadaf2c4f995d37
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: fedora-workstation-repositories filelight google-chrome mupdf virt-manager
[tom@linux2 ~]$
