### ISSUE TITLE
Launching containers from inside the toolbox?

### ISSUE THREAD

**Issue by kamalmarhubi** [containers/toolbox#366]
I just tried to run a container via podman and it seems podman hangs on most commands. It may just be that this isn't expected to work. In that case, consider this a request, fully understanding it might be possible with podman / conmon's architecture.

Running Fedora Silverblue 31 on host, Fedora 31 in the toolbox.

On host:
```
$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Fedora 31.20200126.0 (Workstation Edition)"
$ podman --version
podman version 1.7.0
$ conmon --version
conmon version 2.0.9
commit: 7d46f3e7711aa3578488284ae2f98b447658f086
```

In toolbox:
```
$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Fedora 31 (Container Image)"
$ podman --version
podman version 1.7.0
$ conmon --version
conmon version 2.0.10
commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0
```

**Comment by maxwell-k** [comment]
@kamalmarhubi Did you see https://github.com/containers/toolbox/issues/145?

To me it sounds like this would cover what you are asking for.

**Comment by kamalmarhubi** [comment]
Ah yes, it would. I searched for terms like "nested" rather than "shims". Thanks for the pointer!
