### ISSUE TITLE
Simplify naming of toolbox images

### ISSUE THREAD

**Issue by HarryMichal** [containers/toolbox#373]
In the Dockerfiles of toolbox images we set the label name like this: `name="$FGC/$NAME"`. That leads to the fact that the images are called in case of Fedora 31 like this: `f31/fedora-toolbox`. This naming schema is not right in my opinion. All these images are a fedora-toolbox with one difference and that is the version. But version should be handled by the version label.

I propose we change the naming to just: `fedora-toolbox` and use the label to manage versions. We could also start offering Rawhide as `fedora-toolbox:rawhide`.

**Comment by debarshiray** [comment]
> I propose we change the naming to just: fedora-toolbox and
> use the label to manage versions. We could also start offering
> Rawhide as fedora-toolbox:rawhide.

At the least, we shouldn't refer to the images as `rawhide`, until the code knows how to [interpret the string](https://github.com/containers/toolbox/issues/646) `rawhide`.

Beyond that, using `rawhide` to label the images might increase the amount of manual intervention that's necessary when a new Fedora release gets branched.
