### ISSUE TITLE
fedora is hardcoded in contrast to docu

### ISSUE THREAD

**Issue by thkukuk** [containers/toolbox#376]
The docu says:

"By default, Toolbox creates the container using an OCI image called <ID>-toolbox:<VERSION-ID>, where <ID> and <VERSION-ID> are taken from the host's /usr/lib/os-release."

The code says:
if [ "$host_id" = "fedora" ] 2>&3; then
    release_default=$(get_host_version_id)
else
    release_default="30"
fi
toolbox_container_prefix_default="fedora-toolbox"

So if it is not a fedora system, the container image is hardcoded to fedora 30.

**Comment by HarryMichal** [comment]
Hi @thkukuk, Toolbox was formerly known as Fedora Toolbox and was primarily meant to be used only on Fedora-like systems. While it is not said anywhere, it is still the case. In the future we want Toolbox to support other distros but that is still yet to come.

But still thank you for pointing this out! We should update our documentation to clarify this matter.
