### ISSUE TITLE
'toolbox enter' broke after logout and login

### ISSUE THREAD

**Issue by ptomato** [containers/toolbox#378]
On Fedora 31 Silverblue, after I logged out and logged in again, I can no longer start my toolbox:

```
$ toolbox enter
toolbox: failed to start container fedora-toolbox-31
```

Here is the output with `-v`:

```
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user ptomato
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: running on a cgroups v2 host
toolbox: current Podman version is 1.7.0
toolbox: migration not needed: Podman version 1.7.0 is unchanged
toolbox: Fedora generational core is f31
toolbox: base image is fedora-toolbox:31
toolbox: container is fedora-toolbox-31
toolbox: checking if container fedora-toolbox-31 exists
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: starting container fedora-toolbox-31
toolbox: /etc/profile.d/toolbox.sh already mounted in container fedora-toolbox-31
Error: unable to start container "fedora-toolbox-31": container 'b86a7294a2e8d181759d66c1792ed59bac77d4164a773f3247a840f676aacb3a' already exists: OCI runtime error
toolbox: failed to start container fedora-toolbox-31
```

`podman ps` does not show any running containers, and `podman stop fedora-toolbox-31` does find the stopped container, but since it's already stopped it has no effect. `podman start fedora-toolbox-31` gives me the same message about the container already existing.

**Comment by ptomato** [comment]
Rebooting fixes it, so possibly this is https://github.com/containers/libpod/issues/4198

**Comment by HarryMichal** [comment]
Hi @ptomato! I thought this problem should be fixed via Podman update. For now, I'll close this issue. But if you encounter it again, then feel free to reopen it here and also show the output of `podman logs <name-of-your-container>`.
