### ISSUE TITLE
Enable running minikube on Silverblue

### ISSUE THREAD

**Issue by dotellie** [containers/toolbox#379]
I'm not super knowledgeable in podman or libvirt so this issue might be a bit wish-washy while I try to express my wishes somewhat concretely. :sweat_smile: 

For some background, while I don't feel comfortable moving to silverblue yet, I wanted to try moving as much as possible of my environment in my new Fedora installation to be in containers. Now I'm at the point where I want to start a Kubernetes cluster and the only realistic option for me is minikube with KVM.

The problem I'm having is that minikube fails inside a toolbox because it can't find the file containing the IP of the VM which is understandable since no libvirt folders are mounted to the container. Here is the error from minikube:

```
💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: post-start: command runner: ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: getting IP: reading status file: open /var/lib/libvirt/dnsmasq/virbr1.status: no such file or directory
```

Would this be possible to fix in toolbox or should I just revert to installing everything on the host?

**Comment by HarryMichal** [comment]
Hello @dotellie! I never used Kubernetes or libvirt before so I'm just guessing now. Toolbox now bind mounts almost all folders in root inside of a new container (specifically /etc, /dev, /run, /tmp, /usr, /var). They are mounted in `/run/host`. So you can try inside of a container to do something like this: `mount /run/host/var/lib/libvirt /var/lib/libvirt`.

**Comment by debarshiray** [comment]
If you created the toolbox container with Toolbox 0.0.14 or later, then `/run/libvirt` from the host is [bind mounted inside the container](https://github.com/containers/toolbox/pull/257) at the same location.

It might be that you are missing `/var/lib/libvirt`. As @HarryMichal pointed, you can still try to bind mount it yourself and see if that gets you further along the road.

**Comment by debarshiray** [comment]
I learnt from the libvirt developers that this error message comes from `libvirtd`:
```
open /var/lib/libvirt/dnsmasq/virbr1.status: no such file or directory
```

Are you trying to run `libvirtd` inside the container? Or are you running it on the host?

**Comment by dhodyn** [comment]
Faced the same issue and resolved it with the steps,

To run minikube inside on silverblue inside the toolbox,

First ensure that the libvirtd is install and running on the host system. You will have to layer the virtualization packages 

https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/

```
rpm-ostree install virt-install libvirt-daemon-config-network libvirt-daemon-kvm qemu-kvm virt-manager virt-viewer
```
After restart disable polkit and ensure that the service libvirtd is running
```
sudo vi /etc/polkit-1/rules.d/80-libvirt-manage.rules

polkit.addRule(function(action, subject) {
  if (action.id == "org.libvirt.unix.manage" && subject.local && subject.active && subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
});
```
```
systemctl enable --now libvrtd
```

Then inside the toolbox install the **virtualization** group and bind mount the host libvirtd,
```
dnf install @virtualization

sudo mount --bind /run/host/var/lib/libvirt /var/lib/libvirt
```
After this minikube should work

**Comment by debarshiray** [comment]
Thanks for the detailed comment, @dhodyn !

Toolbox [already](https://github.com/containers/toolbox/pull/257) bind mounts `/run/libvirt` from the host. Back then, that was enough to boot a Fedora live ISO in virt-manager.

Do we also need `/var/lib/libvirt`? If so, we could do that.

**Comment by debarshiray** [comment]
Does https://github.com/containers/toolbox/pull/548 help?

**Comment by debarshiray** [comment]
Ping, @dotellie @dhodyn

**Comment by debarshiray** [comment]
I am going to close this now. Please let us know if this lets you run minikube now.
