### ISSUE TITLE
Can't use symlinks to places outside the home

### ISSUE THREAD

**Issue by reclusivebox** [containers/toolbox#382]
I use multiple distributions on my computer but all of them share some folders which I place inside the /home partition and create symlinks to each user folder. Even through those folders are located at the root of the /home partition the users have the necessary permissions to view and modify them. When using toolbox those folders just can't be seen. I mostly understand the design choice, but is there any workaround to use those folders?

**Comment by debarshiray** [comment]
On systems like Fedora Silverblue, by default, the user's home resides under `/var/home`, and `/var` is one of those directories from the host that Toolbox makes available under `/run/host` inside the container.

Therefore, you'd be able to get to your directories at `/run/host/var/home`.

Maybe you could move those folders to `/var` instead?

**Comment by reclusivebox** [comment]
It's good to know there's a way to access my files. But I still don't have that seamless transition between toolbox and systems, the reason I need to share my home folder is that I have other systems (deb-based). There the user home folder resides in `/home`, I would have to reformat a lot of computers changing the shared mountpoint from `/home` to `/var` and maybe change the default home path(I have to test it). If possible don't mark this issue as solved, there's a workraound but it's less than ideal.

**Comment by reclusivebox** [comment]
After some research I found a solution for my problem. But before explaining it let's understand the problem:

- I have a folder `/home/shared-home` in which I keep all the files common for all the distributions I have installed. This folder contains things like my `Documents` folder. Once I install another distribution I delete some folders inside `/home/myusername-distribution` and run the command `ln -s $PWD/* ~` inside the `/home/shared-home`.

- Once I start a toolbox, the container is unable to see my files, all it sees is a bunch of broken symbolic links. That is because the toolbox doesn't map the entire `/home` from the host to the container, only the `/home/myusername-distribution` folder.

I want to be able to use my files inside the container without changing my `/home` structure. Here is the solution I found:

1. Create a samba share to the `/home/shared-home` folder. It is a very painful think to do in fedora because of to selinux, but If you read [this](https://fedoramagazine.org/fedora-32-simple-local-file-sharing-with-samba/), you can do it.

2. Create a `toolbox-home` folder inside `/var` and change some permissions.
   
   ```bash
   sudo mkdir /var/toolbox-home && sudo chmod 777 /var/toolbox-home
   ```

3. Add a `/etc/rc.d/rc.local` file with the following code:
   
   ```bash
   #!/bin/bash
   sleep 10 && mount -t cifs -o username=USERNAME,password=PASSWORD //localshost/public /var/toolbox-home;
   # This code mounts the samba share to a folder I can access inside the container.
   # You need to add a sleep before the code or the share won't be available when you try to mount it.
   ```

4. Give the file permission for execution with `sudo chmod +x /etc/rc.d/rc.local`.

5. Reboot.

6. Create a `/home/shared-home` folder inside the container.

7. Link the contents of the host's samba share to the `/home/shared-home` folder inside the container.
   
   ```bash
   # Run this code inside the container
   ln -s /run/host/var/toolbox-home/* /home/shared-home/
   ```

8. Make coffee to recover the energies, and it's done!
