### ISSUE TITLE
Application is to start outside the toolbox/libpod container environment when executed within

### ISSUE THREAD

**Issue by py0xc3** [containers/toolbox#386]
For testing purposes, I have installed firefox inside toolbox while I have kept another installation outside the container. If firefox already runs outside the container when it is started from within, a new window (not just a tab) is opened. But according to `systemd status`, the window was opened outside the container and so, is started in production environment ([outside.txt](https://github.com/containers/toolbox/files/4274229/outside.txt)), being simply a new process of the already running firefox while toolbox gets a wrong pid (e.g. [1] [2638] output in the toolbox bash, a pid that did not exist in `systemctl status`). If no firefox is running outside the container when started within, it starts properly inside toolbox ([inside.txt](https://github.com/containers/toolbox/files/4274227/inside.txt)) while the returned pid then equals `systemctl status`. 

Still, it works fine with kwrite being already open outside the container when opened inside ([kwrite.txt](https://github.com/containers/toolbox/files/4274228/kwrite.txt)). The problem appears to be related to systemd in conjunction with toolbox, or libpod in general. Maybe it is in conjunction with multi-process applications like firefox at all, or it originates in how processes get started. In the latter case, the problem could be located in /bin/firefox. The documented test was done using Fedora 31 KDE, default installation (KDE spin iso file) without further updates but with toolbox/libpod and dependencies being installed `dnf -y install toolbox`. Behavior equals in native installations and those in QEMU/kvm. The behavior of an updated Fedora 31 KDE (as of yesterday) equals, too.

[inside.txt](https://github.com/containers/toolbox/files/4274227/inside.txt)
[kwrite.txt](https://github.com/containers/toolbox/files/4274228/kwrite.txt)
[outside.txt](https://github.com/containers/toolbox/files/4274229/outside.txt)

**Comment by py0xc3** [comment]
Complementary notice, when trying to use flatpak without any root privileges on a host, toolbox is able to start flatpak processes with root privileges outside the (user privileged) container even if no flatpak process was running outside before. 

Flatpak only works in toolbox if it is installed outside, too. This seems intended due to the limited access to system resources within toolbox. But if no flatpak process is running in systemd when starting toolbox, it is still possible to install flatpak applications in the container. Still, it then starts a flatpak process outside toolbox (asking for the host root password to run it). After that, a flatpak process with root privileges is running in systemd and remains after toolbox closes. Current and future flatpak applications/installations in toolbox then make use of that root process.

**Comment by Jmennius** [comment]
From what I know, Firefox uses either Xorg or DBus to communicate between processes - and X session (the default) is indeed (fully) shared between the toolbox/container and the host (correct me if I am wrong).
Maybe you can try playing with `MOZ_DBUS_REMOTE` see [Martin Stransky's Blog entry on this](https://mastransky.wordpress.com/2020/03/16/wayland-x11-how-to-run-firefox-in-mixed-environment/).

Regarding the flatpak behavior - I want to clarify this for myself too (just starting now).

**Comment by debarshiray** [comment]
More and more applications these days are *single instance* applications. Even if you have multiple separate windows open, they all belong to the same process. This is often implemented using D-Bus, but could be something else too.

Another example, other than Firefox, is [gedit](https://wiki.gnome.org/Apps/Gedit).

Note that toolbox containers share various aspects of the host. eg., the session D-Bus instance, the Wayland and X.org sockets, the PID namespace, etc..

My understanding is that KWrite is not such an application. That's why it's observed to behave differently.

> a new process of the already running firefox while toolbox gets a wrong pid
> (e.g. [1] [2638] output in the toolbox bash, a pid that did not exist in systemctl
> status)

What do you mean by wrong PID? Toolbox containers don't have a separate PID namespace. There's no distinction between PID values inside or outside the container.

**Comment by debarshiray** [comment]
I am inclined to close this issue, because it seems to me that things are working as they should. Feel to re-open or leave a comment if you have reason to believe otherwise.

Either way, thanks for stopping by.

**Comment by py0xc3** [comment]
> More and more applications these days are _single instance_ applications. Even if you have multiple separate windows open, they all belong to the same process. This is often implemented using D-Bus, but could be something else too.
> 

My focus was the unapparent redirection from inside toolbox to instances outside, just wanted to exemplify affected cases.
> What do you mean by wrong PID? Toolbox containers don't have a separate PID namespace. There's no distinction between PID values inside or outside the container.
> 
The PID which is output by the bash terminal inside toolbox does not correspond to "systemctl status" if firefox was already running outside the container when started within. Due to the common namespace I was confused. 

I had alredy started firefox outside toolbox: if I then enter toolbox and run firefox within, I get the following output:
`⬢[user@toolbox ~]$ firefox &
[1] 3610`

This does not equal (host) systemctl which remains the following:
`[root@linux user]# systemctl status | grep irefox`
`           │     ├─3365 /usr/lib64/firefox/firefox`
`           │     ├─3434 /usr/lib64/firefox/firefox ...`
`           │     ├─3506 /usr/lib64/firefox/firefox ...`
`           │     ├─3557 /usr/lib64/firefox/firefox ...`
`           │     ├─3632 /usr/lib64/firefox/firefox ...`
`           │     └─3670 grep --color=auto irefox`

I found out that the firefox process inside toolbox got its PID assigned before systemd solved it into the existing firefox. So, the PID was not wrong but its process was killed shortly after starting.

> But if no flatpak process is running in systemd when starting toolbox, it is still possible to install flatpak applications in the container. Still, it then starts a flatpak process outside toolbox (asking for the host root password to run it).

I assume that flatpak tries to start its service process outside toolbox with host root privileges for comparable reasons. 

You can close the issue, I agree that the behavior seems to be no bug. 

But I suggest to implement a solution for unapparent redirections to the host, at least if the toolbox user redirects to host root. Toolbox is already marketed as containerization and isolation solution for Silverblue. Despite the mutable/immutable background of its use, many users associate containerization and isolation generally with strict security/stability.
