### ISSUE TITLE
is mlocate useful for toolbox?

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#391]
I am not sure how well mlocate works in Toolbox.

Recently when I tried it, I ended up with a 340MB database, maybe because of ~/.local/share/containers?

Are people using it or should we drop it from the default fedora-toolbox packages?

**Comment by maxwell-k** [comment]
I am not using it and would be happy if you dropped it.

**Comment by HarryMichal** [comment]
Until now I didn't know such tool even existed :)

**Comment by juhp** [comment]
> Until now I didn't know such tool even existed :)

Oh it's useful, on Workstation at least.

**Comment by juhp** [comment]
On Silverblue, `locate` only shows me entries for `/etc` and `/boot` basically... so yeah, but maybe the config could be fixed to index /usr, /home, /var, etc also?

**Comment by HarryMichal** [comment]
I believe for now we can close this since @juhp went ahead and [removed](https://src.fedoraproject.org/container/fedora-toolbox/c/bd035973c9f49a96256951f3e2ec454a0973abfd?branch=master) the tool from the `fedora-toolbox` image and considering that there were no reports complaining about the tool being gone.

**Comment by debarshiray** [comment]
I was playing with this a bit today.

> Recently when I tried it, I ended up with a 340MB database, maybe
> because of ~/.local/share/containers?

How do the sizes of `/var/lib/mlocate/mlocate.db` on the host and inside the container compare?

In my case on a Fedora Workstation system, they were 101M and 100M respectively. Silverblue doesn't have a working `mlocate` on the host, so the comparison there is less meaningful.

> See also https://bugzilla.redhat.com/show_bug.cgi?id=906591

Strangely enough, having `PRUNE_BIND_MOUNTS = "yes"` doesn't seem to prevent `updatedb` from indexing all the bind mounts inside a Toolbox container. eg., `locate Downloads` or `locate pam_xauth.so` returns results from locations that are known to be bind mounts.
