### ISSUE TITLE
sudo gives error in toolbox

### ISSUE THREAD

**Issue by sbluman** [containers/toolbox#392]
When I open a toolbox container, I get an error with every `sudo` command:

``` bash
⬢[me@toolbox ~]$ sudo echo
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
bash: /usr/libexec/vte-urlencode-cwd: No such file or directory
```

**Comment by sbluman** [comment]
This does not seem to impact any functionality, though.
``` bash
sudo dnf install -y ...
```
works fine for any package I have tried.

**Comment by juhp** [comment]
This is a sudo issue and should be fixed in upstream sudo now: see sudo-project/sudo#42

**Comment by debarshiray** [comment]
Yes, as far as I can tell, this is fixed.

Thanks for upstreaming the bug to sudo, @juhp ! Much appreciated.
