### ISSUE TITLE
`VERSION` environment variable is too generic

### ISSUE THREAD

**Issue by srbaker** [containers/toolbox#406]
Hello,

My toolbox has an environment variable `VERSION`, but this conflicts with tools. In particular, it causes me issues with Ruby on Rails database migrations.

Can I suggest we change this to TOOLBOX_CONTAINER_VERSION or something like that? I'm happy to do the work, I just want someone else to tell me what it should be called instead.

Thanks!

**Comment by srbaker** [comment]
Bump. Any opinions on this?

**Comment by HarryMichal** [comment]
Hi @srbaker! This is more of a question for @juhp and @debarshiray. I just know that Fedora images (respectively their Dockerfiles) have to follow [guidelines](https://docs.fedoraproject.org/en-US/containers/guidelines/creation/). There is a section for [versioning](https://docs.fedoraproject.org/en-US/containers/guidelines/creation/#_versioning) that seems to require the usage of the `VERSION` environmental variable.

**Comment by debarshiray** [comment]
Duplicate of #188
