### ISSUE TITLE
Should verify that gdbus is available

### ISSUE THREAD

**Issue by zerodogg** [containers/toolbox#407]
Right now `toolbox` needs `gdbus` to work. But it doesn't check that the command is available before trying to call it so it outputs a somewhat unhelpful `toolbox: failed to call org.freedesktop.Flatpak.SessionHelper.RequestSession` if `gdbus` isn't available, which led me to believe there was something wrong with the service rather than toolbox not being able to call dbus at all.

**Comment by debarshiray** [comment]
Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal , and the Go version doesn't require `gdbus(1)` to talk D-Bus.

However, I am curious how you managed to not have `gdbus(1)` on the system. On Fedora, it's part of the `glib2` RPM package, and it's pretty hard to boot a machine without that package.
