### ISSUE TITLE
No keyboard input if typing before the shell starts

### ISSUE THREAD

**Issue by srbaker** [containers/toolbox#409]
Sometimes I type `toolbox enter` and then get over-excited and start typing the next command before the shell prompt has loaded.

When I do this, I get absolutely no keyboard response from inside the toolbox, and I have to kill the terminal window and start over.

**Comment by maxwell-k** [comment]
@srbaker, to me, what you describe sounds very similar to issue #310. Do you see any differences?

**Comment by srbaker** [comment]
It is identical. I'm really sorry for not seeing this, I didn't look thoroughly enough.

Thanks for your response!
