### ISSUE TITLE
Usage on Fedora CoreOS

### ISSUE THREAD

**Issue by dghubble** [containers/toolbox#411]
Hi folks :wave:. Fedora CoreOS looks to be shipping `toolbox` from the v0.0.18 RPM and I was looking to use it.

```
$ toolbox                                                                                                                                                       
toolbox: TOOLBOX_PATH not set                                                                                                                                                                 
$ export TOOLBOX_PATH=/usr/bin/toolbox
$ toolbox
toolbox: missing command

These are some common commands:
create    Create a new toolbox container
enter     Enter an existing toolbox container
list      List all existing toolbox containers and images

Try 'toolbox --help' for more information.
$ toolbox --help
toolbox: this is not a toolbox container
$ toolbox create
toolbox: this is not a toolbox container
```

Are there requirements/assumptions not captured in the RPM I need to setup/satisfy to use toolbox? I'm not sure if this is a packaging issue here or an integration issue on Fedora CoreOS.

### Versions

```
rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200323.3.2 (2020-04-08T14:30:14Z)
                    Commit: 9b322b9cead87ebf80881b75560e481b6e5a26966814b01bf0c12b61fa363708
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

```
Name        : toolbox
Version     : 0.0.18
Release     : 1.fc31
Architecture: noarch
Install Date: Wed 08 Apr 2020 02:28:06 PM UTC
Group       : Unspecified
Size        : 119658
License     : ASL 2.0
Signature   : RSA/SHA256, Tue 14 Jan 2020 04:01:34 PM UTC, Key ID 50cb390b3c3359c4
Source RPM  : toolbox-0.0.18-1.fc31.src.rpm
Build Date  : Tue 14 Jan 2020 03:56:29 PM UTC
Build Host  : buildvm-06.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/containers/toolbox
Bug URL     : https://bugz.fedoraproject.org/toolbox
Summary     : Unprivileged development environment
```

Related: https://github.com/coreos/fedora-coreos-tracker/issues/458

**Comment by debarshiray** [comment]
> Hi folks wave. Fedora CoreOS looks to be shipping `toolbox`
> from the v0.0.18 RPM and I was looking to use it.

Hello, hello! Sorry for the delayed response.

> ```
> $ toolbox                                                                                                                                                       
> toolbox: TOOLBOX_PATH not set                                                                                                                                                                 

Looks like you were trying to use `toolbox(1)` when sitting inside a container. This is only meant to work with containers created with Toolbox, and those should the TOOLBOX_PATH environment variable defined.

The error that you saw is a sanity check, which should never fail unless something funky is going on. :)

> Try 'toolbox --help' for more information.
> $ toolbox --help
> toolbox: this is not a toolbox container
> $ toolbox create
> toolbox: this is not a toolbox container
> ```

These seem to match what my thoughts above.

> Are there requirements/assumptions not captured in the RPM I need
> to setup/satisfy to use toolbox? I'm not sure if this is a packaging issue
> here or an integration issue on Fedora CoreOS.

Umm... the RPM should be self-contained.

Thanks for playing with Toolbox. :)

**Comment by dghubble** [comment]
> Looks like you were trying to use toolbox(1) when sitting inside a container

At the time, these examples were from running the commands on a Fedora CoreOS host itself, not inside another container. Though perhaps the message came from within a container.

I've since just found podman to be good enough on its own, so I'm ok with closing this out. Don't have a user case anymore.

**Comment by debarshiray** [comment]
> > Looks like you were trying to use toolbox(1) when sitting inside a container
> 
> At the time, these examples were from running the commands on a Fedora
> CoreOS host itself, not inside another container. Though perhaps the message
> came from within a container which quickly exited.

Whatever it was, it had `/run/.containerenv`.
