### ISSUE TITLE
Doesn't work from `/tmp`

### ISSUE THREAD

**Issue by abitrolly** [containers/toolbox#418]
```
$ cd /tmp
$ toolbox -v enter
...
toolbox: looking for /bin/zsh in container fedora-toolbox-31
Error: exec session exited with non-zero exit code 1: OCI runtime error
toolbox: /bin/zsh not found in fedora-toolbox-31; using /bin/bash instead
toolbox: running in container fedora-toolbox-31:
toolbox: /bin/bash
toolbox: -l
Error: chdir: No such file or directory: OCI runtime command not found error
```

**Comment by HarryMichal** [comment]
Hi @abitrolly! This is expected behaviour that is not handled correctly. It was already reported in #369.

If you need to access `/tmp` inside of a Toolbox container you will find it under `/run/host/tmp`.

**Comment by debarshiray** [comment]
I wonder if this might have been some other issue.

Toolbox containers do have a `/tmp` directory, so this cannot be the same as #369.

**Comment by abitrolly** [comment]
From the user perspective getting mounted `/tmp` inside toolbox is not the same as receiving error message. The proper solution is to find that `/tmp` that user wants to containerize is available as `/run/host/tmp` and mount it as `/tmp` inside container. Maybe showing a message about what is going on behind the scenes.
