### ISSUE TITLE
Does/can toolbox use a CRIU-enabled Podman?

### ISSUE THREAD

**Issue by elimisteve** [containers/toolbox#421]
Checkpointing containers so they can maintain their exact state between host reboots is really powerful!

**Comment by debarshiray** [comment]
`podman container checkpoint` and `podman container restore` should already work.

If it's across reboots, then you might have to start `/usr/libexec/flatpak-session-helper` manually. However, we want to move away from `/usr/libexec/flatpak-session-helper` so this requirement might go away soon.

**Comment by debarshiray** [comment]
I am tentatively closing this, since I am not sure if this was just a question or if there was a more concrete use-case behind it.

**Comment by debarshiray** [comment]
Thanks for playing with Toolbox! :)
