### ISSUE TITLE
Can't start any containers

### ISSUE THREAD

**Issue by gainhad** [containers/toolbox#422]
Not sure what's happening, but I am now unable to start any containers. The output from `toolbox -v enter` is:
```
toolbox: running as real user ID 1000
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user hadley
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: running on a cgroups v2 host
toolbox: current Podman version is 1.9.0
toolbox: migration not needed: Podman version 1.9.0 is unchanged
toolbox: Fedora generational core is f31
toolbox: base image is fedora-toolbox:31
toolbox: container is fedora-toolbox-31
toolbox: checking if container fedora-toolbox-31 exists
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: starting container fedora-toolbox-31
toolbox: /etc/profile.d/toolbox.sh already mounted in container fedora-toolbox-31
Error: unable to start container "fedora-toolbox-31": sd-bus call: File exists: OCI runtime error
toolbox: failed to start container fedora-toolbox-31
```

Any ideas?

**Comment by HarryMichal** [comment]
Hi @gainhad! Could you, please, post here the output of `podman logs fedora-toolbox-31` after trying to enter it?

**Comment by gainhad** [comment]
@HarryMichal No logs are output from `podman logs` using either the name, or the id of the container... Not sure what's going on. `toolbox list` shows the container, but `podman ps` does not.

Thanks for the help!

**Comment by HarryMichal** [comment]
`podman ps` only shows running containers. To show all containers you need to run `podman ps -a`. `toolbox list` shows all toolbox containers regardless of the state their in.

Could you try to run `podman start fedora-toolbix-31`? Also how old is the container. By that I mean if it is a new container or one that you created some time ago and have been using it for some time already.

**Comment by gainhad** [comment]
Running `podman start fedora-toolbox-31` gives the same output:
```
Error: unable to start container "fedora-toolbox-31": sd-bus call: File exists: OCI runtime error
```
Running `podman logs fedora-toolbox-31` after also gives no output.

The container is new. Just created it with toolbox a couple days ago.
