### ISSUE TITLE
sudo only works in some containers

### ISSUE THREAD

**Issue by tompreston** [containers/toolbox#424]
I can use sudo in fedora:32 and fedora:31:
```bash
~$ toolbox create
~$ toolbox enter
tpreston@toolbox:~$ sudo whoami
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
root

~$ toolbox create -i fedora-toolbox:31
~$ toolbox enter -c fedora-toolbox-31
tpreston@toolbox:~$ sudo whoami
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
root
```

but not buildstream:latest (which is based on fedora:31):
```bash
~$ toolbox create -i docker.io/buildstream/buildstream:latest
~$ toolbox enter -c buildstream-latest
tpreston@toolbox:~$ sudo whoami

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for tpreston:
Sorry, try again.
[sudo] password for tpreston:
Sorry, try again.
[sudo] password for tpreston:
sudo: 3 incorrect password attempts
```

Both are Fedora based images, and they don't seem to do anything special with users or sudo:
- Fedora 32 https://github.com/containers/toolbox/blob/master/images/fedora/f32/Dockerfile
- BuildStream https://gitlab.com/BuildStream/buildstream-docker-images/blob/master/buildstream/latest.Dockerfile

What gives?

**Comment by HarryMichal** [comment]
Hi @tompreston! `fedora != fedora-toolbox`. Toolbox relies on its own images (Dockerfiles in the `images` directory; images hosted on https://registry.fedoraproject.org/). Most distro images are stripped of many things to reduce their size (including `sudo` groups). `buildstream` does the same thing.
