### ISSUE TITLE
Nginx in toolbox, problem to start

### ISSUE THREAD

**Issue by Javierkaiser** [containers/toolbox#425]
Hi, I'm new with toolbox (and containers) and I'm trying to set my development tools there.
I'm using Fedora 32 and the toolbox image is fedora-toolbox:32.
I managed to set most of my tools, no problem there.
I can't get Nginx to start. I installed it  normally, but when I do "sudo nginx" I get this message: 
**nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)**

My instinct tells me to try running toolbox as root and reinstall everything there, I did not try, I asking for guidance first.
Thanks.

**Comment by junjieyuan** [comment]
The podman container created by toolbox shares the network with the host. In other words, the container uses the port of the host (container 0-> host 0, 1-> 1, ... 80-> 80 ...), and the port below 1024 is a privileged port (may be 1024, there are also It may be other numbers, which I cannot remember), ordinary users cannot directly use them.

You can use the root user of the host machine to run the container, or change the port to be monitored (such as 8080) in the nginx configuration file. If you really need to allow ordinary users to use privileged ports, you can search for "authbind" or other similar programs.

https://github.com/containers/toolbox/blob/b4337d4f8632ce4ac31b889a61e9465404a6921c/toolbox#L1087

**Comment by Javierkaiser** [comment]
Thank you good junjieyuan!
I was so focused on the toolbox that I totally forgot to try that.
Thanks!.
