### ISSUE TITLE
An extremely specific user case: toolbox as fish shell inside flatpak FOSS VSCode

### ISSUE THREAD

**Issue by Yajo** [containers/toolbox#426]
I was going to open a wide amount of issues in some projects, but I'm thinking that maybe exposing my final use case here would be the best, because although it's very specific, I think it can be common enough (don't ask me for statistics, though) so as to be a stop point for whoever, like me, wants to switch Fedora Silverblue + Flatpak + toolbox + vscode and finds out it simply doesn't work.

You don't really need Silverblue to test this, but it's a use case where it's more important. You can do it with normal Fedora 32.

STR:

1. Install https://flathub.org/apps/details/com.visualstudio.code.oss
1. Install toolbox
1. `toolbox create`
1. `toolbox enter`
1. Inside toolbox: `sudo dnf -y install fish`
1. Configure vscode like this: https://github.com/flatpak/flatpak/issues/3285#issuecomment-621692422
1. Open inline term in vscode.
1. Execute `fish`
1. Try to use fish as usual (prompt, completions...). It works very bad, possibly due to https://github.com/containers/toolbox/issues/29.
1. Try to configure fish running `fish_config`: no browser opens, cannot configure it...

Notice that bash shell itself also doesn't work fine (e.g. you cannot delete a character once written), it's just that with [Fish](http://fishshell.com/) less things work fine.

Many stop points as of today. This must become easier...

Sorry for being so specific, I guess you can just close this, but IMHO this use case should be fixed.

**Comment by djlawhead** [comment]
Have you tried installing VS Code from the official [Microsoft repos](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions) through `dnf`? That path works fine for me. Right now I'm struggling with visual artefacts in any Electron application, as well as Google Chrome. But that has been happening on Silverblue, not the regular Fedora Workstation. VS Code, however, runs fine. As long as there aren't any animations.

**Comment by Yajo** [comment]
Yes, I am currently using that solution.

**Comment by debarshiray** [comment]
I think this is unrelated to https://github.com/containers/toolbox/issues/29 because the `TERM` environment variable is on the list of things that are propaged across both the `podman` and `flatpak-spawn` boundaries.

One important thing here is whether the misbehaving shell has a [controlling terminal](https://www.gnu.org/software/libc/manual/html_node/Controlling-Terminal.html)l. Does it?

**Comment by Yajo** [comment]
I don't know about the controlling terminal, but @nahuelwexd found a viable solution in https://github.com/flatpak/flatpak/issues/3285#issuecomment-632977352. I guess this can be closed.
