### ISSUE TITLE
Interactive shell hangs when typing before prompt

### ISSUE THREAD

**Issue by shayaviv** [containers/toolbox#431]
When running either `toolbox enter` or `toolbox run bash` and then _immediately_ pressing some keys, an interactive shell starts and:
* Does not respond to keyboard strokes
* Does not respond when I hit `CTRL-c` / `CTRL-d`
* Only closes when I hit `CTRL-p CTRL-q`, after some noticeable delay

If I make sure not press any key until the prompt `⬢[shayaviv@toolbox ~]$` shows up, then everything is working just fine.

My environment:
* `podman-1.9.1-1.fc32`
* `toolbox-0.0.18-2.fc32`
* Fedora Workstation 32

I tested this on Bourne Shell and Fish Shell, and also in `gnome-terminal` and a TTY console. The hang occurs on all of these.

**Comment by shayaviv** [comment]
After experimenting some more, I can recreate the problem with `podman exec`. I will move this issue to `podman`.

**Comment by HarryMichal** [comment]
Hi @shayaviv, this is a duplicate of #310. It is already being tracked upstream (https://github.com/containers/libpod/issues/4397)
