### ISSUE TITLE
host passthrough not working

### ISSUE THREAD

**Issue by barnscott** [containers/toolbox#433]
Using fedora silverblue 32.

README describes Host Debugging features including passing rpm-ostree to host. This feature did not work for me: simply says command not found.

Please let me know if this is a bug, or if this feature has not yet been implemented. 

From what I see, some other commands can passthrough. Ie, "htop" shows my user processes that exist on host. For my benefit, where can I find additional docs or recoded talks on how this works: it's amazing.

**Comment by HarryMichal** [comment]
Hi @barnscott! This feature is not implemented (#145), yet. Toolbox uses Podman's option `--pid host` when creating containers causing it to see processes running on the host, so in fact, `htop` is not ran on the host but rather in the container.

**Comment by HarryMichal** [comment]
For now, you can use the steps described in #145 to make this functionality work but you'll have to wait a bit more before this is handled manually by Toolbox.
