### ISSUE TITLE
Fixing tests - Zuul doesn't install requirements?

### ISSUE THREAD

**Issue by abitrolly** [containers/toolbox#447]
I looking why tests fail. Zuul reports that `go` is not installed. The installation is directed by the Ansible playbook.

https://github.com/containers/toolbox/blob/dcaf06a950326ac0b7d688dfde89e4b4b67a72b8/playbooks/fedora-30/setup-rpm-env.yaml#L4-L16

And while there is evidence that `setup-rpm-env.yaml` is executed, I do not see the `Install requirements` task is being run.

https://softwarefactory-project.io/zuul/t/local/build/32491e685f404bc690dff4d58292294a/console

**Comment by HarryMichal** [comment]
Hi @abitrolly, as I mentioned in your PR (#446), fixing of tests is already tracked in #438.

**Comment by abitrolly** [comment]
That still doesn't explain why Zuul doesn't run this task.

**Comment by HarryMichal** [comment]
Yes, that is true. The task is not listed in the 'Console'. Interesting. The task itself is run if you look in the raw/json logs. This must be some kind of bug in Zuul itself. I'll report it on the IRC channel (#freenode/zuul).
