### ISSUE TITLE
Running in docker

### ISSUE THREAD

**Issue by salesgroup** [containers/toolbox#457]
Is it possible to run toolbox with docker (instead of podman) ?

whenever I tried, this error appeared:
toolbox: failed to start container fedora-toolbox-31

**Comment by josmardias** [comment]
Readme says that only podman is supported

**Comment by HarryMichal** [comment]
It could be done manually by patching the source code (replacing `podman` with `docker`) but as @josmardias said, this is a `Non goal`.
