### ISSUE TITLE
libudev in toolbox fails to retreive data set by udev rules on the host

### ISSUE THREAD

**Issue by gkiagia** [containers/toolbox#468]
I am using a toolbox to develop pipewire, which uses libudev to enumerate alsa and v4l2 devices. While device enumration works fine in the toolbox, the devices seem to be missing some properties that are normally present on the host...

After some digging I realized that these properies are set by udev rules on the host and stored in the udev database. When enumerating, libudev uses `/run/udev/data` to access them.

In the container, this directory is available in `/run/host/run/udev/data` instead. To work this around, I added a symlink in the container: `ln -s /run/host/run/udev /run/udev`

**Comment by HarryMichal** [comment]
Hi @gkiagia! This looks like an easy fix. If @debarshiray doesn't have any objections, I'd add this symlink into the default setup.

**Comment by debarshiray** [comment]
Thanks for your work on Pipewire, @gkiagia ;)

It's been many years since I last programmed against udev, so apologies for what might be stupid questions.

> I am using a toolbox to develop pipewire, which uses libudev to
> enumerate alsa and v4l2 devices. While device enumration works
> fine in the toolbox, the devices seem to be missing some properties
> that are normally present on the host...
> 
> After some digging I realized that these properies are set by udev
> rules on the host and stored in the udev database. When enumerating,
> libudev uses `/run/udev/data` to access them.

How is `libudev` even enumerating the devices? Is it directly looking at `/dev` inside the container?

I am asking because I am wondering if we need to make more things available. For example, the udev control socket at `/run/udev/control`, but that's only accessible by UID=0 on the host, so won't work inside the container anyway.

**Comment by gkiagia** [comment]
Hi @debarshiray,

I am not very familiar with udev either. Looking at strace output while running pipewire, I can see that it gathers data from `/sys` and from `/run/udev/data`. Obviously, access to `/dev` is also required for the application (pipewire in this case) to be able to open a device, but this works already.

Afaik, the control socket is only needed to control the daemon (`udevadm`) and not to gather information. In addition, all signals from udev are dispatched to applications through an `AF_NETLINK` socket, which works since the network namespace is shared.

**Comment by debarshiray** [comment]
Thanks for confirming that.

Does https://github.com/containers/toolbox/pull/491 work? You might have to create a new container, unless you place the binary you built at `/usr/bin/toolbox`, in which case `podman stop ...` and then `toolbox enter` should be enough.

Toolbox already bind mounts `/dev` from the host. I was wondering if the `/sys` inside the container was working well for you. Seems like it is.

**Comment by debarshiray** [comment]
Ping, @gkiagia

**Comment by gkiagia** [comment]
Yes, it works. Sorry for the delay, I somehow missed your previous comment.
`/sys` is indeed mounted and working as expected.

**Comment by debarshiray** [comment]
> Yes, it works. Sorry for the delay, I somehow missed your previous comment.
> `/sys` is indeed mounted and working as expected.

Thanks for the confirmation!
