### ISSUE TITLE
Spinner doesn't stop after hitting ctrl+c

### ISSUE THREAD

**Issue by fbruetting** [containers/toolbox#48]
v0.0.4-1.fc29

`Ctrl + C` doesn’t work, it continues running in the background.

**Comment by HarryMichal** [comment]
Yes, this is an issue with the current shell script. The issue should be gone in the upcoming version written in Go.

**Comment by debarshiray** [comment]
I am assuming that this issue about the spinner not stopping after a `ctrl+c`.

Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal , and the Go version doesn't have this problem.
