### ISSUE TITLE
toolbox 0.0.92 - unify toolbox create command with blog post

### ISSUE THREAD

**Issue by charafau** [containers/toolbox#489]
Hello! I saw HarryMichal's blog post about new version of podman rewritten in go - thank you for improving toolbox!
I compiled binary myself on Silverblue and one thing occurred to me. 
In blog post ( http://harrymichal.undo.it/posts/2020/wheres-toolbox-0.0.9x-update/ ) I got an impression that toolbox commands got unified with podman and new (preferred) way to enter container is 

`toolbox enter <container-name>` 

but when I create new container message returned from toolbox displays old way of entering with `--container` parameter:

```
~ ➜ toolbox create my-container
Created container: my-container
Enter with: toolbox enter --container my-container
```
Not sure if that's intended or not so I decided to create this simple to fix issue, can create PR if someone decides that it's preferred way.

Thanks

**Comment by HarryMichal** [comment]
Hi @charafau! Thank you for reading the blog post and trying out Toolbox.

The `toolbox enter <container-name>` command works it is just not shown in the "hint" after creating a container. I think this could be called an oversight.

**Comment by charafau** [comment]
thank you for fast answer - don't get me wrong, I know the command works, was just thinking which one should be "embraced" as output message with parameter or without :)

**Comment by debarshiray** [comment]
Thanks for catching this!

We kept advertising the old syntax in the user interface to retain compatibility with the POSIX shell implementation of Toolbox. Now that the Go implementation has proved to be robust and is being used widely, I agree that we should switch these things over.
