### ISSUE TITLE
Providing `--version` information

### ISSUE THREAD

**Issue by fbruetting** [containers/toolbox#49]
Is missing in v0.0.4-1.fc29

**Comment by debarshiray** [comment]
A `--version` flag is a reasonable thing to expect, and one would expect it to be easy. However, I can't think of a way to do this that:

- Doesn't require *building* the final shell script from a `toolbox.in` to fill in the version number.

- Doesn't require installing a second snippet with the version information that's sourced by the main script at run-time.

As archaic as shell scripts are, the ability to have a single self-contained file that can be run without an intermediate step is one of the more endearing aspects of it. It would be nice to not lose that.

Or maybe I am not being imaginative enough? :/

**Comment by fbruetting** [comment]
I neither use Meson nor sh scripts, but can’t this be solved by an environment variable defined at the top, and maybe be fed via Meson?

**Comment by debarshiray** [comment]
Umm... who will feed them in? Note that it has to work both for the (a) running straight out of Git or `./toolbox` case, (b) built and installed, possibly via a distribution package, case.

**Comment by fbruetting** [comment]
I think I would just add constants to that scripts. But I must say that I do not have an idea of shell scripts at all. :/

**Comment by HarryPhoon** [comment]
I went through documentation of Meson and there is a way to set configuration options (the link is [here](https://mesonbuild.com/Configuration.html)). But the expected way to use this mechanic is to feed it an input config and then use the created config. If we want to use this we need to make toolbox.sh read this kind of data from a separate config file. Do we want that??

**Comment by debarshiray** [comment]
> I went through documentation of Meson and there is a way to set
> configuration options (the link is [here](https://mesonbuild.com/Configuration.html)).
> But the expected way to use this mechanic is to feed it an input
> config and then use the created config. If we want to use this we
> need to make toolbox.sh read this kind of data from a separate config
> file. Do we want that??

That would require having to *build* the final shell script from a `toolbox.in`, wouldn't it?

I think this is another of those things that are best addressed during the rewrite in Go, when we'd have to build the final binary from the sources anyway. The only positive aspect of a shell script is that it's self-contained and can be run straight out of the Git tree, without having to build it and so on. Let's not lose that.

**Comment by debarshiray** [comment]
Toolbox has now been [rewritten in Go](https://github.com/containers/toolbox/pull/318) by @HarryMichal , and the Go version offers a `--version` flag.
