### ISSUE TITLE
toolbox becomes unusably slow when creating lots of small files in /tmp

### ISSUE THREAD

**Issue by hferreiro** [containers/toolbox#513]
I have a process that from time to time creates lots of log files on /tmp. In the order of tens or hundreds of thousands. When this happens, fuse-overlayfs uses 100% of the CPU and everything works very slowly.

Trying to remove /tmp contents is particularly slow. Restarting the container doesn't help.

**Comment by A6GibKm** [comment]
Have you tested this in other folders inside the sandbox or folder in your home? As far as I know, rootless podman is very slow when it comes to file IO in general.

**Comment by debarshiray** [comment]
Can you reproduce this with:
```
$ podman run --rm -it --env=TERM=$TERM registry.fedoraproject.org/f31/fedora-toolbox:31 /bin/bash
```

`/tmp` is mounted as a `fuse-overlayfs`, both in Toolbox containers and in stock Podman containers, so I'd say this needs to be moved to `fuse-overlayfs`. Although, I do wonder why Podman isn't mounting a `tmpfs` on `/tmp`.

@giuseppe ?

**Comment by giuseppe** [comment]
this is definitely a fuse-overlayfs issue.  Even if we manage to make it faster, dealing with so many files will always be slow using a FUSE file system.

Would it be possible to mount a tmpfs on `/tmp`?  I think that is the best solution.

**Comment by debarshiray** [comment]
> Would it be possible to mount a tmpfs on /tmp?
> I think that is the best solution.

Yes, I think so too. I was wondering if that's something Podman should do by default, or whether it's better if Toolbox explicitly did it. I am fine with either alternative.

Thanks for taking a look, @giuseppe

**Comment by giuseppe** [comment]
> > 
> 
> Yes, I think so too. I was wondering if that's something Podman should do by default, or whether it's better if Toolbox explicitly did it. I am fine with either alternative.

I'd also prefer we had a tmpfs by default, but I think we are just following what Docker does.

**Comment by hferreiro** [comment]
Yes, I confirm this is an issue with podman too. What's interesting is what's keeping fuse-overlayfs busy once the files are created. I'm trying to reproduce the issue again to find out about that.

**Comment by debarshiray** [comment]
> Yes, I confirm this is an issue with podman too. What's interesting
> is what's keeping fuse-overlayfs busy once the files are created. I'm
> trying to reproduce the issue again to find out about that.

Thank you for digging into it! Feel free to file an issue against [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) if you find anything, and CC me.
