### ISSUE TITLE
Missing fedora-toolbox image for aarch64

### ISSUE THREAD

**Issue by barnscott** [containers/toolbox#528]
**Is your feature request related to a problem? Please describe.**
Currently, toolbox fails to run on my Pinebook Pro running fedora. It appears that an arm image is not available:
```
$ toolbox create -v
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user barn 
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Toolbox config directory is /home/barn/.config/toolbox 
DEBU Current Podman version is 2.0.4              
DEBU Old Podman version is 2.0.4                  
DEBU Migration not needed: Podman version 2.0.4 is unchanged 
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'fedora-toolbox-32'               
DEBU Image: 'fedora-toolbox:32'                   
DEBU Release: '32'                                
DEBU Checking if container fedora-toolbox-32 already exists 
DEBU Looking for image fedora-toolbox:32          
DEBU Looking for image localhost/fedora-toolbox:32 
DEBU Looking for image registry.fedoraproject.org/f32/fedora-toolbox:32 
Image required to create toolbox container.
Download registry.fedoraproject.org/f32/fedora-toolbox:32 (500MB)? [y/N]: y
DEBU Pulling image registry.fedoraproject.org/f32/fedora-toolbox:32 
Trying to pull registry.fedoraproject.org/f32/fedora-toolbox:32...
  no image found in manifest list for architecture arm64, variant "v8", OS linux
Error: unable to pull registry.fedoraproject.org/f32/fedora-toolbox:32: Error choosing an image from manifest list docker://registry.fedoraproject.org/f32/fedora-toolbox:32: no image found in manifest list for architecture arm64, variant "v8", OS linux
Error: failed to pull image registry.fedoraproject.org/f32/fedora-toolbox:32
```

**Describe the solution you'd like**
A configured arm image, or workaround steps.

**Describe alternatives you've considered**
I assume there is a workaround in which i manually define a container, but it would be ideal if it works out of the box.

**Additional context**
Add any other context or screenshots about the feature request here. If a different tool has the functionality you're requesting, share it here.

**Comment by debarshiray** [comment]
Wow! Pinebook Pro - that's cool.

Unfortunately, this is something you will have to take up with Fedora infrastructure. Currently Fedora only offers OCI images for x86_64.

We previously had a request for [ppc64le](https://github.com/containers/toolbox/issues/454) images, and I have a feeling that it might not happen overnight.

**Comment by debarshiray** [comment]
The Fedora OCI infrastructure recently added support for aarch64 and @HarryMichal has now built the `fedora-toolbox` images for it.

It will take some time for the images to propagate to the main registry at `registry.fedoraproject.org`. Until then you can try:
```
$ toolbox create --image candidate-registry.fedoraproject.org/f33/fedora-toolbox:latest
```
