### ISSUE TITLE
cockpit instalation fedora server 32

### ISSUE THREAD

**Issue by angelo0807** [containers/toolbox#530]
I'm trying to use cockpit on my fedora server, but when I'm going to put the IP address on the URL with the port 9090 it never appears, also changing the IP finding a solution now the issue is that it appears always using DNF upgrade- curl 6could resolve hostname.
what I have to do, thanks

**Comment by KlausDevWalker** [comment]
Does this bug happen when you're using Toolbox?

**Comment by angelo0807** [comment]
thanks it was other issue , i fixed it

**Comment by KlausDevWalker** [comment]
So please close this issue :D
