### ISSUE TITLE
Define hostname when creating toolbox

### ISSUE THREAD

**Issue by mvalahtv** [containers/toolbox#563]
**Is your feature request related to a problem? Please describe.**
I would like to have multiple toolboxes so it would be nice if we can define hostname instead of `toolbox`.

**Describe the solution you'd like**
 It can be done via
```
toolbox create -h mytoolbox
```

**Comment by meeas** [comment]
Related to this, can we also add a method to add a hostname after a toolbox has been created?  I assume we can use podman to add a hostname to a running toolbox, but I suspect that the hostname will not persist trough reboots.

**Comment by debarshiray** [comment]
https://github.com/containers/toolbox/issues/969 has some good ideas on how to chose a better default for the container's host name.

One problem with setting the host name through podman create --host ..., like we do today, is that any attempt to change the hostname later doesn't persist across a container restart. This seems somewhat important, if we want to change the container's host name to uniquely identify them.

Of course, users can hack this up using their shell start-up scripts, but it will be good to come up with a less barbaric solution.  :)

One option could be to leverage the `toolbox init-container` entry point to repeatedly set the intended host name on container start-up.

**Comment by debarshiray** [comment]
Let's first try to improve the default hostname that gets chosen for a Toolbx container before trying to come up with ways to customize it.

I don't want to offer users a way to choose a custom name when creating a Toolbx container, until we have figured out a way in which that name can be modified afterwards.  If a person wants custom names for their containers, it's not a stretch to imagine that they might want to change the name afterwards, and as I mentioned above, it's tricky to change the name later.

I do understand why users want to customize the names, though, and I do accept it as a reasonable thing to do.  It's just that we haven't figured out a way to do that properly.

Improving the default name is still going to be an improvement, and we have a clear way ahead, so let's focus on that first.  Baby steps.  :)

**Comment by debarshiray** [comment]
I am going to close this issue in favour of https://github.com/containers/toolbox/issues/969 so that the list of open issues doesn't balloon out of control, and continues to roughly reflect the items that are on the current to-do list. However, it will still be around for future reference.

**Comment by debarshiray** [comment]
> I don't want to offer users a way to choose a custom name when creating a
> Toolbx container, until we have figured out a way in which that name can be
> modified afterwards. If a person wants custom names for their containers,
> it's not a stretch to imagine that they might want to change the name
> afterwards, and as I mentioned above, it's tricky to change the name later.

The [second comment](https://github.com/containers/toolbox/issues/563#issuecomment-1146456319) on this issue is exactly what I was talking about.  :)
