### ISSUE TITLE
[RFE] Add sound support

### ISSUE THREAD

**Issue by AsciiWolf** [containers/toolbox#58]
Fedora Toolbox already supports GUI applications. It would be great if it could also have sound (PulseAudio or ALSA) support. :-)

**Comment by memnoth** [comment]
This might work, ``--volume /dev/snd:/dev/snd``.

Referred to this link, https://github.com/osrf/docker_images/issues/21#issuecomment-239419475

**Comment by memnoth** [comment]
With the mounting of ``/dev/snd``, an application inside container doesn't work well with the sound if it works on the host at the same time.

Errors of mpv
```
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
[ao/alsa] Playback open error: Device or resource busy
[ao/oss] Can't open audio device /dev/dsp: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ao/jack] cannot open server
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
[ao/sdl] could not open audio: ALSA: Couldn't open audio device: Device or resource busy
[ao] Failed to initialize audio driver 'sdl'
Could not open/initialize audio device -> no sound.
```

**Comment by tosmi** [comment]
could this be implemented via an option e.g.

```
$ toolbox --enable-sound enter
```

my plan is to run vlc, emacs (using emms) or even firefox within the toolbox container and this would require sound support.

jm2c
toni

**Comment by aimileus** [comment]
I tried to use the PulseAudio socket from the host and that seems to be fine: PulseAudio works, even if the host uses audio at the same time.

1. Bind mount `/dev/snd`
2. Install `pulseaudio-utils` in the container with dnf. 
3. Set `$PULSE_SERVER` to the value of `/run/user/$(id -ru)/pulse/native`, so that it uses the session of the host. I did not try to run a seperate PulseAudio session in the container.

**Comment by tosmi** [comment]
i just discovered that sound simply works with `vlc`. `/run/user/<uid>/native` is available within the container. didn't have to install pulseaudio-utils, `$PULSE_SERVER` is not set. i'm using toolbox from `master`.

**Comment by memnoth** [comment]
Thank you all for the information, I will check it out both.

**Comment by memnoth** [comment]
``/dev/snd`` might be sometimes necessary.  For instance, liquidwar. it tries to access to ``/dev/snd`` directly.
However, in my case, exporting ``PULSE_SERVER`` is necessary.

**Comment by jodkalemon** [comment]
I copied toolbox to my homedir, added a
`--volume /dev/snd;/dev/snd`
line to the create function and ran google-chrome in it and it just works.

**Comment by HarryMichal** [comment]
I believe this can be closed because Toolbox passes `--volume /dev:/dev:rslave` to `podman create` when a toolbox is created since v0.0.11.

**Comment by anacierdem** [comment]
I'm doing a simple test with `speaker-test -t wav -c 6` but it doesn't seem to work by default with:
```
speaker-test 1.2.9

Playback device is default
Stream parameters are 48000Hz, S16_LE, 6 channels
WAV file(s)
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
Playback open error: -2,No such file or directory
```

```
❯ toolbox --version
toolbox version 0.3
````

I'm trying this on ubuntu:24.04
