### ISSUE TITLE
Low quality icons from applications running in Toolbox

### ISSUE THREAD

**Issue by bkhl** [containers/toolbox#586]
**Describe the bug**

When launching a GUI application from Toolbox, instead of using the icon from my `~/.local/share/applications/*.desktop` file with the given window class, it shows a fuzzy low quality application icon.

**Steps how to reproduce the behaviour**

1. Install Emacs in a toolbox container
2. Create a .desktop file in `~/.local/share/applications/toolbox-foo.desktop` looking something like this:

```
[Desktop Entry]
Name=Emacs (foo)
Type=Application
Exec=toolbox run --container foo emacsclient --alternate-editor '' --socket 'foo' --create-frame --frame-parameters '((name . "emacs-foo"))'
Icon=emacs-foo
Categories=Utility;TextEditor;
Keywords=toolbox;
StartupWMClass=emacs-foo
```

**Expected behaviour**

Window created with window class `emacs-foo` to be matched with the above `.desktop` entry, and use the icon indicated by it.

**Actual behaviour**

The window is created and based on `xprop` output, it has the window class `emacs-foo`, but it is not matched to the `emacs-foo` icon, instead using a fuzzy version of the default icon.

**Screenshots**

![image](https://user-images.githubusercontent.com/34634/96471922-0ed30880-125a-11eb-8387-15c3df85693f.png)

In this screenshot you also see Emacs running installed with `rpm-ostree`. If they had the same window class I'd expect them to be grouped. However, even if starting the toolbox instance with the default window class, it appears like this.

**Output of `toolbox --version` (v0.0.90+)**

```
toolbox version 0.0.96
```

**Toolbox package info (`rpm -q toolbox`)**

```
toolbox-0.0.96-1.fc32.x86_64
```

**Output of `podman version`**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Thu Oct  1 02:31:11 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

```
podman-2.1.1-7.fc32.x86_64
```

**Info about your OS**

Fedora Silverblue 32

**Additional context**

I'm not sure what the exact desired behaviour here should be, if the application should be grouped with other windows from the same application on the host, or if it should be handled separately by using a different window class. I suspect though that if I can find out what the issue is here, I can maybe fix it.

**Comment by debarshiray** [comment]
Wow, interesting!

> Is there some particular reason for setting the hostname in toolbox containers to toolbox,
> does it cause issues to change it?
> 
> Is the appropriate fix here a change to Toolbox (like changing the hostname), or should this be
> seen as an issue in Gnome Shell?

The reason for setting a different hostname for the container is purely cosmetic, just like the purple hexagon. The intent is to somehow differentiate the prompt from the host to make it obvious that the user inside a container.

However, since every distribution has it's own slightly different arrangement of the shell start-up scripts and how things like `PS1` are set, we were wary of doing something too invasive initially. Changing the hostname would mean that all uses of `\h` would pick up the new name.

However, @allanday and others have been looking at coming up with a slightly nicer prompt, so this might change.

Coming back to your original issue. I honestly don't know off-hand what the right way forward would be. @fmuellner might have some thoughts on this.

**Comment by fmuellner** [comment]
Does the `emacs-foo` icon exist outside the toolbox?

**Comment by A6GibKm** [comment]
You are supposed to export the icon too. I am surprised you actually see it. I have a tool here to export everything https://github.com/A6GibKm/silverblue-tools.

**Comment by bkhl** [comment]
> Does the `emacs-foo` icon exist outside the toolbox?

Yes, that's an SVG icon that I put in `~/.local/share/icons`

As described in my previous comment, the icon does get used if I set the hostname in the container to match the host's hostname.

**Comment by bkhl** [comment]
> You are supposed to export the icon too. I am surprised you actually see it. I have a tool here to export everything https://github.com/A6GibKm/silverblue-tools.

With this solution, do you actually get an icon that associates itself with the launced windows, so that if you click the icon again, it activates the window rather than launching the application again?

I would expect that you would run into the same issue as me unless you make the hostnames match also.

**Comment by A6GibKm** [comment]
Just commenting on the icon. I will see later whats the behaviour.

**Comment by bkhl** [comment]
> Coming back to your original issue. I honestly don't know off-hand what the right way forward would be. @fmuellner might have some thoughts on this.

I should be able to set up some work-around now that I know the issue, running `hostname` in a file in `/etc/profile.d/` or something like that. However, I'll just say what the most convenient solution would be for _me_:

1. Add a `--hostname` flag to `toolbox` that passes along it's parameter to `--hostname` of Podman.
2. If not supplied, use the current host hostname as the container hostname.

If 2. causes issues with the shell prompt that can't be resolved for now (I guess that's better discussed in the tickets about that), of course I could live without 2. and instead supply that using the mentioned `--hostname` flag.

**Comment by A6GibKm** [comment]
This is my desktop file
```
[Desktop Entry]
Name=Emacs
GenericName=Text Editor
Comment=Edit text
Comment[zh_TW]=編輯文字
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
Exec=toolbox run emacs %f
Icon=emacs
Type=Application
Terminal=false
Categories=Utility;TextEditor;X-Red-Hat-Base;
StartupWMClass=Emacs
X-Desktop-File-Install-Version=0.24
```
It works as expected. You click the icon and it opens the already open instance.

**Comment by bkhl** [comment]
> It works as expected. You click the icon and it opens the already open instance.

That's interesting, I'm wondering what the difference is, are you using a newer version of Fedora than me (I'm on 32 for both the host and container)?

What is the output of running `xprop` and clicking your Emacs window?

**Comment by A6GibKm** [comment]
You WILL get the weird icon if you don't install it in you system, e.g. `~/.local/share/icons`.

**Comment by bkhl** [comment]
> You WILL get the weird icon if you don't install it in you system, e.g. `~/.local/share/icons`.

I have. And as I say this icon gets used if I manipulate the hostname of the container to match that of the host.

**Comment by A6GibKm** [comment]
Did you install the icon located at `toolbox:/usr/share/icons/hicolor/scalable/apps/emacs.svg`?

**Comment by bkhl** [comment]
Yes.

**Comment by fmuellner** [comment]
> As described in my previous comment, the icon does get used if I set the hostname in the container to match the host's hostname.

Sorry, I had missed that.

That actually makes sense, it means that gnome-shell mistakes the window for a remote X11 client and bypasses the usual .desktop file matching (because the matching .desktop file would be on a different host in that case):

https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/shell-window-tracker.c#L406

**Comment by bkhl** [comment]
> That actually makes sense, it means that gnome-shell mistakes the window for a remote X11 client and bypasses the usual .desktop file matching (because the matching .desktop file would be on a different host in that case):
> 
> https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/shell-window-tracker.c#L406

I suspect that this is what happens, and that the fuzzy icon I see is the icon from the toolbox environment sent in a non-vector form, which ends up not looking very nice.

**Comment by fmuellner** [comment]
> the fuzzy icon I see is the icon from the toolbox environment sent in a non-vector form

More precisely, it's the `_NET_WM_ICON` property set by emacs.

**Comment by bkhl** [comment]
Yup, if I start it with `--no-bitmap-icon`, I get no icon for it at all.

Apparently, X clients are allowed to set the `WM_CLIENT_MACHINE` value as well, but I don't see a way to modify it from within Emacs.

However, looking at what that value _should_ be, it's supposed to be the hostname of the machine the client is running on, as seen from the X server (Wayland X11 emulation in this case).

Since the toolbox isn't emulating a separate machine in a networking sense, and there's no hostname for it to give it from the host, I'm leaning towards that the toolboxes should by default have the same hostname as the host, and the `PS1` thing be solved in some other way.

**Comment by daquinons** [comment]
> Ah, found that if I set the hostname of the Toolbox to match my hostname, get this in the `xprop` of the window:
> 
> ```
> WM_CLIENT_MACHINE(STRING) = "$myhostname"
> ```
> 
> and Gnome Shell actually _does_ apply my `.desktop` icon.
> 
> AFAIK I guess this would work as a workaround for me, although it makes me wonder:
> 
>     1. Is there some particular reason for setting the hostname in toolbox containers to `toolbox`, does it cause issues to change it?
> 
>     2. Is the appropriate fix here a change to Toolbox (like changing the hostname), or should this be seen as an issue in Gnome Shell?

Hello! How do you set that? :thinking: Thanks! This issue has been driving me crazy :D Happening with VS Code.

**Comment by bkhl** [comment]
> Hello! How do you set that? thinking Thanks! This issue has been driving me crazy :D Happening with VS Code.

If your hostname is `foo`, just run `hostname foo` in the toolbox. To make it persist, the only way I can think of at the moment is to set it in your profile, by creating a file named something like `/etc/profile.d/hostname` with the contents:

```bash
sudo hostname foo
```

You can also edit `/etc/hostname` to match but I think for most purposes this will not matter.

This is because the hostname is set as a property of the container when Toolbox creates. Thus my request to add `--hostname` flag to `toolbox create` as well.

PS. If someone knows a way to change the hostname of an already created container instead, that would be nice, so let me know in that case.

**Comment by bkhl** [comment]
In case of anyone wanting to do the same workaround for now, here's how I automated changing the hostname of the container after creation: https://gitlab.com/bkhl/toolboxes/-/blob/latest/scripts/toolbox-project#L191

**Comment by bkhl** [comment]
![image](https://user-images.githubusercontent.com/34634/101586423-7b75b280-3a14-11eb-9a48-0c12643e1fd0.png)

noting that since upgrading to Fedora 33, GNOME shows these icons in their native size instead of scaling them, so it looks slightly less crappy.

**Comment by debarshiray** [comment]
So, did the original problem of low quality icons get solved or at least worked around?

I am asking because I am a bit lost in the back and forth on this bug.

**Comment by fmuellner** [comment]
It's not fixed, but it can be worked around by setting the toolbox's hostname to the same string as the host's hostname.

Or if possible, set up the app to use wayland, as only X11 windows are affected.
