### ISSUE TITLE
Podman command expansion

### ISSUE THREAD

**Issue by Upcycle-Electronics** [containers/toolbox#592]
Do you have a list of the podman commands needed to replicate how a toolbox is created and entered?

...feature request...   ^^this^^ ...in the man/help page :-)

**Comment by debarshiray** [comment]
The list is there in the Toolbox sources. ;)

The Toolbox manuals also mention the main underlying Podman command that's used. eg., see `toolbox-create(1)` and `toolbox-enter(1)`.

However, no, we are not going to document the Podman commands in their entirety in the manuals. We consider them to be an implementation detail that users shouldn't have to worry about, and we'd like to retain the freedom to change them in whichever way necessary.
