### ISSUE TITLE
Toolbox containers missing man pages for many packages

### ISSUE THREAD

**Issue by lambda** [containers/toolbox#603]
**Describe the bug**

The fedora-toolbox containers from https://registry.fedoraproject.org/, which are installed by default by `toolbox`, are missing a number of man pages, such as those for utilities in `coreutils`, which are packaged in `coreutils-common`.

It looks like each release has a hand-maintained list of packages to restore docs, since docs are not included in the parent fedora image. For example, https://github.com/containers/toolbox/blob/master/images/fedora/f33/missing-docs list packages to restore docs for in the f33/fedora-toobox container. But this list is incomplete, there are a number more packages which are missing docs.

**Steps how to reproduce the behaviour**

This has been tested on both f32 and f33, as I was in the process of upgrading when I discovered this.

1. Run `toolbox create` to create the default toolbox (or `toolbox create --release f33` if you want to be specific about it)
2. Run `toolbox enter` to start a shell in the default toolbox (or `toolbox enter --release f33`)
3. Run `man mktemp` within the toolbox shell to look up docs on the `mktemp` utility

**Expected behaviour**

I expected to read the docs on the `/usr/bin/mktemp` utility form the `coreutils` project.

**Actual behaviour**

I got only `man(3) mktemp`, on the `mktemp` standard library call.

**Output of `toolbox --version` (v0.0.90+)**

```
[lambda@eiffel ~]$ toolbox --version
toolbox version 0.0.96
```

**Toolbox package info (`rpm -q toolbox`)**

```
[lambda@eiffel ~]$ rpm -q toolbox
warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
toolbox-0.0.96-1.fc33.x86_64
```

**Output of `podman version`**

```
[lambda@eiffel ~]$ podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Sun Oct  4 19:25:24 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

```
[lambda@eiffel ~]$ rpm -q podman
warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
podman-2.1.1-10.fc33.x86_64
```

**Info about your OS**

```
[lambda@eiffel ~]$ cat /etc/os-release 
NAME=Fedora
VERSION="33.20201028.0 (Silverblue)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33.20201028.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='33.20201028.0'
```

**Additional context**

```
[lambda@eiffel ~]$ toolbox list -i
IMAGE ID      IMAGE NAME                                        CREATED
7e4d1b69a358  registry.fedoraproject.org/f32/fedora-toolbox:32  4 months ago
4f81af0fcbc0  registry.fedoraproject.org/f33/fedora-toolbox:33  38 hours ago
```

The following can fetch a full list of the affected packages:

```
[lambda@eiffel ~]$ toolbox enter -r f33
⬢[lambda@toolbox ~]$ rpm -qads --qf "PACKAGE: %{NAME}\n" | sed -n -E '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }' | uniq
crypto-policies
tzdata
pcre2-syntax
ncurses-base
dnf-data
setup
glibc-common
glibc
zlib
sqlite-libs
libdb
gmp
libgpg-error
libxcrypt
popt
libxml2
readline
file-libs
expat
libffi
libunistring
libidn2
libassuan
libgcrypt
alternatives
keyutils-libs
audit-libs
libtasn1
lz4-libs
pcre
libsemanage
shadow-utils
libutempter
vim-minimal
libcomps
libmetalink
libksba
mpfr
nettle
gnutls
libeconf
libgomp
libsigsegv
libverto
libyaml
coreutils-common
ca-certificates
krb5-libs
libtirpc
libblkid
glib2
systemd-libs
zchunk-libs
libusbx
cyrus-sasl-lib
openldap
gnupg2
gpgme
libssh
librepo
tpm2-tss
ima-evm-utils
python3-libs
python3-gpg
cracklib
libpwquality
libarchive
libmodulemd
libsolv
libdnf
dnf
yum
sssd-client
sudo
util-linux
rpm
man-db
passwd
jwhois
```

This command, or something like it, could be used for populating the list of packages to restore docs for automatically, rather than manually maintaining the list.

To break the command down:

1. `rpm -qads` list the status of doc files in all packages
2. `... --qf "PACKAGE: %{NAME}\n"` and prefix each list with the package name
3. `| sed -n -E '/PACKAGE: /{s/PACKAGE: // ; h ; b }; ...` using sed without the default behavior of printing the pattern space, look for the heading lines containing package names, and when found add the package name to the hold space and move on to the next line
4. `... /^not installed/ { g; p }'` if any of the docs files in this package are listed as not installed, copy the package name from the hold space, print it, and move on
5. `| uniq` replace the duplicates we get because we print the package name once per missing file, and I had already spent too much time trying to figure out how to get `sed` to do the above and couldn't be bothered continuing to try to make `sed` do this 

I tried to work around this in a toolbox container with:

```
sudo dnf -y reinstall $(rpm -qads --qf "PACKAGE: %{NAME}\n" | sed -n -E '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }' | uniq)
```

But that actually installed a bunch of other dependencies and weak dependencies that we may not want, so there may need to be some further filtering of the list or flags to `dnf` to prevent it from installing too much.

**Comment by edwintorok** [comment]
Also affects distrobox, the workaround works there too.

**Comment by debarshiray** [comment]
Seems like we missed this one.  My apologies.

Yes, this has been a known problem from the very first day.  My RPM and Sed skills weren't enough to let me hack that up in seconds, and I never found the time to properly dig into it.  So, many thanks for putting together that pipeline with `rpm(1)` and `sed(1)`.

I put together a pull request to fix the `fedora-toolbox` images at https://github.com/containers/toolbox/pull/1396 and added a built-in test, based on your command, to ensure that the list of packages stays updated as the `fedora` base image evolves.

For Fedora 39 onwards, the `fedora-toolbox` images are no longer going to be built as layered images on top of the `fedora` base image with Container/Dockerfiles.  They are going to be built using [fedora-kickstarts](https://pagure.io/fedora-kickstarts/) and [pungi-fedora](https://pagure.io/pungi-fedora/) as *base* images, just like the `fedora` base image.  This removes the need to undo the consequences of minimization efforts put into the `fedora` base image.

This is one of the outcomes from the [ToolbxReleaseBlocker](https://fedoraproject.org/wiki/Changes/ToolbxReleaseBlocker) Change for Fedora 39, which adopts the `fedora-toolbox` images as a release-blocking deliverable from the Fedora Project.
