### ISSUE TITLE
AfterShotPro3 does not start

### ISSUE THREAD

**Issue by skontar** [containers/toolbox#627]
**Describe the bug**
AfterShotPro3 worked well in Fedora 31, but does not have compatible libraries in Fedora 32. I tried to install it using toolbox and Fedora 31 container, which worked fine, but the application fails to start.

**Steps how to reproduce the behaviour**
1. Download https://dwnld.aftershotpro.com/trials/3/AfterShotPro3.rpm
2. Create Fedora 31 toolbox: `toolbox create --release f31`
3. Enter: `toolbox enter --release 31`
4. Install application locally: `sudo dnf install AfterShotPro3.rpm`
5. Start the application: `AfterShot3X64`

**Expected behaviour**
Application starts and works.

**Actual behaviour**
Application seems to start, the startup window appears, then it crashes:
```
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv2_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv2_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)
```

**Screenshots**
N/A

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.97`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.97-1.fc32.x86_64`

**Output of `podman version`**
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 21:31:11 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-2.1.1-7.fc32.x86_64`

**Info about your OS**
Fedora 32

**Additional context**
I am not sure if graphical applications are even supported, but it looks like it is very close to actually working.

**Comment by debarshiray** [comment]
Yes, graphical applications are supposed to work.

Would it be possible for you to get some information about the crash? A backtrace, or maybe a strace log?

**Comment by skontar** [comment]
Sure thing. I am not very experienced with debugging compiled applications, so if you can get me any pointers what to run or where to start with getting backtrace or strace log or where to quickly learn about them, then I can spend some time diving in.

**Comment by skontar** [comment]
[strace.log](https://github.com/containers/toolbox/files/5560521/strace.log)

**Comment by skontar** [comment]
[gdb_backtrace.txt](https://github.com/containers/toolbox/files/5560977/gdb_backtrace.txt)

**Comment by debarshiray** [comment]
Thanks for those logs.

From the strace logs, it looks like it's crashing when reading `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`.

**Comment by debarshiray** [comment]
And these hint at some sort of OpenSSL ABI problem:
```
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv2_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv2_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
```

With those clues, a bit searching [pointed me at](https://support.corel.com/hc/en-us/articles/360033740854-AfterShot-Pro-AfterShot-Pro-does-not-launch-in-Fedora-30) `compat-openssl10`. The application starts if you install that RPM. :)

**Comment by debarshiray** [comment]
Closing this now. Thanks for stopping by.

**Comment by skontar** [comment]
@debarshiray Awesome! I would not be able to figure it out myself. It never occurred to me that missing package could be the problem. I thought that the dependencies are resolved by the rpm, but in reality I just got the library installed on my old system by pure chance. Thank you!

**Comment by debarshiray** [comment]
No problem! I am glad it worked out. :)
