### ISSUE TITLE
toolbox run can not find commands by relative path

### ISSUE THREAD

**Issue by hexagonrecursion** [containers/toolbox#630]
**Describe the bug**
When I run `toolbox run ./foo.sh` toolbox does not execute `./foo.sh` from the cwd.

**Steps how to reproduce the behaviour**
```
~ $ cat ./foo.sh
#!/bin/env bash
printf 'hello\n'
~ $ ./foo.sh
hello
~ $ toolbox --log-level debug run ./foo.sh
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user user 
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Toolbox config directory is /home/user/.config/toolbox 
DEBU Current Podman version is 2.1.1              
DEBU Old Podman version is 2.1.1                  
DEBU Migration not needed: Podman version 2.1.1 is unchanged 
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'fedora-toolbox-32'               
DEBU Image: 'fedora-toolbox:32'                   
DEBU Release: '32'                                
DEBU Checking if container fedora-toolbox-32 exists 
DEBU Inspecting mounts of container fedora-toolbox-32 
DEBU Starting container fedora-toolbox-32         
DEBU Inspecting entry point of container fedora-toolbox-32 
DEBU Entry point PID is a float64                 
DEBU Entry point of container fedora-toolbox-32 is toolbox (PID=4444) 
DEBU Waiting for container fedora-toolbox-32 to finish initializing 
DEBU Checking if initialization stamp /run/user/1000/toolbox/container-initialized-4444 exists 
DEBU Container fedora-toolbox-32 is initialized   
DEBU Looking for command ./foo.sh in container fedora-toolbox-32 
Error: command ./foo.sh not found in container fedora-toolbox-32
~ $ 
```

**Expected behaviour**
`./foo.sh` is executed in the toolbox

**Actual behaviour**
```
Error: command ./foo.sh not found in container fedora-toolbox-32
```

**Screenshots**
none

**Output of `toolbox --version` (v0.0.90+)**
```
$ toolbox --version
toolbox version 0.0.97
```

**Toolbox package info (`rpm -q toolbox`)**
```
$ rpm -q toolbox
toolbox-0.0.97-1.fc32.x86_64
```

**Output of `podman version`**
```
$ podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 22:31:11 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
```
$ rpm -q podman
podman-2.1.1-7.fc32.x86_64
```

**Info about your OS**
```
$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
```

**Additional context**
At first I thought that `toolbox run` does not preserve the cwd (e.g. changes it to / or to ~) but after a little experimenting with `toolbox run cwd` it turned out to not be the case.

**Comment by debarshiray** [comment]
The idea behind `toolbox run` was to enable people to write their own desktop files to run graphical applications that might be installed in a Toolbox. If you want to run ad hoc scripts and binaries, then I'd suggest supplying an absolute path as `$(pwd)/foo.sh`. Or, you can run an interactive Toolbox environment using `toolbox enter`.

Unfortunately, making `toolbox run` support relative paths isn't high on our priority list at the moment.

**Comment by hexagonrecursion** [comment]
Sure I can work around this, but my point is that this is a behaviour I did not expect. It was surprising.

**Comment by hexagonrecursion** [comment]
My intuition tells me that [src/cmd/run.go:runCommand()](https://github.com/containers/toolbox/blob/1a5acddca2a69bd1a2861bc3f351924ae39a0798/src/cmd/run.go#L137) is really two different functions joined like Siamese twins. One runs a specific command in a specific container. The other has a whole bunch of fallback logic. I'll try to separate them. You can track my progress here: https://github.com/hexagonrecursion/toolbox/compare/fix-630-base...hexagonrecursion:fix-630

**Comment by debarshiray** [comment]
I am looking forward to seeing what you come up with. Thank you very much for working on this!
