### ISSUE TITLE
sudo asks for password

### ISSUE THREAD

**Issue by Gavus** [containers/toolbox#644]
**Describe the bug**
I am asked to enter password for my user, and it does not work.

**Steps how to reproduce the behaviour**
1. Using ubuntu 20.04 lts.
2. Install requirements: podman and flatpak.
3. Enter default toolbox container: fedora:30.
4 sudo echo hello

**Expected behaviour**
stdout print hello

**Actual behaviour**
Sudo asks for password and the host password does not work.

**Output of `toolbox --version` (v0.0.90+)**
toolbox: unrecognized option '--toolbox'
I Downloaded v0.0.97

**Output of `podman version`**
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Podman package info (`apt show podman`)**
```
Package: podman
Version: 2.2.0~2
Priority: optional
Section: devel
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Installed-Size: 69,4 MB
Depends: libseccomp2, libdevmapper1.02.1, libgpgme11, catatonit, conmon (>= 2.0.18~1), containers-common (>= 1.2.0~3), containernetworking-plugins (>= 0.8.6~1), runc | cri-o-runc, iptables, podman-plugins (>= 1.1.1~1)
Recommends: crun, slirp4netns, uidmap, varlink
Conflicts: podman-rootless
Homepage: https://github.com/containers/podman.git
Download-Size: 16,9 MB
APT-Sources: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Packages
Description: Manage pods, containers and container images.
```

**Info about your OS**
Ubuntu 20.04 Lts

**Comment by debarshiray** [comment]
>  toolbox: unrecognized option '--toolbox'

You are running the POSIX shell implementation of Toolbox, which is unmaintained.  Try building and using the Go implementation instead.

**Comment by debarshiray** [comment]
Thanks for stopping by!
