### ISSUE TITLE
Ubuntu Xenial container issues.

### ISSUE THREAD

**Issue by VinnyVynce** [containers/toolbox#650]
**Describe the bug**
I'm a bit out of ideas to get this work but I cannot get Ubuntu Xenial working in Toolbox at all on my system. SELinux and this particular version of Ubuntu doesn't seems to not play along.

**Steps how to reproduce the behaviour**
1. wget my dockerfile in [this gist](https://gist.github.com/VinnyVynce/bfe791dfb821467751db4cd541e9e412).
2. `podman build -t ubuntu-xenial-toolbox -f Dockerfile-xenial `
3. `toolbox create -i localhost/ubuntu-xenial-toolbox:latest -c xenial`
4. `toolbox enter -c xenial` leads to `Error: invalid entry point PID of container xenial`
5. `podman start  --attach xenial` leads to `usermod: failure while writing changes to /etc/passwd`
6. doing a temporary `sudo setenforce 0` and another `podman start  --attach xenial` leads to a full start now...
7. `sudo apt install aptitude` will lead to `cannot get security labeling handle: No such file or directory` which is related to SELinux
8. exiting from toolbox and typing `podman run --security-opt label=disable -it localhost/ubuntu-xenial-toolbox /bin/bash` and `sudo apt install aptitude` will however work.

**Expected behaviour**
Having the toolbox create correctly without changing my enforcement level and working correctly within toolbox.

**Actual behaviour**
The tmp dosen't mount properly at all, I had to mount it in the dockerfile, I always get a bad fs error. I don't have this error in my Ubuntu 18:04, debian sid or Fedora 33 toolboxes.
The toolbox cannot get pass /etc/passwd with an enforcing policy and runs into other issues with a permissive policy.

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.97

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.97-1.fc33.x86_64

**Output of `podman version`**
```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 09:37:50 2020
OS/Arch:      linux/amd64

```

**Podman package info (`rpm -q podman`)**
podman-2.2.1-1.fc33.x86_64

**Info about your OS**
Fedora Silverblue 33

**SELinux Status (`getenforce`)**
Enforcing

**Comment by debarshiray** [comment]
Unfortunately, we don't support Ubuntu Toolbox containers at the moment because the upstream Toolbox maintainers don't have the bandwidth to debug issues affecting those containers when running on different kinds of hosts. :(

I will have to close this. Thanks for stopping by.
