### ISSUE TITLE
Creating a toolbox fails when the user's uid is not the same and their gid.

### ISSUE THREAD

**Issue by aem09** [containers/toolbox#664]
**Describe the bug**
toolbox create fails with the error: "Error: failed to change ownership of the runtime directory /run/user/1010/toolbox: chown /run/user/1010/toolbox: operation not permitted" . When a user's uid is not the same as their gid.

This is because the user is not allowed to change the ownership of the file (which is actually owned by then anyway) to a group that does not exist or belongs to something else.

**Steps how to reproduce the behaviour**
1. Login with a user who has a different uid to gid
2. Attempt to create a toolbox.

**Expected behaviour**
Toolbox created.

**Actual behaviour**
Creation fails with Error: failed to change ownership of the runtime directory /run/user/1010/toolbox: chown /run/user/1010/toolbox: operation not permitted

**Screenshots**
![image](https://user-images.githubusercontent.com/33454849/104186706-b9e4ff80-540e-11eb-8bee-46b2b291d1a4.png)

**Output of `toolbox --version` (v0.0.90+)**
toolbox version 0.0.98.1

**Toolbox package info (`rpm -q toolbox`)**
toolbox-0.0.98.1-1.fc33.x86_64

**Output of `podman version`**
```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 14:37:50 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman-2.2.1-1.fc33.x86_64

**Info about your OS**
Fedora release 33 (Thirty Three)

**Additional context**
Changing the same user's gid to be the same as their uid allowed podman to work fine:
![image](https://user-images.githubusercontent.com/33454849/104187394-a0908300-540f-11eb-9331-92448f4042cf.png)

As far as I can tell, this issue is caused by this [line](https://github.com/containers/toolbox/blob/7c02f93d680da1d3b64e6bb45146a80937bd3f6c/src/pkg/utils/utils.go#L376) making the assumption that the user's uid is the same as their gid, but I'm not certain.

**Comment by lebel** [comment]
I have the same issue here. My uid is 1026 and my gid is 100 and with the new version of toolbox, it fails the same way.

**Comment by Crivaledaz** [comment]
Hi,

We have the exact same problem in my company, since we have updated the Toolbox package on Fedora 33 to the version 0.0.98.

Our users connect to their Fedora Workstation with LDAP credentials and each user has a unique UID, but they belong to the same main group "People" which has a GID different from any UID. So, none of our users get the same UID and GID.

Note : that was working with toolbox version 0.0.96 (from package toolbox-0.0.96-1.fc33.x86_64).

Regards

**Comment by rommi4** [comment]
same here 
`$ id 
uid=1000(rvt480) gid=1001(rvt480) groups=1001(rvt480),10(wheel),976(docker),998(input),1000(sudo)`

level=debug msg="Creating runtime directory /run/user/1000/toolbox"
Error: failed to change ownership of the runtime directory /run/user/1000/toolbox: chown /run/user/1000/toolbox: operation not permitted

**Comment by BrunoVernay** [comment]
Is there a workaround?  Because it is not released yet
