### ISSUE TITLE
UBI image does not include sudo

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#670]
**Describe the bug**
The UBI image does not include sudo, which as far as I can tell more or less means
that a rootless ubi container cannot install any packages?  I would be happy if I am wrong...
however this makes it not very useful yet sadly.
So it seems to me it is necessary to have a ubi-toolbox base container to add sudo etc, like we also do for Fedora?
Are there plans to do this?

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99`

**Info about your OS**
Fedora/Silverblue 33

**Comment by debarshiray** [comment]
This was also my initial reaction, but then I saw that UBI has `su`! So, this should work:
```
$ su -
# dnf ...
```

**Comment by juhp** [comment]
Ah thanks - you right that makes a big difference.

(But also with ubi8 locale is not reset to C.utf8 - again not difficult to fix, but another thing to think about.)

**Comment by debarshiray** [comment]
It turns out that the UBI RPM repositories always had `sudo` in them.  It was just the UBI base image that didn't come with `sudo`.  So it was possible to install afterwards.

Since RHEL 8.5, we have the `registry.access.redhat.com/ubi8/toolbox:8.5` image that comes with `sudo`.

Closing.
