### ISSUE TITLE
Toolbox errors with `Error: failed to get the current user's default shell`

### ISSUE THREAD

**Issue by meghprkh** [containers/toolbox#672]
Toolbox errors with `Error: failed to get the current user's default shell` on running any command when (I think) zsh is the default shell. 

**Steps how to reproduce the behaviour**
1. Setup `prezto` or maybe just `chsh zsh` works too
2. Run `toolbox create -c abc`
3. See error  `Error: failed to get the current user's default shell` 
4. The same error is also seen on `bash -c 'toolbox create -c abc'`

**Expected behaviour**
It should have created a container

**Actual behaviour**
It failed to create a container with `Error: failed to get the current user's default shell`

**Screenshots**
NA

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99-1.fc33.x86_64`

**Output of `podman version`**
```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 14:37:50 2020
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
e.g., `podman-1.9.2-1.fc32.x86_64`

**Info about your OS**
Fedora 33

**Additional context**
I am using Prezto zsh. PFA the log of `toolbox -vv create -c abc &> toolbox-log`

[toolbox-log.txt](https://github.com/containers/toolbox/files/5832755/toolbox-log.txt)

**Comment by meghprkh** [comment]
To notify devs, it is working again! Thanks :) Keeping it open since I can see an open PR above.

**Comment by HarryMichal** [comment]
Hi @meghprkh! Thank you for reporting the issue! Since it has been solved and the PR above is [not related](https://github.com/containers/toolbox/pull/675#issuecomment-780926572) to this, I'll close it.
