### ISSUE TITLE
Xauthority issues (on SDDM?): Can't open display: 0 due to `toolbox` hostname

### ISSUE THREAD

**Issue by mjlbach** [containers/toolbox#679]
**Describe the bug**

I'm almost done packaging toolbox for nixos. Like silverblue, this will be incredibly advantageous for users who want an escape hatch from the immutable non-FHS compliant filesystem.

Xauth is shared with the container, but gui apps refuse to open with `keyError: Can't open display: 0`. Running `xauth list` shows:

```
# Using authority file /home/mjlbach/.Xauthority
nixos/unix:0  MIT-MAGIC-COOKIE-1 yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy 
```

After running (inside the toolbox) `xauth add $DISPLAY . yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy `, xauth lists an additional entry:

```
toolbox/unix:0  MIT-MAGIC-COOKIE-1  yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```

And will subsequently allow gui apps to connect to the Xserver, with no problems at all, until the next system restart when the keys are wiped. The other option is changing the hostname of the container to `nixos`, matching xauth,, which also seems to solve the issue.

This is suboptimal, as this key has to be re-entered on every restart. I assume that toolbox should automatically handle this, and the fact that the hostnames don't match wouldn't be an issue, as the toolbox container has a hostname of `toolbox` by default. Any pointers on where to look to debug this would be appreciated!

For reference, the xauth list on fedora/gnome is much shorter:
```
#Using authority file /run/user/1001/gdm/Xauthority
localhost.localdomain/unix:  MIT-MAGIC-COOKIE-1  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#ffff#6c6f63616c686f73742e6c6f63616c646f6d61696e#:  MIT-MAGIC-COOKIE-1  yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```
Which uses a different Xauthority file than nixos/kde, so maybe that is part of the issue?

**Output of `toolbox --version` (v0.0.90+)**
toolbox 0.0.99

**Toolbox package info (`rpm -q toolbox`)**
toolbox 0.0.99

**Output of `podman version`**

```
Version:            2.2.1
RemoteAPI Version:  2.1.0
Go Version:         go1.15.7
OS/Arch:            linux/amd64
```

**Podman package info (`rpm -q podman`)**
podman 2.2.1

**Info about your OS**
NixOS 21.03 (nixpkgs-unstable)

**Additional context**

Related: https://github.com/containers/toolbox/issues/197

**Comment by tijolao** [comment]
Just adding if you use GDM this problem doesn't happen with KDE, GDM adds one more entry to Xauthority and SDDM not. My xauth list:

```
xauth list
archo/unix:  MIT-MAGIC-COOKIE-1  xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#ffff#617263686f#:  MIT-MAGIC-COOKIE-1  xxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by mjlbach** [comment]
I think this is because SDDM doesn't create FamilyWild type xauth entries:

https://github.com/sddm/sddm/issues/733
https://bugzilla.redhat.com/show_bug.cgi?id=1370222#c25

**Comment by jessesaga** [comment]
I'm experiencing this same issue on Fedora 33 when I use SSH X11 forwarding. On the remote Fedora 33 instance I can run X applications without issues. Once I enter the toolbox X11 applications fail with authentication errors.

`xauth add $DISPLAY . yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy` allows for the X11 forwarding to succeed.

**Comment by HarryMichal** [comment]
Hi @mjlbach! First of all, thank you for packaging Toolbox for NixOS! We appreciate it greatly!

Now, to be frank, I have a very limited knowledge of X11 and everything around it. But I do have at least one thought.

Toolbox does not touch `.Xauthority` directly. Not on GNOME Shell, nor KDE Plasma. All Toolbox does is pass the `XAUTHORITY` environmental variable to the toolbox container when it is entered/command is executed there and bind mounts the user's runtime directory and home directory (also several more bind mounts but only these seem relevant). So, when using Shell, `.Xauthority` lives in the runtime directory and when using Plasma, the file lives in the home folder. In both cases, this should work alright (and seems to be working on Fedora with both desktop environments). So, I'd say that Toolbox could definitely fix this in some way but to me it seems only as a temporary solution and seems more like misconfiguration (or at least incomplete configuration) of `.Xauthority` on NixOS. What do you think?

As I said, my knowledge of X11 is very limited and my reasoning could be wrong.

@jessesaga Just tried that on my machine through ssh-ing to localhost (so to my own machine) and had a similar but a slightly different experience. I could not get GUI apps to run from the host but from a toolbox it worked fine :). But that may be specific to the ssh-ing to localhost use case. I'm not confident, yet, to say these two issues are not related. Let's keep them together for now.

@debarshiray, I'll need your insight here.

**Comment by mjlbach** [comment]
Hi @HarryMichal!

Thanks for your work on toolbox! (Fedora is my daily driver).

SDDM, unlike GDM, doesn't use FamilyWild type xauth entries, so Xauth is sensitive to the hostname. This is why it works on gnome, but not SDDM on nixos.

There's this upstream PR for SDDM which would fix the issue here: sddm/sddm#1230

Fedora applies this patch to SDDM (same author): https://src.fedoraproject.org/rpms/sddm/blob/master/f/0001-Redesign-Xauth-handling.patch to use FamilyWild, I'm not sure if this causes enough issues/inconvenience to justify a patch in nixpkgs as well.

I can confirm applying this patch to our sddm, that the problem is resolved as well.

**Comment by HarryMichal** [comment]
Ah, ok, that explains it. And by looking at the PR it does not seem a final solution is near. So, patching Toolbox for the time being might be the forward. But first, let's hear what @debarshiray thinks.

**Comment by mjlbach** [comment]
Sounds good :) I'm not sure how worth it is for adding a mitigation for an upstream bug (I filed this issue before I nailed down this was upstream and edited the issue subsequently). I'm surprised more arch/debian/opensuse users haven't run into this, but I don't know the size of the kde/toolbox/not-on-fedora community.

**Comment by debarshiray** [comment]
Yes, I agree with @mjlbach that this is likely best fixed in SDDM. It seems that https://github.com/sddm/sddm/pull/1230 is waiting for a rebase, and a lot of distributors are using that patch in one form or another already.

By the way, thanks for tracking this one down, @mjlbach 

Closing.
