### ISSUE TITLE
Fedora Branched (34) and Rawhide (35) Images

### ISSUE THREAD

**Issue by LorbusChris** [containers/toolbox#706]
**Is your feature request related to a problem? Please describe.**
Please build and distribute Fedora 34 and Rawhide images

**Describe the solution you'd like**
F34 and Rawhide images are released to the registry

**Comment by debarshiray** [comment]
I believe this an after effect of https://github.com/containers/toolbox/pull/615

The `fedora-toolbox` OCI images are already there on `registry.fedoraproject.org`, but we needed a new Toolbox release to get the client-side tool to use the new location on the registry. I just did that. Here's the update for Fedora 34: https://bodhi.fedoraproject.org/updates/FEDORA-2021-866c556687

**Comment by LorbusChris** [comment]
Oh right, they do exist at the new location, however the aarch64 build for F35 is missing:
```
[lorbus@lenovo ~]$ podman manifest inspect docker://registry.fedoraproject.org/fedora-toolbox:34
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 741,
            "digest": "sha256:a390875989bf64f5d1b9147124b431d3e82ba808e06867b130c274dd9012b4a0",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 741,
            "digest": "sha256:9e758006096ecb1dd52f109069c38600e31c03c2f1f242f134922dcbfab646fc",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        }
    ]
}
[lorbus@lenovo ~]$ podman manifest inspect docker://registry.fedoraproject.org/fedora-toolbox:35
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 741,
            "digest": "sha256:7949bae9352853f09a0f93da5709c8c2bb1deae67c6bee4a7b2a5b769780cbb5",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    ]
}
```

**Comment by debarshiray** [comment]
Interesting. Thanks for pointing that out.

This is something that needs to sorted out with the [Fedora infrastructure](https://pagure.io/fedora-infrastructure/) team. Could you file a ticket with them? I have pinged a few folks on the Freenode IRC network to see what's going on.

**Comment by debarshiray** [comment]
I am going to close this issue now, since there's nothing more that we can do upstream.

Thanks for trying out Toolbox and stopping by!
