### ISSUE TITLE
RFE: Support systems without man installed

### ISSUE THREAD

**Issue by travier** [containers/toolbox#713]
**Is your feature request related to a problem? Please describe.**
Fedora CoreOS systems do not have the man command installed. Running `toolbox --help` on such a system results in:
```
$ toolbox --help
Error: man(1) not found
```
which is not a great user experience.

**Describe the solution you'd like**
toolbox uses the https://github.com/spf13/cobra module for argument parsing and this module support generating help text from argument parsing code. I have not yet dig into the code to figure out what's needed to use that in toolbox.

**Comment by debarshiray** [comment]
Well, we are trying to move in a direction where the documentation is consolidated around the manuals by making sure that they are easy to read, are kept updated, etc.. They are written in Markdown, which makes it easy to render them in a web browser, which is nice.

Bits and pieces of the Toolbox documentation have gotten scattered across the Fedora wiki and Silverblue website over time, and that's what motivated this.

So, I don't want to add a second way of showing an elaborate help screen that's independent from the manuals. It will complicate the command line parsing logic, which already has its subtleties that might not be obvious at first, and will be yet another thing that needs to be tested and kept updated as the code evolves.

Also, integrating the manuals with the `--help` output or a `help` command isn't without precedent. Git comes to mind, but I won't be surprised if there are more. It's just a nicer way to format a big chunk of text.

That said, I understand the problem when using CoreOS.

How about having a somewhat simple static blurb as a compromise that's unlikely to need a lot of maintenance, and can be dumped to the screen if the `man(1)` invocation fails? It can direct users to the Toolbox website where they can find the manuals in Markdown format.
```
toolbox - Tool for containerized command line environments on Linux

Common commands are:
create    Create a new toolbox container
enter     Enter an existing toolbox container
list      List all existing toolbox containers and images

Go to https://github.com/containers/toolbox for further information.
```

**Comment by travier** [comment]
Would have been great to have the full help but I understand the maintenance burden. This should make things much better.
