### ISSUE TITLE
Images without /etc/machine-id don't work

### ISSUE THREAD

**Issue by TheEvilSkeleton** [containers/toolbox#734]
**Describe the bug**

I'm trying to install the `docker.io/archlinux/archlinux` image, but it doesn't work.

**Steps how to reproduce the behaviour**
1. Run `toolbox create --image docker.io/archlinux/archlinux`
2. Run `toolbox enter archlinux`

**Expected behaviour**

It should start the container.

**Actual behaviour**

Gives me the following error: `Error: invalid entry point PID of container archlinux`

Running `podman start --attach archlinux`:

```
level=debug msg="Running as real user ID 0"
level=debug msg="Resolved absolute path to the executable as /usr/bin/toolbox"
level=debug msg="TOOLBOX_PATH is /usr/bin/toolbox"
level=debug msg="Creating /run/.toolboxenv"
level=debug msg="Monitoring host"
level=debug msg="Path /run/host/etc exists"
level=debug msg="Resolved /etc/localtime to /run/host/usr/share/zoneinfo/America/New_York"
level=debug msg="Binding /etc/machine-id to /run/host/etc/machine-id"
mount: /etc/machine-id: mount point does not exist.
Error: failed to bind /etc/machine-id to /run/host/etc/machine-id
```

**Output of `toolbox --version` (v0.0.90+)**

`toolbox version 0.0.99.1`

**Toolbox package info (`rpm -q toolbox`)**

`toolbox-0.0.99.1-1.fc34.x86_64`

**Output of `podman version`**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.16
Built:        Mon Feb 22 09:08:57 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**

`podman-3.0.1-1.fc34.x86_64`

**Info about your OS**

```
TheEvilSkeleton@TheMainLaptop ~> cat /etc/os-release 
NAME=Fedora
VERSION="34.20210321.n.0 (Silverblue Prerelease)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34.20210321.n.0 (Silverblue Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='34.20210321.n.0'
```

**Additional context**

It's a freshly installed Fedora Silverblue 34 OS. All I ran prior is `rpm-ostree upgrade`.

**Comment by TheEvilSkeleton** [comment]
Just found out about https://github.com/containers/toolbox/pull/710 right after filing this issue.

**Comment by juhp** [comment]
FWIW I see the same error with a toolbox created from `quay.io/centos/centos:stream9-development`.

**Comment by debarshiray** [comment]
This was already fixed by https://github.com/containers/toolbox/pull/794 in Toolbox 0.0.99.2.

**Comment by juhp** [comment]
Thank you!

Mm probably I was seeing a different problem: I see now that centos:stream9 does have /etc/machine-id.
I can open a new issue for that. (I noticed that centos:stream9 has an empty /etc/machine-id file,
though the same is true for fedora:35 unlike `fedora-toolbox:35`.)

On the other hand `--image centos:stream8` is working well!

**Comment by juhp** [comment]
Also I confirmed that archlinux now works, so that is great. :+1:
