### ISSUE TITLE
rename master branch to main?

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#740]
As part of "conscious language" efforts it would be appropriate to rename the `master` branch to `main`.

On the github side at least it is a very straightforward one-click change in the web project settings,
though of course there may possibly be other tweaks needed like CI scripts etc.

**Comment by debarshiray** [comment]
Yes, we should do this. I was actually discussing this (offline) with @HarryMichal some months ago, and I wasn't aware that it's so easy to implement.

**Comment by debarshiray** [comment]
This is done.

I was hoping that there would be a way to have an alias to `main` on the server-side, that's equivalent to:
```
$ git symbolic-ref refs/heads/master refs/heads/main
```

However, it seems like GitHub doesn't offer a way to do that. So, the following steps are necessary to update your local clones:
```
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a
```

**Comment by juhp** [comment]
Thank you!
