### ISSUE TITLE
UBI images not listed as toolbox images

### ISSUE THREAD

**Issue by HarryMichal** [containers/toolbox#753]
**Describe the bug**
When a [UBI]() image is present on a host machine, it is not listed in the output of `toolbox list`.

**Steps how to reproduce the behaviour**

1. Pull an UBI image - `podman pull registry.access.redhat.com/ubi8/ubi`
2. `toolbox list`

**Expected behaviour**

UBI image is shown in the output.

**Actual behaviour**

UBI image is not shown in the output.

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.1`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.1-1.fc35.x86_64`

**Output of `podman version`**
```
Version:      3.1.0-dev
API Version:  3.0.0
Go Version:   go1.16
Built:        Mon Feb 22 23:40:29 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.1.0-0.42.dev.gitd999328.fc35.x86_64`

**Info about your OS**
Fedora Silverblue Rawhide

**Comment by vorburger** [comment]
Isn't this simply because `registry.access.redhat.com/ubi8/ubi` doesn't have a ` com.github.containers.toolbox="true"` tag, and thus is not a "valid" toolbox container image, jut like any others you may have pulled, as per https://github.com/containers/toolbox#image-requirements? (Or does it? I have not checked.)

**Comment by HarryMichal** [comment]
> Isn't this simply because `registry.access.redhat.com/ubi8/ubi` doesn't have a ` com.github.containers.toolbox="true"` tag, and thus is not a "valid" toolbox container image, jut like any others you may have pulled, as per https://github.com/containers/toolbox#image-requirements? (Or does it? I have not checked.)

Yes, that is correct. Though I'm unsure whether UBI maintainers will like the idea of adding a yet-another-label to the image. I don't think Toolbox is that critical to them. I'm thinking more about allow listing one of their labels.

**Comment by debarshiray** [comment]
There's a chance that we might get an OCI image designed specifically for Toolbox that's created out of the UBI RPM repositories. Much like `fedora-toolbox`. Currently, UBI is optimized for generic container use-cases and values smaller size over a nice interactive user experience. eg., it uses `coreutils-single`, doesn't have `sudo`, `man-db` or `vte-profile` installed by default, etc..

If that happens, we might also be able to add our own labels to it.
