### ISSUE TITLE
passthrough /usr/local

### ISSUE THREAD

**Issue by bam80** [containers/toolbox#755]
`/usr/local` dir usually doesn't have anything useful in the container images.
In the other hand, one might install something useful there on host.
So I wonder if it could be passed through from the host, so stuff there would be accessible from the containers?

**Comment by erazemk** [comment]
Try symlinking or moving stuff from `/usr/local` to `$HOME/.local` if you want to use it in a container, since `/usr/local` is usually for system-wide stuff.

**Comment by mfocko** [comment]
I too would be careful about `/usr/local`. I have tried to isolate Rust with Cargo in the toolbox and decided to go for `/usr/local` as home for cargo and rustup

(but it's true I could've used `/opt` too…)

**Comment by debarshiray** [comment]
If you really do want to access `/usr/local` from the host inside your Toolbox container, you can always find it under `/run/host/usr/local`.

In current `toolbox.git`, we actually bind mount the entire `/` from the host into the container's `/run/host`, so going forward even things like `/opt` should be present in there.

You can `mount --rbind` these custom locations in your bash start-up scripts by looking for `/run/.toolboxenv`. In the future we might offer doing such things through the `toolbox.conf` configuration file.

**Comment by debarshiray** [comment]
Closing.

Thanks for stopping by! :)
