### ISSUE TITLE
Toolbox incompatible with fancy fish prompts?

### ISSUE THREAD

**Issue by Yajo** [containers/toolbox#756]
**Describe the bug**
When entering toolbox, fancy [fish](https://fishshell.com/) prompts break.

**Steps how to reproduce the behaviour**
1. Install fish.
2. Set it as your shell
3. Do the same inside your toolbox.
3. Install https://github.com/jorgebucaran/fisher (this will help installing other prompts)
4. `fisher install IlanCosman/tide`
5. `tide configure`
6. Make some choices. Be as fancy as possible.
5. `toolbox enter`

**Expected behaviour**
The shell should look nice, no matter if inside or outside the toolbox, as the fish version is the same on both sides.

**Actual behaviour**
If you run `fish configure` outside of the toolbox, when you enter the toolbox it looks awful. However, if you run it within the toolbox, it will look awful when you get out:

**Screenshots**
![](https://user-images.githubusercontent.com/973709/115266679-50247200-a130-11eb-9c49-6918b8d197ec.png)

**Output of `toolbox --version` (v0.0.90+)**
e.g., `toolbox version 0.0.99.1`

**Toolbox package info (`rpm -q toolbox`)**
e.g., `toolbox-0.0.99.1-1.fc33.x86_64`

**Output of `podman version`**
e.g.,
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 16:56:17 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
e.g., `podman-3.0.1-1.fc33.x86_64`

**Info about your OS**
e.g., Fedora Silverblue 33

**Additional context**
Check https://github.com/IlanCosman/tide/issues/146 for more details. Initially I thought it would be a prompt bug, but similar stuff happens if uninstalling `tide` and installing `oh-my-fish/theme-bobthefish`:

<pre><font color="#5FD700">❯</font> <font color="#005FD7">toolbox</font> <font color="#00AFFF">list</font> <font color="#00AFFF">-i</font>
IMAGE ID      IMAGE NAME                                    CREATED
675192cc4238  registry.fedoraproject.org/fedora-toolbox:33  7 weeks ago
</pre>

**Comment by debarshiray** [comment]
> Check IlanCosman/tide#146 for more details. Initially I thought
> it would be a prompt bug, but similar stuff happens if uninstalling
> tide and installing oh-my-fish/theme-bobthefish

It doesn't have any details to actually narrow down the problem. :)

It might be because of the purple ⬢ that Toolbox prefixes to the shell's primary prompt (ie., `PS1`). That happens in `profile.d/toolbox.sh` that gets installed in `/etc/profile.d/toolbox.sh`. You could try playing with that.

**Comment by debarshiray** [comment]
As per https://github.com/IlanCosman/tide/issues/146, this is now fixed.

**Comment by debarshiray** [comment]
Thanks for digging into the issue in such detail and helping resolve it!
