### ISSUE TITLE
Unable to start container after update **podman 2:3.1.2-1.fc34 -> 2:3.2.0-0.1.rc1.fc34**

### ISSUE THREAD

**Issue by Ma3yTa** [containers/toolbox#760]
**Describe the bug**
Unable to start container after update **podman 2:3.1.2-1.fc34 -> 2:3.2.0-0.1.rc1.fc34**

<details>
  <summary>[ma3yta@localhost ~]$ podman start --attach dotnet --log-level debug (Click to expand)</summary>
  <pre><font color="#2AA1B3">INFO</font>[0000] podman filtering at log level debug          
<font color="#D0CFCC">DEBU</font>[0000] Called start.PersistentPreRunE(podman start --attach dotnet --log-level debug) 
<font color="#D0CFCC">DEBU</font>[0000] Merged system config &quot;/usr/share/containers/containers.conf&quot; 
<font color="#D0CFCC">DEBU</font>[0000] Using conmon: &quot;/usr/bin/conmon&quot;              
<font color="#D0CFCC">DEBU</font>[0000] Initializing boltdb state at /var/home/ma3yta/.local/share/containers/storage/libpod/bolt_state.db 
<font color="#D0CFCC">DEBU</font>[0000] Using graph driver overlay                   
<font color="#D0CFCC">DEBU</font>[0000] Using graph root /var/home/ma3yta/.local/share/containers/storage 
<font color="#D0CFCC">DEBU</font>[0000] Using run root /run/user/1000/containers     
<font color="#D0CFCC">DEBU</font>[0000] Using static dir /var/home/ma3yta/.local/share/containers/storage/libpod 
<font color="#D0CFCC">DEBU</font>[0000] Using tmp dir /run/user/1000/libpod/tmp      
<font color="#D0CFCC">DEBU</font>[0000] Using volume path /var/home/ma3yta/.local/share/containers/storage/volumes 
<font color="#D0CFCC">DEBU</font>[0000] Set libpod namespace to &quot;&quot;                   
<font color="#D0CFCC">DEBU</font>[0000] Not configuring container store              
<font color="#D0CFCC">DEBU</font>[0000] Initializing event backend journald          
<font color="#D0CFCC">DEBU</font>[0000] configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
<font color="#D0CFCC">DEBU</font>[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
<font color="#D0CFCC">DEBU</font>[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
<font color="#D0CFCC">DEBU</font>[0000] Using OCI runtime &quot;/usr/bin/crun&quot;            
<font color="#D0CFCC">DEBU</font>[0000] Default CNI network name podman is unchangeable 
<font color="#2AA1B3">INFO</font>[0000] Setting parallel job count to 25             
<font color="#2AA1B3">INFO</font>[0000] podman filtering at log level debug          
<font color="#D0CFCC">DEBU</font>[0000] Called start.PersistentPreRunE(podman start --attach dotnet --log-level debug) 
<font color="#D0CFCC">DEBU</font>[0000] overlay storage already configured with a mount-program 
<font color="#D0CFCC">DEBU</font>[0000] Merged system config &quot;/usr/share/containers/containers.conf&quot; 
<font color="#D0CFCC">DEBU</font>[0000] overlay storage already configured with a mount-program 
<font color="#D0CFCC">DEBU</font>[0000] Using conmon: &quot;/usr/bin/conmon&quot;              
<font color="#D0CFCC">DEBU</font>[0000] Initializing boltdb state at /var/home/ma3yta/.local/share/containers/storage/libpod/bolt_state.db 
<font color="#D0CFCC">DEBU</font>[0000] Using graph driver overlay                   
<font color="#D0CFCC">DEBU</font>[0000] Using graph root /var/home/ma3yta/.local/share/containers/storage 
<font color="#D0CFCC">DEBU</font>[0000] Using run root /run/user/1000/containers     
<font color="#D0CFCC">DEBU</font>[0000] Using static dir /var/home/ma3yta/.local/share/containers/storage/libpod 
<font color="#D0CFCC">DEBU</font>[0000] Using tmp dir /run/user/1000/libpod/tmp      
<font color="#D0CFCC">DEBU</font>[0000] Using volume path /var/home/ma3yta/.local/share/containers/storage/volumes 
<font color="#D0CFCC">DEBU</font>[0000] overlay storage already configured with a mount-program 
<font color="#D0CFCC">DEBU</font>[0000] Set libpod namespace to &quot;&quot;                   
<font color="#D0CFCC">DEBU</font>[0000] [graphdriver] trying provided driver &quot;overlay&quot; 
<font color="#D0CFCC">DEBU</font>[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
<font color="#D0CFCC">DEBU</font>[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
<font color="#D0CFCC">DEBU</font>[0000] Initializing event backend journald          
<font color="#D0CFCC">DEBU</font>[0000] configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
<font color="#D0CFCC">DEBU</font>[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
<font color="#D0CFCC">DEBU</font>[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
<font color="#D0CFCC">DEBU</font>[0000] Using OCI runtime &quot;/usr/bin/crun&quot;            
<font color="#D0CFCC">DEBU</font>[0000] Default CNI network name podman is unchangeable 
<font color="#2AA1B3">INFO</font>[0000] Setting parallel job count to 25             
<font color="#D0CFCC">DEBU</font>[0000] overlay: mount_data=,lowerdir=/var/home/ma3yta/.local/share/containers/storage/overlay/l/56QB4BQZ3IUKLISNMQW3Q4337D:/var/home/ma3yta/.local/share/containers/storage/overlay/l/YQU2LM4PUIJC5HZBXPALDHS5CB,upperdir=/var/home/ma3yta/.local/share/containers/storage/overlay/821be7b681919e10e491f72dd4cb2738860d609bfffa10ac88c652558a203070/diff,workdir=/var/home/ma3yta/.local/share/containers/storage/overlay/821be7b681919e10e491f72dd4cb2738860d609bfffa10ac88c652558a203070/work,context=&quot;system_u:object_r:container_file_t:s0:c460,c465&quot; 
<font color="#D0CFCC">DEBU</font>[0000] mounted container &quot;b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb&quot; at &quot;/var/home/ma3yta/.local/share/containers/storage/overlay/821be7b681919e10e491f72dd4cb2738860d609bfffa10ac88c652558a203070/merged&quot; 
<font color="#D0CFCC">DEBU</font>[0000] Created root filesystem for container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb at /var/home/ma3yta/.local/share/containers/storage/overlay/821be7b681919e10e491f72dd4cb2738860d609bfffa10ac88c652558a203070/merged 
<font color="#D0CFCC">DEBU</font>[0000] Workdir &quot;/&quot; resolved to host path &quot;/var/home/ma3yta/.local/share/containers/storage/overlay/821be7b681919e10e491f72dd4cb2738860d609bfffa10ac88c652558a203070/merged&quot; 
<font color="#D0CFCC">DEBU</font>[0000] Not modifying container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb /etc/passwd 
<font color="#D0CFCC">DEBU</font>[0000] Not modifying container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb /etc/group 
<font color="#D0CFCC">DEBU</font>[0000] /etc/system-fips does not exist on host, not mounting FIPS mode subscription 
<font color="#D0CFCC">DEBU</font>[0000] Setting CGroups for container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb to user.slice:libpod:b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb 
<font color="#D0CFCC">DEBU</font>[0000] set root propagation to &quot;rslave&quot;             
<font color="#D0CFCC">DEBU</font>[0000] reading hooks from /usr/share/containers/oci/hooks.d 
<font color="#D0CFCC">DEBU</font>[0000] Created OCI spec for container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb at /var/home/ma3yta/.local/share/containers/storage/overlay-containers/b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb/userdata/config.json 
<font color="#D0CFCC">DEBU</font>[0000] /usr/bin/conmon messages will be logged to syslog 
<font color="#D0CFCC">DEBU</font>[0000] running conmon: /usr/bin/conmon               <font color="#D0CFCC">args</font>=&quot;[--api-version 1 -c b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb -u b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb -r /usr/bin/crun -b /var/home/ma3yta/.local/share/containers/storage/overlay-containers/b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb/userdata -p  -n dotnet --exit-dir /run/user/1000/libpod/tmp/exits --full-attach -s -l k8s-file:/var/home/ma3yta/.local/share/containers/storage/overlay-containers/b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb/userdata/ctr.log --log-level debug --syslog --conmon-pidfile /run/user/1000/containers/overlay-containers/b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/home/ma3yta/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mount_program=/usr/bin/fuse-overlayfs --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb]&quot;
<font color="#2AA1B3">INFO</font>[0000] Running conmon under slice user.slice and unitName libpod-conmon-b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb.scope 
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

<font color="#D0CFCC">DEBU</font>[0000] Received: -1                                 
<font color="#D0CFCC">DEBU</font>[0000] Cleaning up container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb 
<font color="#D0CFCC">DEBU</font>[0000] Network is already cleaned up, skipping...   
<font color="#D0CFCC">DEBU</font>[0000] unmounted container &quot;b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb&quot; 
Error: unable to start container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb: opening file `` for writing: No such file or directory: OCI not found
</pre>
</details>

**Expected behaviour**
Containers works fine after update **podman 2:3.1.2-1.fc34 -> 2:3.2.0-0.1.rc1.fc34**

**Actual behaviour**
```
 podman start --attach dotnet --log-level debug
 Error: unable to start container b2a64907dbefb2a22240b94bc88bd0c92540895b7a392370efa0fc7dc601dceb: opening file `` for writing: No such file or directory: OCI not found
```
Works fine when create a new container but doesn't work for old containers.

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.1`

**Toolbox package info (`rpm -q toolbox`)**
``toolbox-0.0.99.1-1.fc34.x86_64``

**Output of `podman version`**
<pre>Version:      3.2.0-rc1
API Version:  3.2.0-rc1
Go Version:   go1.16.3
Built:        Thu May  6 04:03:46 2021
OS/Arch:      linux/amd64
</pre>

**Podman package info (`rpm -q podman`)**
``podman-3.2.0-0.1.rc1.fc34.x86_64``

**Info about your OS**
Fedora Silverblue 34

**Comment by Ma3yTa** [comment]
moved issue to podman repo https://github.com/containers/podman/issues/10274

**Comment by HarryMichal** [comment]
Thank you for reporting the issue, @Ma3yTa!

**Comment by anthr76** [comment]
FYI this regression seems to have made it's way back :)
