### ISSUE TITLE
Error: failed to get the Podman version inside Tilix flatpak

### ISSUE THREAD

**Issue by Ma3yTa** [containers/toolbox#770]
**Describe the bug**
``Error: failed to get the Podman version``  when entering container from Tilix flatpak version.

**Steps how to reproduce the behaviour**
1. open Tilix flatpak version
2. enter command ``toolbox enter``
3. error shown ``Error: failed to get the Podman version``

**Expected behaviour**
No error. Enter container.

**Actual behaviour**
Works fine from the gnome-terminal but getting an error when using Tilix flatpak version: ``Error: failed to get the Podman version``

**Screenshots**
![image](https://user-images.githubusercontent.com/660379/118916495-11cfcd80-b8fd-11eb-9114-981bdffeb893.png)

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.1`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.1-1.fc34.x86_64`

**Output of `podman version`**
```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Thu May 13 02:27:59 2021
OS/Arch:      linux/amd64

```
**Podman package info (`rpm -q podman`)**
`podman-3.1.2-3.fc34.x86_64`

**Info about your OS**
Fedora Silverblue 34

**Comment by Ma3yTa** [comment]
## Tilix output for ``podman version --format json``
```bash
Error: kernel does not support overlay fs: 'overlay' is not supported over btrfs 
at "/var/home/ma3yta/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver

```

## Gnome Termonal output for ``podman version --format json``
```bash
{"Client":{"APIVersion":"3.1.2","Version":"3.1.2","GoVersion":"go1.16.3","GitCommit":"","BuiltTime":"Thu May 13 02:27:59 2021","Built":1620847679,"OsArch":"linux/amd64"}}
```

**Comment by Ma3yTa** [comment]
moved to podman repo https://github.com/containers/podman/issues/10438

**Comment by debarshiray** [comment]
Or were you using the Flatpak:ed version of the Tilix app to run Toolbox?
