### ISSUE TITLE
Allow support of non-GNU distros (introduce a static binary?)

### ISSUE THREAD

**Issue by nickavem** [containers/toolbox#772]
**Is your feature request related to a problem? Please describe.**
Right now the toolbox binary is dynamically linked:
```
/usr/bin/toolbox: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f906e6e328b8ae7640b80a674713877e7cea2af5, for GNU/Linux 3.2.0, stripped
```
This makes it only useable with GNU/Linux guests.

**Describe the solution you'd like**
Introduce a static binary. I believe this should be fully doable with the Go language.

**Describe alternatives you've considered**
Create a musl compatible binary
Provide a mode to also automatically install required interpreters on non-GNU guests

**Comment by anthr76** [comment]
Would be awesome to have this for mac, but then podman is lacking. Toolbox seems pretty closely integrated with Linux. Nonetheless it would be cool to see a statically built binary.

**Comment by HarryMichal** [comment]
There was an effort for having Toolbox build statically in the [past](https://github.com/containers/toolbox/pull/531). @debarshiray had some thoughts that made us decide against the decision. Maybe it's time to revisit this decision.

**Comment by debarshiray** [comment]
Since https://github.com/containers/toolbox/pull/897 we run the `/usr/bin/toolbox` binary against the host's run-time, even for the `init-container` command inside the container.  That should make it possible to use it with containers that have a different run-time implementation than the host.  eg., musl versus glibc.

**Comment by debarshiray** [comment]
Thanks for stopping by.
