### ISSUE TITLE
remove --very-verbose option from bash-completions

### ISSUE THREAD

**Issue by juhp** [containers/toolbox#788]
**Describe the bug**
toolbox no longer supports the `--very-verbose` option but it is still surfaced by the bash-completions file.
So it would be good to remove it completely there.

**Steps how to reproduce the behaviour**
1. in bash type: `toolbox -- TAB` 

**Expected behaviour**
--very-verbose not to be listed as a completion since toolbox does not recognize it.

**Actual behaviour**
--very-verbose is listed in the options completion list,
but using it gives an "unknown option" error: rather confusing.

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.90.1`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.1-1.fc34.x86_64`

**Info about your OS**
Fedora Silverblue 34

**Comment by HarryMichal** [comment]
Thanks for the report! I believe this has already been addressed by https://github.com/containers/toolbox/pull/720. Now we just need to make a release. But I see a one more mention of `--very-verbose` in the completion script, so I'll remove it, too.
