### ISSUE TITLE
Toolbox - any linux distro inside.

### ISSUE THREAD

**Issue by chiddekel** [containers/toolbox#789]
Add support to choice more distro Linux  - Debian, Ubuntu, Arch, Gentoo, Opensuse, etc.

**Comment by anthr76** [comment]
Hi @chiddekel I've been using my own custom built toolboxes for quite awhile and it works great. 

It's documented how to create your own and you can have the flexibility to have any distro you choose.

**Comment by chiddekel** [comment]
Is a this one: https://github.com/anthr76/toolbox ?

**Comment by anthr76** [comment]
Indeed.

**Comment by anthr76** [comment]
No but this is. https://github.com/anthr76/tooling

**Comment by fedelibre** [comment]
toolbox-create manual might be more clear in the OPTIONS section.

IIUC, --distro currently supports only Fedora and RHEL, see [here](https://github.com/containers/toolbox/blob/main/src/pkg/utils/utils.go#L94). A command option to list the currently supported distros would be helpful IMO.

So the `--image` option is useful also to create containers for distros not currently supported by toolbox. This might be obvious to you but not to the common user like me. or building a toolbox container from an ubuntu docker image is not guaranteed to work fine?

This sentence might be improved:

> --image NAME, -i NAME
>
>       Change the NAME of the base image used to create the toolbox container. This is useful for creating containers from custom-built base images.

**Comment by erazemk** [comment]
It's listed in the [Contributing guide](https://github.com/containers/toolbox/wiki/Contributing#first-contribution) that this is a feature that the toolbox developers want as well (under "Play with custom images"), it's just that no-one has submitted a finished image for a different distro. There are a few opened pull requests though, like #742 for Debian, #483 for Ubuntu and #861 for Arch (plus others with the [images label](https://github.com/containers/toolbox/labels/2.%20Images)).

Creating your own image isn't that hard, you can use the existing Fedora images as a template and work from there.

**Comment by tommytran732** [comment]
What about the RHEL image? If I remember correctly there are fully working RHEL images on Red Hat's registries. Maybe we could build CentOS Stream/Alma/Rocky images based on that?

**Comment by debarshiray** [comment]
I agree with everything that @anthr76 and @erazemk said.

> What about the RHEL images?

As @fedelibre already found out, you can use something like `toolbox create --distro rhel --version 8.4` to create RHEL containers using UBI.

**Comment by debarshiray** [comment]
I am going to close this now because this issue is too broad to be actionable.

Let's focus on the individual issues for each distribution. It mainly needs people to step up to maintain the images long-term. Ideally, it would be someone who already works on the corresponding distribution.
