### ISSUE TITLE
How to access drive block device via smartctl?

### ISSUE THREAD

**Issue by rugk** [containers/toolbox#803]
**Is your feature request related to a problem? Please describe.**
I want to use a toolbox to do a SMART analysis of a (external) disk.

I thus enter the toolbox, install `smartmontools` and run:
```
$ smartctl --info /dev/disk/[…]
smartctl 7.2 2021-01-17 r5171 [x86_64-linux-5.12.7-300.fc34.x86_64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

Smartctl open device: /dev/disk/[…] failed: Permission denied
```

If I run that as a user, it does not work.

If I run a toolbox as root, it does not work, too, however:
```
# smartctl --info /dev/disk/[…]
smartctl 7.2 2021-01-17 r5171 [x86_64-linux-5.12.7-300.fc34.x86_64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

Smartctl open device: /dev/disk/[…] failed: INQUIRY failed
```

https://github.com/containers/toolbox/pull/78 gave access to the mounted devices AFAIK. But what about the block device?

**Describe the solution you'd like**
Access block device…

**Describe alternatives you've considered**
I did not really want to create my own Docker container for this task…

**Additional context**

**Comment by olivergs** [comment]
I've tried to do what you told, and If I create the toolbox as root, I'm able to get the information for the disk:

[oliver@t480s ~]$ sudo toolbox enter
Error: directory /home/oliver not found in container fedora-toolbox-34
Using /root instead.

Welcome to the Toolbox; a container where you can install and run
all your tools.

 - Use DNF in the usual manner to install command line tools.
 - To create a new tools container, run 'toolbox create'.

For more information, see the documentation.

⬢[root@toolbox ~]# sudo dnf install smartmontools
Fedora 34 - x86_64                                                                                                    19 MB/s |  74 MB     00:03    
Fedora 34 openh264 (From Cisco) - x86_64                                                                             1.5 kB/s | 2.5 kB     00:01    
Fedora Modular 34 - x86_64                                                                                           2.4 MB/s | 4.9 MB     00:02    
Fedora 34 - x86_64 - Updates                                                                                         3.7 MB/s |  20 MB     00:05    
Fedora Modular 34 - x86_64 - Updates                                                                                 2.9 MB/s | 4.4 MB     00:01    
Dependencies resolved.
=====================================================================================================================================================
 Package                                Architecture                    Version                                Repository                       Size
=====================================================================================================================================================
Installing:
 smartmontools                          x86_64                          1:7.2-3.fc34                           fedora                          557 k

Transaction Summary
=====================================================================================================================================================
Install  1 Package

Total download size: 557 k
Installed size: 1.9 M
Is this ok [y/N]: y
Downloading Packages:
smartmontools-7.2-3.fc34.x86_64.rpm                                                                                  661 kB/s | 557 kB     00:00    
-----------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                395 kB/s | 557 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                             1/1 
  Installing       : smartmontools-1:7.2-3.fc34.x86_64                                                                                           1/1 
  Running scriptlet: smartmontools-1:7.2-3.fc34.x86_64                                                                                           1/1 
Created symlink /etc/systemd/system/multi-user.target.wants/smartd.service → /usr/lib/systemd/system/smartd.service.

  Verifying        : smartmontools-1:7.2-3.fc34.x86_64                                                                                           1/1 

Installed:
  smartmontools-1:7.2-3.fc34.x86_64                                                                                                                  

Complete!
⬢[root@toolbox ~]# smartctl --info /dev/disk/by-id/nvme-eui.002538b881b5a611
smartctl 7.2 2021-01-17 r5171 [x86_64-linux-5.12.9-300.fc34.x86_64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       SAMSUNG XXXXXXXX
Serial Number:                      XXXXXXXXXXX
Firmware Version:                   5L7QCXB7
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 256,060,514,304 [256 GB]
Unallocated NVM Capacity:           0
Controller ID:                      2
NVMe Version:                       1.2
Number of Namespaces:               1
Namespace 1 Size/Capacity:          256,060,514,304 [256 GB]
Namespace 1 Utilization:            222,978,158,592 [222 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            002538 b881b5a611
Local Time is:                      Mon Jul 12 12:59:07 2021 WEST

**Comment by rugk** [comment]
Thanks!
