### ISSUE TITLE
cannot run ether-wake from a toolbox

### ISSUE THREAD

**Issue by fedelibre** [containers/toolbox#805]
I'm on Fedora 34 Silverblue.

I'm trying to Wake On Lan (WoL) a computer in my LAN.
As `net-tools` is not part of Silverblue, I installed it in a toolbox, but when I try to run it I always get the same reply "This program must be run as root", **even though I am running it as root**.

If I install net-tools in my system (as overlayed package), then ether-wake works fine.

net-tools version on my system and in the container is the same:
```
$ rpm -q net-tools
net-tools-2.0-0.59.20160912git.fc34.x86_64
```

Here's the ether-wake output in the toolbox:

```
⬢[fede@toolbox ~]$ sudo ether-wake D4:3D:7E:42:DC:56
ether-wake: This program must be run as root.

⬢[root@toolbox ~]# ether-wake D4:3D:7E:42:DC:56
ether-wake: This program must be run as root.
⬢[root@toolbox ~]# whoami
root
```

My system versions:

```
$ toolbox --version
toolbox version 0.0.99.1

$ rpm -q toolbox
toolbox-0.0.99.1-1.fc34.x86_64

$ podman version
Version:      3.2.0
API Version:  3.2.0
Go Version:   go1.16.3
Built:        Wed Jun  9 16:24:16 2021
OS/Arch:      linux/amd64

$ rpm -q podman
podman-3.2.0-5.fc34.x86_64
```

**Comment by HarryMichal** [comment]
Hi @fedelibre! A toolbox created with `toolbox create` is a so-called "rootless container". It is a container created with privileges of your user not any higher. Running a command with `sudo` or as root inside of the container does not give you privileges equal to the root user on your system. Try to create a container as root (e.g. `sudo toolbox create`), install the package in it and try to run the command again.

**Comment by fedelibre** [comment]
Thanks @HarryMichal ! Your solution works. It's not a bug.

I've just realized also that the `wol` package provides a similar tool which does not require root privileges.
