### ISSUE TITLE
Using `toolbox run` in a pipeline sometimes leaves tty in wrong state

### ISSUE THREAD

**Issue by GregoryHinton** [containers/toolbox#848]
**Description**
Using `toolbox run` in a pipeline sometimes leaves the tty with echo and other settings disabled.
The `stty sane` command must be issued to return the tty to normal.
For example, the command
```
    $ toolbox run echo hello | awk ''
```
will cause this to occur.

**Steps to reproduce**
```
1. toolbox create
2. stty -a >stty.before
3. toolbox run echo hello | awk ''; stty -a >stty.after; stty sane
4. diff stty.before stty.after
```

**Expected behaviour**
The `diff` command from step 4 above should have no output, i.e. the tty should be in
the same state as before the `toolbox run` command.

**Actual behaviour**
The following `stty -a` settings are changed:
```
icrnl --> -icrnl
opost --> -opost
isig --> -isig
icanon --> -icanon
iexten --> -iexten
echo --> -echo
```

**Output of `toolbox --version` (v0.0.90+)**
```
toolbox version 0.0.99.2
```

**Toolbox package info (`rpm -q toolbox`)**
```
toolbox-0.0.99.2-1.fc34.x86_64
```

**Output of `podman version`**
```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.16.4
Built:        Fri Jun 25 16:49:19 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
```
podman-3.2.2-1.fc34.x86_64
```

**Info about your OS**
```
$ head -2 /etc/os-release 
NAME=Fedora
VERSION="34.20210721.0 (Silverblue)"
```

**Additional context**
This may be related to [#157](https://github.com/containers/toolbox/issues/157).

I have not seen this bug occur when `sed` is used as the second stage in the pipeline.
For some reason, `awk` is particularly vulnerable.

I have confirmed that each line of the `toolbox run` output is terminated with CRLF 
instead of just LF. I thought this might be confusing `awk`; but when a hand-built file 
terminated with CRLF is piped it into `awk`, it works just fine.

I have seen no problems when I use `podman exec` for the first stage of the pipeline 
(with or without the `-it` flags). Doesn't `toolbox run` just do some initial checking and then 
run `podman exec`?

I also reported this bug at [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1983378).

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/157
