### ISSUE TITLE
No default toolchain configured in Gnome Builder with Rustup

### ISSUE THREAD

**Issue by Ayush1325** [containers/toolbox#859]
Gnome Builder has support for Toolbox containers by default. 
However, when rust is installed using rustup, Gnome Builder cannot find rustc installed in the container.
Running `toolbox run -c container rustc` gives the following error:
```
/bin/sh: line 1: exec: rustc: not found
Error: command rustc not found in container emacs
```

# Steps how to reproduce the behaviour
1. Install GNOME Builder from flathub
1. Install rustup with installer from [Instructions](https://rustup.rs/) (you may need exit and re-enter a container for reloading PATH)
1. Install clang too (because of cc linker)
1. Create a new project with cargo new
1. Open that project in Builder
1. Set build runtime to Container->Toolbox->mycontainer
1. Click run

# System Information
```
toolbox version 0.0.99.2
podman version 3.2.3
OS: Fedora Workstation 34
```

# Additional Context
This issue does not occur if rustc and cargo are installed inside the toolbox as system packages.
There is also an open issue in the gnome-builder [here](https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/1190) but it does not have any activity.

**Comment by olivergs** [comment]
Most probably this problem occurs because the install sets the path for rustc in .bashrc or similar config file. When you run toolbox it mounts the user home as the home inside the container, so you get the same configuration you have outside. That can confuse the paths for bash.

**Comment by Ayush1325** [comment]
@olivergs Thanks. Fixed it by passing build environment variable.

**Comment by Ayush1325** [comment]
Well, the building part is now working, however, the program still doesn't run. I get the error:
```
Error: open executable: Permission denied: OCI permission denied
```
I don't see any other logs.

**Comment by Ayush1325** [comment]
Well, in the end, I was able to get things working by using flatpak runtime instead of container.

**Comment by olivergs** [comment]
Glad it worked. Thanks for the information and thanks for reporting.
