### ISSUE TITLE
[FRE] desktop integration

### ISSUE THREAD

**Issue by allaeddineomc** [containers/toolbox#870]
**Is your feature request related to a problem? Please describe.**
when i install a graphical .rpm app in toolbox it doesn't create a desktop entry  it will be great if you add a way to synchronize .desktop files from guest's /usr/share/applications to host's ~/.local.share.applications with adding "toolbox run --container $CONTAINER " in front of the exec line , i'm already doing this manually but i think automating it will be more convenient 

**Describe alternatives you've considered**
an alternative is to make an external script that can be installed inside to container to do the work instead of putting the work in toolbox itself

**Comment by kuba3351** [comment]
Hello

I think it is not simple because when you delete a container, you will have a lot of useless .desktop files, so if you delete a lot containers, your desktop shortcuts will be a mess.

I think it is possible only if `toolbox em` will search and delete .desktop files that points to the container.

I prefer installing GUI apps in flatpak rather than toolbox, because it has better desktop shortcuts handing.

**Comment by allaeddineomc** [comment]
It's not to replace flatpak but to work alongside with it , there are a lot of useful apps that don't have a flatpak and may never have like nomachine and google chrome , mostly proprietary software that work only as a distro package or a snap

**Comment by erazemk** [comment]
Could toolbox not just symlink its /usr/share/applications to /usr/share/applications/toolbox on the host and remove the symlink when the container is deleted?

**Comment by alvarlagerlof** [comment]
> Could toolbox not just symlink its /usr/share/applications to /usr/share/applications/toolbox on the host and remove the symlink when the container is deleted?

Yeah exactly. A seperate folder with maybe subfolders for each container would make it clear where it comes from.

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/417
