### ISSUE TITLE
[RFE] Do not clear the terminal output when exiting a toolbox

### ISSUE THREAD

**Issue by travier** [containers/toolbox#877]
**Is your feature request related to a problem? Please describe.**

Exiting a toolbox currently clear out the entire terminal output, making this not ideal for one shot commands for example.

**Describe the solution you'd like**

Do not clear terminal on exit.

**Describe alternatives you've considered**

Nothing that I know of.

**Additional context**

N/A

**Comment by olivergs** [comment]
Hi  @travier 

I've tried to run a command and my output does not get cleared.

```
[oliver@t480s ~]$ toolbox create --distro fedora --release 34
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:34 (500MB)? [y/N]: y
Created container: fedora-toolbox-34
Enter with: toolbox enter fedora-toolbox-34
[oliver@t480s ~]$ toolbox run --container fedora-toolbox-34 ls /
README.md  bin	boot  dev  etc	home  lib  lib64  lost+found  media  mnt  opt  proc  root  run	sbin  srv  sys	tmp  usr  var
```

Can you please tell what's the exact command and image you're using?

**Comment by debarshiray** [comment]
@travier which shell were you using?

**Comment by travier** [comment]
Oh, this does not happen with bash but does with ZSH. Looking if this is something in my config.

**Comment by travier** [comment]
OK, this comes from `/etc/zlogout` so this has nothing to do with toolbox. Sorry for the noise.

**Comment by travier** [comment]
Note for those coming later to this one: The shell used inside the container matters here, not the one outside.

**Comment by debarshiray** [comment]
I see. Thanks for clearing that up. :)
