### ISSUE TITLE
.local/share/containers/storage/overlay owned by incorrect user

### ISSUE THREAD

**Issue by chergert** [containers/toolbox#880]
On a new Fedora 35 install, I created a new F35 toolbox with `toolbox create`.

When trying to get symbol decoding working in Sysprof, I noticed that `.local/share/containers/storage/overlay` is owned by user id `100000` while everything else is `1000 (christian)`.

Interestingly, everything within that directory is owned by `christian`, so a chown seems to work fine.

```
[christian@workstation storage]$ toolbox --version 
toolbox version 0.0.99.2
```

**Comment by debarshiray** [comment]
Did this get fixed on the way? With Podman 3.4.0, I see:
```
[rishi@kolache ~]$ ls -l ~/.local/share/containers/storage
total 36
drwx------.  2 rishi rishi 4096 Oct 15 12:43 libpod
drwx------.  2 rishi rishi 4096 Oct 15 12:43 mounts
drwx------. 24 rishi rishi 4096 Nov 16 23:13 overlay
drwx------.  3 rishi rishi 4096 Nov 16 21:57 overlay-containers
drwx------.  9 rishi rishi 4096 Nov 16 23:13 overlay-images
drwx------.  2 rishi rishi 4096 Nov 16 23:13 overlay-layers
drwx------.  2 rishi rishi 4096 Oct 15 12:54 secrets
-rw-r--r--.  1 rishi rishi   64 Nov 15 14:36 storage.lock
drwx------.  2 rishi rishi 4096 Oct 15 12:43 tmp
-rw-r--r--.  1 rishi rishi    0 Oct 15 12:43 userns.lock
```

If this is still an issue, please report it against github.com/containers/podman

**Comment by juhp** [comment]
I still see it in my current SB35 VM - even after removing `~/.local/share/containers/storage/`.

```shellsession
$ ls .local/share/containers/storage/overlay -ld
drwx------. 1 100000 100000 550 Nov 17 12:24 .local/share/containers/storage/overlay
```

**Comment by juhp** [comment]
So I did some "binary bissect" testing in Fedora Live images and this behavior changed between:
F34-WORK-x86_64-LIVE-20210514.iso and F34-WORK-x86_64-LIVE-20210615.iso
(ie Fedora 34 GA was not affected).

F34-WORK-x86_64-LIVE-20210514 has:
```
$ rpm -q podman containers-common toolbox
podman-3.2.0-0.1.rc1.fc34.x86_64
containers-common-1-16.fc34.noarch
toolbox-0.0.99.2-7.fc34.x86_64
$ ls -ldZ .local/share/containers/storage/overlay
drwx------. 6 liveuser liveuser unconfined_u:object_r:data_home_t:s0 4096 Nov 18 01:17 .local/share/containers/storage/overlay
```
vs

F34-WORK-x86_64-LIVE-20210615:
```
$ rpm -q podman containers-common toolbox
podman-3.2.0-5.fc34.x86_64
containers-common-1-19.fc34.noarch
toolbox-0.0.99.2-7.fc34.x86_64
$ ls -ldZ .local/share/containers/storage/overlay
drwx------. 7 100000 100000 unconfined_u:object_r:container_ro_file_t:s0 4096 Nov 18 01:25 .local/share/containers/storage/overlay
```

**Comment by debarshiray** [comment]
> So I did some "binary bissect" testing in Fedora Live images

Oh, wow! Thanks for digging into this in such detail, @juhp !

**Comment by debarshiray** [comment]
> eg after running podman run -it --rm fedora:35, overlay/
> is owned by user, but after fresh toolbox enter the owner
> is now 10000: it would be good to come up with a minimal
> reproducer without toolbox I guess...

Maybe try adding `--userns=keep-id` ?

**Comment by juhp** [comment]
> --userns=keep-id

That does indeed seem to do it!
So that is the trivial reproducer, thanks

(It had also crossed my mind that it might well be something like this.
All just simple brute force testing: quite straightforward:
just boot Live image and run podman and install/run toolbox, very easy.:)

**Comment by debarshiray** [comment]
> All just simple brute force testing: quite straightforward:
> just boot Live image and run podman and install/run toolbox,
> all very easy.:)

Everything seems easy once someone has already done it. :)

Thanks for taking the time to dig in.

**Comment by chergert** [comment]
This is still happening on Fedora 36 branched, I had to `sudo chown christian:christian $HOME/.local/share/contains/storage/overlay` today (it was 100000:100000 again)  to get access to the contents from Builder so it could provide toolbox/podman integration.

Should I reopen this?

**Comment by chergert** [comment]
I don't think I had podman-4.0 yet, but it's also possible that I was expecting it to fix whatever podman had broken previously and that just isn't the case.

I guess I was hoping that we wouldn't have to go tell GNOME Builder users they need to go `chown` something to unbreak their systems.

**Comment by phpcitizen** [comment]
fedora still creates folders with 100000:100000?

**Comment by chergert** [comment]
After performing a `podman system reset`, I'm getting `100000:100000` again.
