### ISSUE TITLE
Nice domain for the toolbox website

### ISSUE THREAD

**Issue by jimmac** [containers/toolbox#883]
Currently the website is deployed to the temporary https://containers.github.io/toolbox/

We need a short memorable domain for the project.

**Comment by ma3yta** [comment]
toolbox.dev

**Comment by jimmac** [comment]
Domain has been acquired.

**Comment by HarryMichal** [comment]
> Domain has been acquired.

For the sake of history, what is the acquired domain?

**Comment by mfocko** [comment]
> For the sake of history, what is the acquired domain?

this one containertoolbx.org?

**Comment by debarshiray** [comment]
Yes, it's containertoolbx.org  :)
