### ISSUE TITLE
Add Zsh Completions

### ISSUE THREAD

**Issue by gotmax23** [containers/toolbox#910]
Hi Toolbox developers,

**Is your feature request related to a problem? Please describe.**

I am a Zsh user. One of the best features of Zsh is its powerful tab completion support. Toolbox provides Bash completion support but not Zsh completion support.

**Describe the solution you'd like**
Could you please consider adding Zsh completion support?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks,
Maxwell

**Comment by gotmax23** [comment]
It looks like this is a duplicate of #836. Should I close this issue?

**Comment by HarryMichal** [comment]
Hi @gotmax23! Yes, this request has already been discussed and there even is a prototype solution available. It just has to be completed. I'll close the ticket for you. Thanks for stopping by.

**Comment by debarshiray** [comment]
Duplicate of https://github.com/containers/toolbox/issues/836
