### ISSUE TITLE
toolbox incorrectly attaching to debug pod

### ISSUE THREAD

**Issue by wgahnagl** [containers/toolbox#919]
**Describe the bug**
Once "toolbox" is executed on an OpenShift Container Platform Node, all further "toolbox" executions place users in the "debug" Pod instead of the toolbox Pod as expected.

this is copied over from a bugzilla bug here ! 
https://bugzilla.redhat.com/show_bug.cgi?id=2001927 

we think it might not be an openshift bug but a toolbox bug!

$ oc debug node/ip-10-0-148-127.eu-central-1.compute.internal
Starting pod/ip-10-0-148-127eu-central-1computeinternal-debug ...
To use host binaries, run `chroot /host`

Pod IP: 10.0.148.127
If you don't see a command prompt, try pressing enter.
sh-4.4# echo "debug-pod" > /WhereAe.g., Fedora Silverblue 32mI
sh-4.4# cat /WhereAmI 
debug-pod
sh-4.4# chroot /host bash
[root@ip-10-0-148-127 /]# podman ps -a
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
[root@ip-10-0-148-127 /]# toolbox
Trying to pull registry.redhat.io/rhel8/support-tools:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 3b4376bfc048 done  
Copying blob 296e14ee2414 done  
Copying blob 356f18f3a935 done  
Copying config 6ad911cd1a done  
Writing manifest to image destination
Storing signatures
6ad911cd1a8b431676ea12e242b02c3210a28660fdbfda3b6b43b53909fb48a6
Spawning a container 'toolbox-root' with image 'registry.redhat.io/rhel8/support-tools'
Detected RUN label in the container image. Using that as the default...
[root@ip-10-0-148-127 /]# 
[root@ip-10-0-148-127 /]# cat /WhereAmI
cat: /WhereAmI: No such file or directory
# exit
exit
Error: `/proc/self/exe run -it --name toolbox-root --privileged --ipc=host --net=host --pid=host -e HOST=/host -e NAME=toolbox-root -e IMAGE=registry.redhat.io/rhel8/support-tools:latest -v /run:/run -v /var/log:/var/log -v /etc/machine-id:/etc/machine-id -v /etc/localtime:/etc/localtime -v /:/host registry.redhat.io/rhel8/support-tools:latest` failed: exit status 1
/usr/bin/toolbox: failed to runlabel on image 'registry.redhat.io/rhel8/support-tools'
[root@ip-10-0-148-127 /]# podman ps -a
CONTAINER ID  IMAGE                                          COMMAND        CREATED         STATUS                     PORTS   NAMES
1533ac77446a  registry.redhat.io/rhel8/support-tools:latest  /usr/bin/bash  23 seconds ago  Exited (1) 10 seconds ago          toolbox-root
[root@ip-10-0-148-127 /]# toolbox
Container 'toolbox-root' already exists. Trying to start...
(To remove the container and start with a fresh toolbox, run: sudo podman rm 'toolbox-root')
toolbox-root
Container started successfully. To exit, type 'exit'.
WARN[0000] Cannot move process 155893 to cgroup "/sys/fs/cgroup/cpuset/machine.slice/libpod-conmon-1533ac77446a2ff81c381eddbea90bf035077c9e8664980c4cf57fe9eed1ea9d.scope" 
[root@ip-10-0-148-127 /]# cat /WhereAmI 
debug-pod
[root@ip-10-0-148-127 /]# exit
[root@ip-10-0-148-127 /]# exit
sh-4.4# exit

**Steps how to reproduce the behaviour**
1. Run `oc debug node/<NODE>`
2. Inside the debug Pod, run `echo "debug-pod" > /WhereAmI`
3. Change to the host: `chroot /host bash`
4. Run the toolbox container: `toolbox`
5. Verify that `cat /WhereAmI` returns "cat: /WhereAmI: No such file or directory" as expected (as we are in the toolbox container).
6. `exit` and restart toolbox using `toolbox`
7. Run `cat /WhereAmI` again

**Expected behaviour**
~~~
# cat /WhereAmI
cat: /WhereAmI: No such file or directory
~~~

**Actual behaviour**
~~~
[root@ip-10-0-148-127 /]# cat /WhereAmI 
debug-pod
~~~

**Output of `toolbox --version` (v0.0.90+)**
e.g., `toolbox version 0.0.90`

**Toolbox package info (`rpm -q toolbox`)**
e.g., `toolbox-0.0.18-2.fc32.noarch`

**Output of `podman version`**
e.g.,
```
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

**Podman package info (`rpm -q podman`)**
e.g., `podman-1.9.2-1.fc32.x86_64`

**Info about your OS**
cri-o 4.7

**Additional context**
- Also any `podman exec -it toolbox-root SOME_COMMAND` is executed on the debug pod and not in the running toolbox container.

**Comment by HarryMichal** [comment]
Hi @wgahnagl! This bug seems to be related to https://github.com/coreos/toolbox and not this particular project. Please, report it there. Closing.

**Comment by debarshiray** [comment]
> [root@ip-10-0-148-127 /]# toolbox
> Trying to pull registry.redhat.io/rhel8/support-tools:latest...
> Getting image source signatures
> Checking if image destination supports signatures
> Copying blob 3b4376bfc048 done
> Copying blob 296e14ee2414 done
> Copying blob 356f18f3a935 done
> Copying config 6ad911cd1a done
> Writing manifest to image destination
> Storing signatures
> 6ad911cd1a8b431676ea12e242b02c3210a28660fdbfda3b6b43b53909fb48a6
> Spawning a container 'toolbox-root' with image 'registry.redhat.io/rhel8/support-tools'
> Detected RUN label in the container image. Using that as the default...
> [root@ip-10-0-148-127 /]#

This trace is clearly not from this code base.

*For others who might be as confused as me, the version numbers mentioned in the issue are just example placeholders from the GitHub template. They aren't relevant to this particular issue.*
