### ISSUE TITLE
Container name as env in toolbox or as hostname

### ISSUE THREAD

**Issue by mvala** [containers/toolbox#926]
We are using multiple containers and we would like to know what container we are running it via `PS1`. Would it be possible that container name would be passed as ENV variable so we can adjust it, or better set hostname as container name or at least to have this option while creating toolbox

**Comment by mvala** [comment]
Maybe it is duplicate of #771

**Comment by HarryMichal** [comment]
One could use `/run/.containerenv` to read the name of the container.

**Comment by mvala** [comment]
Thanks this is solution.
