### ISSUE TITLE
`toolbox create` command (ran from within toolbx) is not failing when container already exists.

### ISSUE THREAD

**Issue by JayDoubleu** [containers/toolbox#957]
**Describe the bug**
`toolbox create` command is not failing when container already exists while running from within toolbox

**Steps how to reproduce the behaviour**
```
[user@hostname ~]$ toolbox create --distro fedora --release f35
Error: container fedora-toolbox-35 already exists
Enter with: toolbox enter
Run 'toolbox --help' for usage.
[user@hostname ~]$ echo $?
1

[user@hostname ~]$ toolbox run toolbox create --distro fedora --release f35
[user@hostname ~]$ echo $?
0
[user@hostname ~]$ 
```

**Expected behaviour**
Should return `Error: container fedora-toolbox-35 already exists` and return code 1

**Actual behaviour**
No output and return code 0

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.2`

**Toolbox package info (`rpm -q toolbox`)**
e.g., `toolbox-0.0.18-2.fc32.noarch`

**Output of `podman version`**
```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 20:25:37 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.4.2-1.fc35.x86_64`

**Info about your OS**
e.g., Fedora Silverblue 35

**Other information**

Same result when running from interactive shell inside toolbox as well as with `toolbox run`

**Comment by JayDoubleu** [comment]
In fact, seems like `toolbox create` just returns 0 when ran in general 
```
toolbox create --distro fedora --release f34
echo $?
0
```

**Comment by debarshiray** [comment]
Good catch! It seems that while tunneling things back and forth over `flatpak-spawn`, the standard error output and the exit codes are getting lost.

**Comment by JayDoubleu** [comment]
There is still few bugs here and there with flatpak-spawn it seems (https://github.com/flatpak/flatpak/issues/3697). I'm not sure if it was designed to perform things toolbx requires. 

Out of curiosity, would it be a difficult task for this logic to be embedded into a toolbx itself in case flatpak-spawn is trying to solve different problems and has its own roadmap?

**Comment by debarshiray** [comment]
@HarryMichal we might have to take this off the milestone for 0.1.0 if this ends up requiring some major surgery.

**Comment by debarshiray** [comment]
> Out of curiosity, would it be a difficult and reasonable task for this logic to
> be embedded into a toolbx itself

Yes, possibly.

> in case flatpak-spawn is trying to solve
> different problems and has its own roadmap?

That's unlikely. It's the same group of people after all. We'll see. We have to figure out exactly what's going wrong here.

**Comment by JayDoubleu** [comment]
`flatpak-spawn --host --watch-bus --forward-fd=1 --forward-fd=2 --directory="$(pwd)" --env=TERM=xterm-256color toolbox create fedora-toolbox-35` <- this seems to work ok tho ( stolen from https://github.com/containers/toolbox/issues/863#issuecomment-910157370)

**Comment by debarshiray** [comment]
I am going to close this now.  Please leave a comment or open a new issue if you have reason to believe otherwise.  My apologies that it took so long to get to it.
