### ISSUE TITLE
Bash completion errors for invalid subcommands

### ISSUE THREAD

**Issue by oturpe** [containers/toolbox#975]
**Describe the bug**
I was trying to remove a container I do not need any more.
The name of the container was `rawhide-test`,
so I typed: `$ toolbox remove raw`
and tried to save me some typing by invoking bash completion with `<Tab>`.
The following error was printed:

```
bash: options: bad array subscript
```

This happens because `remove` is not a Toolbox subcommand,
the correct command is `rm`,
In which case bash completion works as expected.
But, every other tool's bash completion simply does not complete or suggest anything
when there are no completions available.

**Steps how to reproduce the behaviour**
1.Type, but do not hit enter: `$ toolbox invalid-command `
2. Invoke bash completion by hitting `<Tab>`

**Expected behaviour**
Nothing happens.

**Actual behaviour**
Error as given in the description appears.

**Screenshots**
n/a

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.2`

**Toolbox package info (`rpm -q toolbox`)**
`toolbox-0.0.99.2^3.git075b9a8d2779-4.fc35.x86_64`

**Output of `podman version`**
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 23:45:07 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
`podman-3.4.4-1.fc35.x86_64`

**Info about your OS**
Fedora Workstation 35

**Additional context**
n/a

**Comment by HarryMichal** [comment]
Thank you for the report, @oturpe! I can reproduce it on my machine, too. I believe #840 should fix this.

**Comment by olivergs** [comment]
The problem right now is that the completion file shipped is out of sync with the completion system we already have implemented upstream.

If you want a workaround, just do:

`toolbox completion bash > right_completions`

and then

`source ./right_completions`

After that you will get the right behaviour.

The fix upstream should be as easy as replacing the current bash completion file with the contents of the right_completions file.

**Comment by oturpe** [comment]
Thank you both!
Pull request #840 does fix the problem,
as does using the completions from `$ toolbox completion bash`.
However, both solutions could still be improved [like I explain in this pr comment](https://github.com/containers/toolbox/pull/840#issuecomment-1009290952)

I am also wondering, if there is a generator for completions in place,
why is it not run during build and the result installed?
Then the completions would never get out of sync.

**Comment by HarryMichal** [comment]
> Pull request #840 does fix the problem, as does using the completions from `$ toolbox completion bash`. 

Mmm... I believe these are the same :).

> However, both solutions could still be improved [like I explain in this pr comment](https://github.com/containers/toolbox/pull/840#issuecomment-1009290952)

Thanks for the insight!

> I am also wondering, if there is a generator for completions in place, why is it not run during build and the result installed? Then the completions would never get out of sync.

That's what #840 is trying to accomplish :).
