### ISSUE TITLE
toolbox immediately fails after clean rpm install on official F35/podman images

### ISSUE THREAD

**Issue by castedo** [containers/toolbox#989]
**Describe the bug**

For the following steps use $IMAGE as either of these two
 `registry.fedoraproject.org/fedora:35` OR `quay.io/podman/stable`
The 2nd one is "official" in the sense of being the repo for shortname "podman" in `/etc/containers/registries.conf.d/000-shortnames.conf` installed by podman and also described in this blog post:
https://www.redhat.com/sysadmin/podman-inside-container

**Steps how to reproduce the behaviour**
1. podman run -it --privileged --name toolbox-test $IMAGE
2. yum -y install toolbox
3. (only if using first image mentioned) useradd podman
4. sudo -i -u podman
5. toolbox --log-level=debug

**Expected behaviour**
Toolbox to start pulling default image and create container (container creation within a container). This would be nice scenario for people who want to tentatively try out toolbox without installing it and having to use it on their host machine. Also might be useful for testing, especially automated testing.

**Actual behaviour**
Get error message:
```
-bash: /usr/bin/toolbox: No such file or directory
```

**Toolbox package info (`rpm -q toolbox`)**
From within the container:
```
[podman@e9eee708b956 ~]$ rpm -q toolbox
toolbox-0.0.99.3-2.fc35.x86_64
```

**Output of `podman version`**
From within container:
```
[podman@e9eee708b956 ~]$ rpm -q podman
podman-3.4.4-1.fc35.x86_64
[podman@e9eee708b956 ~]$ podman version
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 21:45:07 2021
OS/Arch:      linux/amd64
[podman@e9eee708b956 ~]$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="35 (Container Image)"
ID=fedora
...
```
From **outside** the container on this host:
```
[castedo@nasa ~]$ rpm -q podman
podman-3.3.1-9.module+el8.5.0+12697+018f24d7.x86_64
[castedo@nasa ~]$ podman version
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Tue Sep 21 04:41:42 2021
OS/Arch:      linux/amd64
[castedo@nasa ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
```

**Additional context**

Here's the full terminal output:
```
[castedo@nasa ~]$ podman run -it --privileged --name toolbox-test quay.io/podman/stable
[root@0468736dbfa2 /]# yum -y install toolbox
Fedora 35 - x86_64                                                                                                        1.2 MB/s |  79 MB     01:05
Fedora 35 openh264 (From Cisco) - x86_64                                                                                  4.4 kB/s | 2.5 kB     00:00
Fedora Modular 35 - x86_64                                                                                                4.5 MB/s | 3.3 MB     00:00
Fedora 35 - x86_64 - Updates                                                                                              7.1 MB/s |  21 MB     00:02
Fedora Modular 35 - x86_64 - Updates                                                                                      3.2 MB/s | 2.8 MB     00:00
Dependencies resolved.
==========================================================================================================================================================
 Package                                       Architecture                  Version                                 Repository                      Size
==========================================================================================================================================================
Installing:
 toolbox                                       x86_64                        0.0.99.3-2.fc35                         updates                        2.3 M
Installing dependencies:
 flatpak-session-helper                        x86_64                        1.12.3-1.fc35                           updates                         43 k

Transaction Summary
==========================================================================================================================================================
Install  2 Packages

Total download size: 2.3 M
Installed size: 7.9 M
Downloading Packages:
(1/2): flatpak-session-helper-1.12.3-1.fc35.x86_64.rpm                                                                    101 kB/s |  43 kB     00:00    
(2/2): toolbox-0.0.99.3-2.fc35.x86_64.rpm                                                                                 2.4 MB/s | 2.3 MB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                     2.1 MB/s | 2.3 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                  1/1 
  Installing       : flatpak-session-helper-1.12.3-1.fc35.x86_64                                                                                      1/2 
  Installing       : toolbox-0.0.99.3-2.fc35.x86_64                                                                                                   2/2 
  Running scriptlet: toolbox-0.0.99.3-2.fc35.x86_64                                                                                                   2/2 
  Verifying        : flatpak-session-helper-1.12.3-1.fc35.x86_64                                                                                      1/2 
  Verifying        : toolbox-0.0.99.3-2.fc35.x86_64                                                                                                   2/2 

Installed:
  flatpak-session-helper-1.12.3-1.fc35.x86_64                                        toolbox-0.0.99.3-2.fc35.x86_64                                       

Complete!
[root@0468736dbfa2 /]# sudo -i -u podman
[podman@0468736dbfa2 ~]$ toolbox --log-level=debug
-bash: /usr/bin/toolbox: No such file or directory
[podman@0468736dbfa2 ~]$

**Comment by JayDoubleu** [comment]
```
$ podman run -it --privileged quay.io/podman/stable
[root@368c306e123b /]# dnf -qq -y install toolbox

Installed:
  flatpak-session-helper-1.12.3-1.fc35.x86_64                                                                      toolbox-0.0.99.3-2.fc35.x86_64                                                                     

[root@368c306e123b /]# mkdir -p /run/host/usr/lib64/
[root@368c306e123b /]# ln -s /lib64/ld-linux-x86-64.so.2 /run/host/usr/lib64/ld-linux-x86-64.so.2
[root@368c306e123b /]# toolbox
Error: TOOLBOX_PATH not set
[root@368c306e123b /]# export TOOLBOX_PATH=/usr/bin/toolbox
[root@368c306e123b /]# toolbox
Error: missing command

create    Create a new toolbox container
enter     Enter an existing toolbox container
list      List all existing toolbox containers and images

Run 'toolbox --help' for usage.
[root@368c306e123b /]# 
```

**Comment by debarshiray** [comment]
> **Steps how to reproduce the behaviour**
> 
>     1. podman run -it --privileged --name toolbox-test $IMAGE
> 
>     2. yum -y install toolbox
> 
>     3. (only if using first image mentioned) useradd podman
> 
>     4. sudo -i -u podman
> 
>     5. toolbox --log-level=debug
>
> [...]
> 
> **Actual behaviour** Get error message:
> 
> ```
> -bash: /usr/bin/toolbox: No such file or directory
> ```

Other than what @JayDoubleu already demonstrated, [here](https://github.com/containers/toolbox/commit/6063eb27b98939942e316771224c5653a9b2e59b) is the background behind this particular error message.

**Comment by debarshiray** [comment]
Anyway, taking a step back ...

While it's possible to run [Podman inside a Podman container](https://www.redhat.com/sysadmin/podman-inside-container), and even though Toolbx uses Podman under the hood, it's not a supported configuration for Toolbx.

Toolbx has a very specific [goal](https://containertoolbx.org/) of offering containerized interactive command line environments for development and troubleshooting.  It's simply not meant to be run from inside a non-Toolbx container.  You can use it from inside a Toolbx container, though.  ;)

To carry on with the example from @JayDoubleu :
```
[podman@28025e8c6f64 ~]$ export TOOLBOX_PATH=/usr/bin/toolbox
[podman@28025e8c6f64 ~]$ toolbox 
Error: missing command

create    Create a new toolbox container
enter     Enter an existing toolbox container
list      List all existing toolbox containers and images

Run 'toolbox --help' for usage.
[podman@28025e8c6f64 ~]$ toolbox --help
Error: this is not a toolbox container
```

**Comment by debarshiray** [comment]
Closing.  Thanks for stopping by!

**Comment by castedo** [comment]
> Toolbx has a very specific [goal](https://containertoolbx.org/) of offering containerized interactive command line environments for development and troubleshooting.

The question I can raise is whether sometimes troubleshooting involves troubleshooting toolbx itself. For instance, something stops working when run inside a toolbx container ... is the problem due to some toolbx interaction or a problem due to something else?

Being able to run toolbx in a "clean" container with as few dependencies as possible on the host probably helps troubleshooting in these cases.

**Comment by debarshiray** [comment]
> The question I can raise is whether sometimes troubleshooting involves troubleshooting toolbx itself.

Some of us do hack on Toolbx inside a Toolbx container on a Fedora Silverblue host.

The `toolbox` binary is such that you can build it inside a Toolbx container that matches the host, and then use the same binary from the host.  So, you hack on it and build it inside the container, and then use the generated binary from the host.

> For instance, something stops working when run inside a toolbx container ... is the problem due to some toolbx interaction or a problem due to something else?

It's not that difficult to isolate the *toolbx interaction*, as you called it - it's a bunch of Podman invocations and the `toolbox init-container` entry point.  :)

> Being able to run toolbx in a "clean" container with as few dependencies as possible on the host probably helps troubleshooting in these cases.

Ultimately, Toolbx creates and runs containers, so it's really meant to be run on the host.  Running it nested is a trick with `flatpak-spawn --host ...`.  It invokes the binary that was used to create the container on the *host*, but everything is wired up to make it look as if it's working inside the container.

**Comment by debarshiray** [comment]
By the way, I filed https://github.com/containers/toolbox/issues/1183 to improve the error handling inside non-Toolbx containers.
