### ISSUE TITLE
let contents of file at standard path in base image replace purple hexagon in prompt

### ISSUE THREAD

**Issue by castedo** [containers/toolbox#990]
[cnest](https://github.com/castedo/cnest) will use the contents found in `/etc/nestsign` in the base image to set the prefix in the prompt of the container.
https://github.com/castedo/cnest/blob/d3a333fac1c92356ee406ece8cbc05818fefa20b/cnest/data/profile.d/nestsignprompt.sh#L2

This help make clear which of multiple containers environments I am in ... and it's fun. :smiley: For instance, in the container environment I have with an insane number of package for publishing (LaTeX etc...) I have a green pine tree. For my ancient centos 7 container full of old crap I'll probably never upgrade, I have a boring symbol. For my bleeding edge experimental development container I have a rocket emoji, etc... you get the idea.

Note that these are all environments for which I have separate Dockerfiles installing lots of packages. So adding a file with an emoji in the Dockerfile is easy.

I'm not sure `/etc/nestsign` is a great path that I chose. Perhaps toolbox wants to do something similar but with a diff path. If so let me know. Perhaps `cnest` and `toolbox` should use the same path as a general "here's a sign/symbol to use to indicate you're inside something in the prompt". There is some precedence for doing something similar with `/etc/debian_chroot`.

**Comment by HarryMichal** [comment]
I don't think this is something we want. We use the purple hexagon to symbolize the use of Toolbx. One could probably assume it's our simplified "logo" (obviously, we don't own the label in any way). We don't want to reinvent the wheel of shell styling and instead leave that to the likes of Oh My Zsh or Starship or just plain-old custom scripting. We can make the job easier by providing some stable interfaces that can be used to achieve these goals.

So, an interface to change the hexagon is something we don't desire. Thanks for using Toolbx and making a suggestion. It is appreciated!
