### ISSUE TITLE
Support running display servers on a VT

### ISSUE THREAD

**Issue by jadahl** [containers/toolbox#992]
Currently it's not possible to run a display server that relies using common technologies like logind and udev in a toolbox from a VT. This issue is meant to track the things than is needed to make this possible. The reason for wanting to do this is typically Wayland compositor development on a Silverblue system.

1. `sd_pid_get_session()` doesn't find the right session.

This function tries to find the session by looking at the cgroup on `getpid()`. This fails due to the cgroup not being what it expects. A typical cgroup it'd expect looks like `0::/user.slice/user-1000.slice/session-35.scope`, where `35` is the session, but instead it'll contain something like `0::/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-67cfc51a5110905b4c7fb6b49607fcf4aba9a9b88089d0fe57fc95cc87ce2755.scope/container`.

It might be possible to work around this issue in compositors by finding the session some other way. However, for this to be possible using the C API, some things seems to be needed:
  * `/run/systemd/users/$UID` needs to be exposed for systemd to find the sessions
  * `/run/systemd/sessions/` needs to be exposed

Some help from toolbox might be needed as well for allowing the display server to figure out what tty `toolbox enter` came from.

2. udev device enumeration doesn't work when matching seat.

Running e.g `udevadm trigger --dry-run --subsystem-match=drm --verbose -g seat` in a toolbox doesn't enumerate the available devices as it does when run outside of toolbox. Not passing `-g seat` makes it appear. Compositors use this to only attempt to open drm devices assigned to its seat. Have yet to investigate further what is needed.

If one works around these two issues (e.g. hard coding them), one can sucessfully run a display server running as drm master, managing mode setting devices and input devices.

Cc: @debarshiray, @swick, @HarryMichal

**Comment by jadahl** [comment]
Some more findings:

> sd_pid_get_session() doesn't find the right session.

`$XDG_SESSION_ID` is already exposed inside the toolbox; the display server should use use this instead of `sd_pid_get_session()`.

> udev device enumeration doesn't work when matching seat.

This needed exposing `/run/udev/tags` from the host to work.

**Comment by jadahl** [comment]
For reference, https://github.com/containers/toolbox/pull/997 makes things work better. Together with using `$XDG_SESSION_ID` things appears to launch properly with toolboxes created with that PR applied.

**Comment by debarshiray** [comment]
> Some more findings:
> 
> > sd_pid_get_session() doesn't find the right session.
> 
> `$XDG_SESSION_ID` is already exposed inside the toolbox; the display server should use use this instead of `sd_pid_get_session()`.

One thing though.  `XDG_SESSION_ID` is not set in my GNOME session on Fedora 36.  Did that change?

`XDG_SESSION_ID` is one of those environment variables that were propagated since the very beginning, and I can't remember if I noticed it in my environment or whether I picked it up from some code base or documentation somewhere as something that should be retained.

I see that there's an environment variable called `XDG_SESSION_CLASS` these days.  Should that be propagated inside Toolbx containers as well?  Is it new or did we simply miss it before?

**Comment by jadahl** [comment]
> One thing though. XDG_SESSION_ID is not set in my GNOME session on Fedora 36. Did that change?

Good question, so digged a bit, and seems we added it as a work around for not having a proper graphical session when starting from tty.

Here's a commit in mutter that introduces it.

    launcher: Use $XDG_SESSION_ID if available
    
    In some cases mutter is started in the user scope from a TTY (for
    example using toolbox). Using sd_pid_get_session fails because it's not
    in the session scope so it falls back to the primary session
    (sd_uid_get_display). We want to start mutter on the TTY we started
    mutter on however. Instead of relying on the scope to figure out the
    correct session we first look at $XDG_SESSION_ID which is set by
    systemd_pam.so.
    
> I see that there's an environment variable called XDG_SESSION_CLASS these days. Should that be propagated inside Toolbx containers as well? Is it new or did we simply miss it before?

I don't see that it's used by e.g. gnome-shell, it uses other mechanisms to determine whether a session is a "greeter" or "user", but gdm does appear to set it so for completeness sake, I guess it doesn't hurt to forward it.

**Comment by debarshiray** [comment]
> > One thing though. XDG_SESSION_ID is not set in my GNOME session on Fedora 36. Did that change?
> 
> Good question, so digged a bit, and seems we added it as a work around for not having a proper graphical session when starting from tty.
> 
> Here's a commit in mutter that introduces it.
> 
> ```
> launcher: Use $XDG_SESSION_ID if available
> ```

Thanks for that pointer, @jadahl 

Yes, that's Mutter [commit 8ebdae809222af3c](https://gitlab.gnome.org/GNOME/mutter/-/commit/8ebdae809222af3c1ea99a0296a59bdaaa6d977b) which landed in Mutter 42.beta which is what we have in Fedora >= 36.  Cool.

**Comment by swick** [comment]
With #997 merged gnome-shell in a toolbox on a tty works now for the most part. The only remaining issue I know about is  #1203.

**Comment by debarshiray** [comment]
> > I see that there's an environment variable called XDG_SESSION_CLASS these days. Should that be propagated inside Toolbx containers as well? Is it new or did we simply miss it before?
> 
> I don't see that it's used by e.g. gnome-shell, it uses other mechanisms to determine whether a session is a "greeter" or "user", but gdm does appear to set it so for completeness sake, I guess it doesn't hurt to forward it.

I have tried to propagate `XDG_SESSION_CLASS` in https://github.com/containers/toolbox/pull/1235

**Comment by debarshiray** [comment]
Closing.
